const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};
global.indexedDB={open(){return{}}};global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
global.document={getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return{imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){}}}}}};
const root=path.resolve(__dirname,"..");
const files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(value,message)=>{if(!value)failures.push(message)},two=new Set(["market","inn","lodge","guild","mansion"]);
expect(HL.DATA.version===11,`version ${HL.DATA.version}`);expect(Object.keys(HL.DATA.buildingScenes).length===120,"port count");expect(!files.includes("legacy_animation.js"),"legacy animation loaded");
for(const id of["rian","damian","orso","mira","vardo"]){const manifest=HL.DATA.spriteManifestsV11[id];expect(!!manifest,`${id} manifest`);for(const mode of["town","interior"]){expect(Object.keys(manifest.modes[mode].frames).length===8,`${id} ${mode} directions`);for(let d=0;d<8;d++)expect(manifest.modes[mode].frames[d].length===10,`${id} ${mode} ${d} frames`)}}
expect(HL.DATA.spriteManifestsV11.rian.modes.town.src.includes("V11/Characters/rian_town_v11.png"),"rian town v11 source");
expect(HL.DATA.spriteManifestsV11.rian.modes.interior.src.includes("V11/Characters/rian_interior_v11.png"),"rian interior v11 source");
for(const id of["damian","orso","mira","vardo"]){expect(HL.DATA.spriteManifestsV11[id].modes.town.src.includes(`/V11/Characters/${id}_town_v11.png`),`${id} town v11 source`);expect(HL.DATA.spriteManifestsV11[id].modes.interior.src.includes(`/V11/Characters/${id}_interior_v11.png`),`${id} interior v11 source`)}
for(const type of["caravel","cog","galley","brig","carrack"]){const manifest=HL.DATA.shipVisualManifestsV11[type];expect(manifest?.world.frameWidth===96,`${type} world size`);expect(manifest?.battle.frameWidth===144,`${type} battle size`);for(const layers of Object.values(manifest.layers))for(const src of Object.values(layers))expect(fs.existsSync(path.resolve(root,src)),`${type} missing ${src}`)}
const distanceToRect=(x,y,r)=>{const rx=Math.max(r[0],Math.min(x,r[0]+r[2])),ry=Math.max(r[1],Math.min(y,r[1]+r[3]));return Math.hypot(x-rx,y-ry)};
const blocked=(floor,x,y)=>floor.collision.solids.some(r=>x+.5>=r[0]&&x+.5<r[0]+r[2]&&y+.5>=r[1]&&y+.5<r[1]+r[3]);
const reachable=floor=>{const start=[Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])],seen=new Set([start.join(",")]),queue=[start];while(queue.length){const[x,y]=queue.shift();for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(nx<0||ny<0||nx>=32||ny>=18||seen.has(key)||blocked(floor,nx,ny))continue;seen.add(key);queue.push([nx,ny])}}return seen};
const reachesRect=(seen,rect)=>[...seen].some(key=>{const[x,y]=key.split(",").map(Number);return distanceToRect(x+.5,y+.5,rect)<.8});
for(const [portId,group]of Object.entries(HL.DATA.buildingScenes))for(const[facility,building]of Object.entries(group)){
  expect(Object.keys(building.floors).length===(two.has(facility)?2:1),`${portId}:${facility} floors`);
  for(const floor of Object.values(building.floors)){const seen=reachable(floor);for(const stair of floor.stairs||[]){expect(["grand","side"].includes(stair.style),`${floor.id} stair style`);expect(stair.auto&&stair.autoRect,`${floor.id} auto stair`);expect(distanceToRect(stair.spawn[0],stair.spawn[1],stair.rect)<.01,`${floor.id} stair spawn`);expect(reachesRect(seen,stair.autoRect),`${floor.id} auto stair unreachable`);const[x,y,w,h]=stair.rect;expect(floor.collision.solids.some(r=>r[0]===x&&r[1]===y&&r[2]===1&&r[3]===h),`${floor.id} left rail collision`);expect(floor.collision.solids.some(r=>r[0]===x+w-1&&r[1]===y&&r[2]===1&&r[3]===h),`${floor.id} right rail collision`)}}}
const prior=HL.Game.freshState();prior.version=10;prior.money=4321;prior.bank.balance=876;prior.fragmentBoard.owned=["f01","f02"];prior.prologueState.phase="mansion-2f";const migrated=HL.migrateStateV11(prior);
expect(migrated.version===11,"migration version");expect(migrated.money===4321&&migrated.bank.balance===876,"migration economy");expect(migrated.fragmentBoard.owned.length===2,"migration fragments");expect(migrated.prologueState.phase==="mansion-2f","migration prologue");
expect(HL.Game.freshState().stairCooldown===0,"fresh stair cooldown");
const images={town:{width:480,height:576,transparent:1,cornersOpaque:false},interior:{width:640,height:768,transparent:1,cornersOpaque:false}},valid=JSON.parse(JSON.stringify(HL.DATA.spriteManifestsV11.rian));valid.id="custom";
expect(HL.UserAssetStore.validate(valid,images).length===0,"valid dual manifest rejected");
expect(HL.UserAssetStore.validate(valid,{town:images.town}).some(v=>v.includes("실내 PNG")),"missing interior accepted");
const badFrame=JSON.parse(JSON.stringify(valid));badFrame.modes.town.frames[0][0].x=999;expect(HL.UserAssetStore.validate(badFrame,images).some(v=>v.includes("1번 프레임")),"bad frame accepted");
const badPivot=JSON.parse(JSON.stringify(valid));badPivot.modes.interior.frames[0][1].pivot[1]-=3;expect(HL.UserAssetStore.validate(badPivot,images).some(v=>v.includes("피벗")),"pivot jitter accepted");
const overlap=JSON.parse(JSON.stringify(valid));overlap.modes.town.frames[0][1].x=overlap.modes.town.frames[0][0].x;expect(HL.UserAssetStore.validate(overlap,images).some(v=>v.includes("겹칩니다")),"overlap accepted");
const editorHtml=fs.readFileSync(path.resolve(root,"../Tools/sprite_editor.html"),"utf8");for(const id of["townFile","interiorFile","exportTown","exportInterior","exportJson"])expect(editorHtml.includes(`id="${id}"`),`editor missing ${id}`);
expect(fs.existsSync(path.resolve(root,HL.DATA.tileSetV11.atlas)),"tile atlas missing");expect(fs.existsSync(path.resolve(root,"../Tools/sprite_editor.html")),"sprite editor missing");
console.log(JSON.stringify({version:HL.DATA.version,ports:Object.keys(HL.DATA.buildingScenes).length,ships:Object.keys(HL.DATA.shipVisualManifestsV11).length,sprites:Object.keys(HL.DATA.spriteManifestsV11).length,failures:failures.slice(0,30),failureCount:failures.length},null,2));if(failures.length)process.exitCode=1;
