const fs=require("fs"),vm=require("vm"),path=require("path"),{createCanvas,Image:CanvasImage,loadImage}=require("@napi-rs/canvas");
const root=path.resolve(__dirname,".."),out=path.resolve(root,"../Docs/Screenshots/V20");class LocalImage extends CanvasImage{set src(value){this._src=value;super.src=fs.readFileSync(path.resolve(root,value))}get src(){return this._src}get complete(){return this.width>0}get naturalWidth(){return this.width}}process.chdir(root);global.window=global;global.HL={};global.Image=LocalImage;global.Audio=class{play(){return Promise.resolve()}pause(){}};global.localStorage={getItem(){return null},setItem(){},removeItem(){}};global.indexedDB={open(){return{}}};global.addEventListener=()=>{};global.performance={now:()=>4200};global.document={querySelector(){return null},getElementById(){return null},createElement(){return createCanvas(960,540)}};
const files=["data.js","world_data.js","v5_data.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v17_data.js","v17_systems.js","v17_art.js","v18_data.js","v18_systems.js","v18_art.js","v19_data.js","v19_systems.js","v19_art.js","v20_data.js","v20_systems.js","v20_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const canvas=createCanvas(960,540),ctx=canvas.getContext("2d"),e={canvas,ctx,clear(color){ctx.fillStyle=color;ctx.fillRect(0,0,960,540)},text(value,x,y,color="white",align="left",size=16){ctx.fillStyle=color;ctx.textAlign=align;ctx.font=`${size}px sans-serif`;ctx.fillText(value,x,y)}};ctx.imageSmoothingEnabled=false;const art=new HL.Art({get(){return null}});fs.mkdirSync(out,{recursive:true});
async function main(){
  art.ensureV20();
  for(const scene of Object.values(HL.DATA.specialInteriorsV20)){const src=scene.background,image=await loadImage(path.resolve(root,src));art.images.v20Interiors[src]=image;art.assetLoadStateV20[src]={image,status:"ready",error:null}}
  for(const manifest of Object.values(HL.DATA.captainSpriteManifestsV20))for(const src of Object.values(manifest.images))if(!art.captainSpriteRendererV20.images[src])art.captainSpriteRendererV20.images[src]=await loadImage(path.resolve(root,src));
  const rendered=[];for(const cap of HL.DATA.captainsV16){const opening=HL.DATA.playableOpeningsV19[cap.id],map=HL.DATA.townDefinitionsV19[cap.startPort],building=HL.DATA.buildingScenes[cap.startPort][opening.facility],scene=building.floors["1f"],state=HL.migrateStateV20(HL.applyCaptainV16(HL.Game.freshState(),cap.id));state.currentPort=cap.startPort;state.mode="town";state.town={x:map.spawn[0],y:map.spawn[1],dir:4};state.partyFollowerState={render:[]};const townGame={e,s:state,npcs:map.npcs,playerAnim:.7,playerMoving:true,townMap:()=>map,townBuildings:()=>map.buildings.map(b=>({...b,name:b.label})),questTarget:()=>opening.facility};art.town(townGame);let name=`${cap.id}_${cap.startPort}_town_v20.png`;fs.writeFileSync(path.join(out,name),canvas.toBuffer("image/png"));rendered.push(name);state.mode="interior";state.interior={buildingId:opening.facility,id:opening.facility,floorId:"1f",x:scene.spawn[0],y:scene.spawn[1],dir:0};state.partyFollowerState={render:[]};const interiorGame={e,s:state,playerAnim:.7,playerMoving:true,currentBuilding:()=>building,questTarget:()=>opening.facility};art.v20SpecialInterior(interiorGame,scene,state.interior);name=`${cap.id}_${cap.startPort}_${opening.facility}_v20.png`;fs.writeFileSync(path.join(out,name),canvas.toBuffer("image/png"));rendered.push(name)}
  console.log(JSON.stringify({rendered,out},null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1});
