const fs=require("fs"),vm=require("vm"),path=require("path"),{createCanvas,Image,loadImage}=require("@napi-rs/canvas");
const root=path.resolve(__dirname,".."),out=path.resolve(root,"../Docs/Screenshots/V15");process.chdir(root);global.window=global;global.HL={};global.Image=Image;global.Audio=class{play(){return Promise.resolve()}pause(){}};global.localStorage={getItem(){return null},setItem(){},removeItem(){}};global.indexedDB={open(){return{}}};global.document={createElement:()=>createCanvas(1,1)};let clock=2600;global.performance={now:()=>clock};
const files=["data.js","world_data.js","v5_data.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const canvas=createCanvas(960,540),ctx=canvas.getContext("2d");ctx.imageSmoothingEnabled=false;const engine={canvas,ctx,clear(color){ctx.fillStyle=color;ctx.fillRect(0,0,960,540)},text(value,x,y,color="white",align="left",size=16){ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline="alphabetic";ctx.font=`${size}px sans-serif`;ctx.fillText(value,x,y)}};
async function main(){fs.mkdirSync(out,{recursive:true});const art=new HL.Art({get(){return null}});art.images.v15Tiles=await loadImage(path.resolve(root,HL.DATA.tileMetaV15.src));art.images.v15Props=await loadImage(path.resolve(root,HL.DATA.propSpritesV15.src));art.ensureV11();for(const id of ["rian","damian"]){const manifest=HL.DATA.spriteManifestsV11[id];for(const mode of ["town","interior"]){const src=manifest.modes[mode].src;art.spriteRendererV11.images[`${id}:${mode}:base`]=await loadImage(path.resolve(root,src))}}art.ensureV12();for(const facility of ["market","inn","lodge","harbor","guild","shipyard"]){const id=`owner_bella_${facility}`,recipe=HL.DATA.appearanceRecipeV12(id);for(const src of Object.values(recipe.sheet))if(!art.spriteRendererV12.images[src])art.spriteRendererV12.images[src]=await loadImage(path.resolve(root,src))}
  const rendered=[];
  for(const facility of ["market","inn","guild","shipyard","harbor","mansion"]){const building=HL.DATA.buildingScenes.bella[facility],scene=building.floors["1f"],state=HL.Game.freshState();state.currentPort="bella";state.mode="interior";state.interior={id:facility,buildingId:facility,floorId:"1f",x:scene.spawn[0],y:scene.spawn[1]-2.4,dir:0};state.v12={enteredAt:-5000};const game={e:engine,s:state,playerAnim:.42,playerMoving:true,questTarget:()=>facility,currentBuilding:()=>building};clock+=330;art.v15InteriorScene(game,scene,state.interior,"rian");const name=`lisbon_${facility}_v15.png`;fs.writeFileSync(path.join(out,name),canvas.toBuffer("image/png"));rendered.push(name)}
  console.log(JSON.stringify({rendered,out},null,2))
}
main().catch(error=>{console.error(error);process.exitCode=1});
