const assert = require('assert');
require('./boot_v21.js');
setImmediate(() => {
  const game = new HL.Game();
  game.e.selectedSlot = 99;
  game.newGame('ines');
  game.handleWakeV21('caller');
  game.handleOpeningV21('news');
  assert.equal(game.s.openingWakeV21.completedSteps, undefined, 'news must not skip daily work');
  for (const step of ['work', 'news', 'consult', 'prepare']) game.handleOpeningV21(step);
  assert.equal(game.s.openingWakeV21.completed, true);
  game.handleWakeV21('caller');
  assert.equal(game.s.openingWakeV21.stage, 4, 'repeat caller must not reset progress');
  assert.equal(game.s.openingWakeV21.completedSteps.length, 4);
  game.handleOpeningV21('work');
  assert.equal(game.s.openingWakeV21.completedSteps.length, 4, 'repeat work must be idempotent');
  game.s.interior.x = 10.5;
  game.s.interior.y = 12.5;
  const restored = HL.migrateStateV21(game.s);
  assert.equal(restored.interior.x, 10.5);
  assert.equal(restored.interior.y, 12.5);
  game.s.tradeState = { selected: Object.keys(HL.DATA.ports.seville.market)[0], intent: 'buy', quantity: 1 };
  game.renderV21Trade = () => {};
  game.dispatchAction('v21-trade-mode:sell');
  assert.equal(game.s.tradeState.intent, 'sell');
  game.dispatchAction('v21-trade-mode:buy');
  assert.equal(game.s.tradeState.intent, 'buy');
  console.log('Seville opening order, repeat interaction, position restore and trade mode: PASS');
});
