const fs=require("fs"),vm=require("vm"),path=require("path");
const {loadImage,createCanvas}=require("@napi-rs/canvas");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};
global.indexedDB={open(){return{}}};global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
global.document={getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return{imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){}}}}}};
const root=path.resolve(__dirname,"..");
const files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(value,message)=>{if(!value)failures.push(message)},two=new Set(["market","inn","lodge","guild","mansion"]),facilities=["market","inn","shipyard","guild","lodge","harbor","mansion","bank","estate","home"];
const blocked=(floor,x,y)=>floor.collision.solids.some(r=>x+.5>=r[0]&&x+.5<r[0]+r[2]&&y+.5>=r[1]&&y+.5<r[1]+r[3]);
const reachable=floor=>{const start=[Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])],seen=new Set([start.join(",")]),queue=[start];while(queue.length){const[x,y]=queue.shift();for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(nx<0||ny<0||nx>=floor.width||ny>=floor.height||seen.has(key)||blocked(floor,nx,ny))continue;seen.add(key);queue.push([nx,ny])}}return seen};
const reaches=(seen,r,range=1.7)=>[...seen].some(key=>{const[x,y]=key.split(",").map(Number),cx=x+.5,cy=y+.5,rx=Math.max(r[0],Math.min(cx,r[0]+r[2])),ry=Math.max(r[1],Math.min(cy,r[1]+r[3]));return Math.hypot(cx-rx,cy-ry)<=range});
(async()=>{
  expect(HL.DATA.version===12,`version ${HL.DATA.version}`);expect(Object.keys(HL.DATA.buildingScenes).length===120,"port count");expect(files.slice(-3).join(",")==="v12_data.js,v12_systems.js,v12_art.js","script order");
  let floorCount=0;for(const portId of HL.DATA.portOrder){const group=HL.DATA.buildingScenes[portId];for(const facility of facilities){const building=group[facility];expect(!!building,`${portId}:${facility} missing`);expect(Object.keys(building.floors).length===(two.has(facility)?2:1),`${portId}:${facility} floor count`);for(const floor of Object.values(building.floors)){floorCount++;expect(floor.width>=40&&floor.height>=24,`${floor.id} small`);expect(floor.tiles.length===floor.height&&floor.tiles.every(row=>row.length===floor.width),`${floor.id} tile dimensions`);expect(!blocked(floor,Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])),`${floor.id} blocked spawn`);const seen=reachable(floor);expect(reaches(seen,floor.exit.rect),`${floor.id} exit unreachable`);for(const stair of floor.stairs)expect(reaches(seen,stair.autoRect),`${floor.id} stair unreachable`);for(const hot of floor.hotspots)expect(reaches(seen,hot.rect),`${floor.id}:${hot.id} unreachable`);for(const npc of floor.npcs)expect(npc.workZone&&npc.y<npc.workZone[1]+npc.workZone[3],`${floor.id} owner work zone`)}}}
  expect(floorCount===1800,`floor count ${floorCount}`);
  const recipes=Object.values(HL.DATA.appearanceRecipesV12),signatures=new Set(recipes.map(r=>r.appearanceSignature));expect(recipes.length>=1325,`appearance count ${recipes.length}`);expect(signatures.size===recipes.length,"duplicate appearance signature");for(const facility of facilities){const recipe=HL.DATA.appearanceRecipeV12(`owner_bella_${facility}`);expect(recipe.profession===({market:"merchant",inn:"innkeeper",shipyard:"shipwright",guild:"guildmaster",lodge:"innkeeper",harbor:"harbormaster",mansion:"noble",bank:"banker",estate:"banker",home:"noble"}[facility]),`${facility} owner profession`)}
  for(const recipe of recipes.slice(0,40))for(const src of Object.values(recipe.sheet))expect(fs.existsSync(path.resolve(root,src)),`missing NPC ${src}`);
  const objectImage=await loadImage(path.resolve(root,HL.DATA.objectSpritesV12.atlas)),canvas=createCanvas(objectImage.width,objectImage.height),c=canvas.getContext("2d");c.drawImage(objectImage,0,0);const alpha=c.getImageData(0,0,objectImage.width,objectImage.height).data;let transparent=0;for(let i=3;i<alpha.length;i+=4)if(alpha[i]===0)transparent++;expect(transparent>alpha.length/4*.5,"object atlas lacks transparency");
  for(const [type,manifest] of Object.entries(HL.DATA.shipVisualManifestsV12))for(const [size,m] of Object.entries({world:manifest.world,battle:manifest.battle}))for(const src of Object.values(manifest.layers[size])){expect(fs.existsSync(path.resolve(root,src)),`${type} missing ${src}`);const image=await loadImage(path.resolve(root,src));expect(image.width===m.frameWidth*32&&image.height===m.frameHeight,`${type} ${size} atlas dimensions`)}
  const prior=HL.Game.freshState();prior.version=11;prior.money=7654;prior.bank.balance=432;prior.mode="interior";prior.currentPort="bella";prior.interior={id:"guild",buildingId:"guild",floorId:"2f",x:26,y:14,dir:6};prior.fragmentBoard.owned=["f01","f02"];const migrated=HL.migrateStateV12(prior);expect(migrated.version===12,"migration version");expect(migrated.money===7654&&migrated.bank.balance===432,"migration economy");expect(migrated.fragmentBoard.owned.length===2,"migration fragments");expect(migrated.mode==="interior"&&migrated.interior.floorId==="2f","migration interior");expect(!blocked(HL.DATA.buildingScenes.bella.guild.floors["2f"],Math.floor(migrated.interior.x),Math.floor(migrated.interior.y)),"migration blocked position");
  console.log(JSON.stringify({version:HL.DATA.version,ports:Object.keys(HL.DATA.buildingScenes).length,floors:floorCount,appearanceRecipes:recipes.length,ships:Object.keys(HL.DATA.shipVisualManifestsV12).length,failures:failures.slice(0,40),failureCount:failures.length},null,2));if(failures.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exitCode=1});
