const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};
global.indexedDB={open(){return{}}};global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return{imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){}}}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(value,message)=>{if(!value)failures.push(message)},facilities=["market","inn","shipyard","guild","lodge","harbor","mansion","bank","estate","home"],two=new Set(["market","inn","lodge","guild","mansion"]),sizes={bank:[24,16],estate:[24,16],home:[24,16],market:[30,18],inn:[30,18],lodge:[30,18],harbor:[30,18],guild:[32,18],mansion:[40,24],shipyard:[40,24]};
const blocked=(floor,x,y)=>floor.collision.solids.some(r=>x+.5>=r[0]&&x+.5<r[0]+r[2]&&y+.5>=r[1]&&y+.5<r[1]+r[3]);
const reachable=floor=>{const start=[Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])],seen=new Set([start.join(",")]),queue=[start];while(queue.length){const[x,y]=queue.shift();for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(nx<0||ny<0||nx>=floor.width||ny>=floor.height||seen.has(key)||blocked(floor,nx,ny))continue;seen.add(key);queue.push([nx,ny])}}return seen};
const reaches=(seen,r,range=1.8)=>[...seen].some(key=>{const[x,y]=key.split(",").map(Number),cx=x+.5,cy=y+.5,rx=Math.max(r[0],Math.min(cx,r[0]+r[2])),ry=Math.max(r[1],Math.min(cy,r[1]+r[3]));return Math.hypot(cx-rx,cy-ry)<=range});
let floors=0,maxOwnerDistance=0,minProps=Infinity,minInteractions=Infinity;
for(const portId of HL.DATA.portOrder)for(const facility of facilities){const building=HL.DATA.buildingScenes[portId][facility];expect(Object.keys(building.floors).length===(two.has(facility)?2:1),`${portId}:${facility} floor count`);for(const floor of Object.values(building.floors)){floors++;expect(floor.width===sizes[facility][0]&&floor.height===sizes[facility][1],`${floor.id} size ${floor.width}x${floor.height}`);expect(!blocked(floor,Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])),`${floor.id} blocked spawn`);const seen=reachable(floor);expect(reaches(seen,floor.exit.rect),`${floor.id} exit unreachable`);for(const stair of floor.stairs)expect(reaches(seen,stair.autoRect),`${floor.id} stair unreachable`);for(const h of floor.hotspots)expect(reaches(seen,h.rect),`${floor.id}:${h.id} unreachable`);minProps=Math.min(minProps,floor.props.length);minInteractions=Math.min(minInteractions,floor.hotspots.length);const owner=floor.npcs[0];if(owner){const d=Math.hypot(floor.spawn[0]-owner.x,floor.spawn[1]-owner.y);maxOwnerDistance=Math.max(maxOwnerDistance,d);expect(d<=(facility==="mansion"||facility==="shipyard"?18:12),`${floor.id} owner distance ${d.toFixed(1)}`)}}}
expect(HL.DATA.version===13,`version ${HL.DATA.version}`);expect(floors===1800,`floor count ${floors}`);expect(minProps>=35,`minimum props ${minProps}`);expect(minInteractions>=6,`minimum interactions ${minInteractions}`);
const prior=HL.Game.freshState();prior.version=12;prior.money=2222;prior.bank.balance=777;prior.currentPort="bella";prior.mode="interior";prior.interior={id:"shipyard",buildingId:"shipyard",floorId:"1f",x:61,y:37,dir:0};prior.fragmentBoard.owned=["f01","f02"];const migrated=HL.migrateStateV13(prior);expect(migrated.version===13,"migration version");expect(migrated.money===2222&&migrated.bank.balance===777,"migration economy");expect(migrated.fragmentBoard.owned.length===2,"migration fragments");expect(!blocked(HL.DATA.buildingScenes.bella.shipyard.floors["1f"],Math.floor(migrated.interior.x),Math.floor(migrated.interior.y)),"migration safe position");
const tradeState=HL.Game.freshState();tradeState.money=10000;tradeState.cargo.glass=0;tradeState.averageCost={};tradeState.marketStock={};const trade=new HL.TradeViewModel(tradeState),beforeMoney=tradeState.money,result=trade.commit("bella","glass","buy",5);expect(result.quantity===5,"trade quantity");expect(tradeState.cargo.glass===5,"trade cargo");expect(tradeState.money===beforeMoney-result.total,"trade money");expect(tradeState.averageCost.glass===result.price,"trade average");
const protectedState=HL.Game.freshState();protectedState.beginnerProtection={enabled:true,completed:false};expect(HL.isBeginnerProtected(protectedState),"beginner protection active");protectedState.campaign.chapterId="blue-ledger";expect(!HL.isBeginnerProtected(protectedState),"beginner protection ending");
console.log(JSON.stringify({version:HL.DATA.version,ports:HL.DATA.portOrder.length,floors,minProps,minInteractions,maxOwnerDistance:+maxOwnerDistance.toFixed(1),tradeQuantity:result.quantity,failures:failures.slice(0,60),failureCount:failures.length},null,2));if(failures.length)process.exitCode=1;
