const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};
global.indexedDB={open(){return{}}};global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return{imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){}}}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)},facilities=["market","inn","lodge","harbor","guild","mansion","shipyard"],two=new Set(["market","inn","lodge","guild","mansion"]),sizes={market:[26,16],inn:[26,16],lodge:[26,16],harbor:[26,16],guild:[28,18],mansion:[32,20],shipyard:[32,20]};
const blocked=(floor,x,y)=>x<0||y<0||x>=floor.width||y>=floor.height||floor.collision.solids.some(r=>x+.5>=r[0]&&x+.5<=r[0]+r[2]&&y+.5>=r[1]&&y+.5<=r[1]+r[3]);
const reachable=floor=>{const start=[Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])],seen=new Set([start.join(",")]),queue=[start];while(queue.length){const[x,y]=queue.shift();for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(seen.has(key)||blocked(floor,nx,ny))continue;seen.add(key);queue.push([nx,ny])}}return seen};
const reaches=(seen,r,range=1.8)=>[...seen].some(key=>{const[x,y]=key.split(",").map(Number),cx=x+.5,cy=y+.5,rx=Math.max(r[0],Math.min(cx,r[0]+r[2])),ry=Math.max(r[1],Math.min(cy,r[1]+r[3]));return Math.hypot(cx-rx,cy-ry)<=range});
let floors=0,minProps=Infinity,maxProps=0,minHotspots=Infinity;
for(const facility of facilities){
  const building=HL.DATA.buildingScenes.bella[facility];expect(building.version===15,`${facility} is not v15`);expect(Object.keys(building.floors).length===(two.has(facility)?2:1),`${facility} floor count`);
  for(const floor of Object.values(building.floors)){
    floors++;expect(floor.width===sizes[facility][0]&&floor.height===sizes[facility][1],`${floor.id} size`);expect(!blocked(floor,Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])),`${floor.id} spawn blocked`);
    const seen=reachable(floor);expect(reaches(seen,floor.exit.rect),`${floor.id} exit unreachable`);for(const stair of floor.stairs)expect(reaches(seen,stair.rect),`${floor.id} stair unreachable`);for(const h of floor.hotspots)expect(reaches(seen,h.rect),`${floor.id}:${h.id} unreachable`);
    minProps=Math.min(minProps,floor.props.length);maxProps=Math.max(maxProps,floor.props.length);minHotspots=Math.min(minHotspots,floor.hotspots.length);expect(floor.props.length>=18&&floor.props.length<=30,`${floor.id} prop count ${floor.props.length}`);expect(floor.hotspots.length>=6&&floor.hotspots.length<=8,`${floor.id} hotspot count`)
  }
}
expect(floors===12,`Lisbon floor count ${floors}`);expect(HL.DATA.buildingScenes.lume.market.version===13,"non-Lisbon interior did not remain V13");expect(HL.DATA.version===15,`version ${HL.DATA.version}`);
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");expect(!/src="v14_(data|systems|art)\.js"/.test(index),"V14 remains active");expect(/src="v15_art\.js"/.test(index),"V15 art not active");
const prior=HL.Game.freshState();prior.version=14;prior.money=3456;prior.bank.balance=812;prior.currentPort="bella";prior.mode="interior";prior.interior={id:"shipyard",buildingId:"shipyard",floorId:"1f",x:38,y:22,dir:0};prior.fragmentBoard.owned=["f01","f02","f03"];prior.campaign.chapterId="blue-ledger";const migrated=HL.migrateStateV15(prior);
expect(migrated.version===15,"migration version");expect(migrated.money===3456&&migrated.bank.balance===812,"migration economy");expect(migrated.fragmentBoard.owned.length===3,"migration fragments");expect(migrated.campaign.chapterId==="blue-ledger","migration campaign");expect(!blocked(HL.DATA.buildingScenes.bella.shipyard.floors["1f"],Math.floor(migrated.interior.x),Math.floor(migrated.interior.y)),"migration unsafe");
const engine=Object.create(HL.Engine.prototype);engine.saveSlot=(i,s)=>localStorage.setItem(engine.slotKey(i),JSON.stringify(s));localStorage.setItem(engine.v14SlotKey(1),JSON.stringify(prior));engine.migrateOld(1);expect(JSON.parse(localStorage.getItem(engine.v14SlotKey(1))).version===14,"V14 original save changed");expect(engine.loadSlot(1)?.version===15,"V14 save not copied to V15");
console.log(JSON.stringify({version:HL.DATA.version,floors,minProps,maxProps,minHotspots,failures:failures.slice(0,80),failureCount:failures.length},null,2));if(failures.length)process.exitCode=1;
