const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};
global.Audio=class{play(){return Promise.resolve()}pause(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.indexedDB={open(){return{}}};
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return{imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},measureText(v){return{width:String(v).length*6}},fillText(){}}}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v16_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)};
expect(HL.DATA.version===16,`version ${HL.DATA.version}`);expect(HL.DATA.captainsV16.length===6,"captain count");expect(Object.keys(HL.DATA.campaignsV16).length===6,"campaign count");
let chapters=0,tasks=0,cutscenes=0;
for(const c of HL.DATA.captainsV16){const story=HL.DATA.campaignsV16[c.campaignId];expect(!!HL.DATA.ports[c.startPort],`${c.id} start port`);expect(!!HL.DATA.ships[c.ship],`${c.id} ship`);expect(story?.captainId===c.id,`${c.id} campaign owner`);expect(story?.chapters.length===6,`${c.id} chapter count`);expect(story?.choices.length===4,`${c.id} choice count`);chapters+=story.chapters.length;for(const ch of story.chapters){tasks+=ch.tasks.length;cutscenes+=ch.cutscenes.length;expect(ch.tasks.length===3,`${ch.id} tasks`);expect(ch.cutscenes.length===3,`${ch.id} cutscenes`);for(const t of ch.tasks)expect(!!HL.DATA.ports[t.port],`${t.id} port ${t.port}`)}}
expect(chapters===36,`chapters ${chapters}`);expect(tasks===108,`tasks ${tasks}`);expect(cutscenes===108,`cutscenes ${cutscenes}`);
const pairs=new Set(HL.DATA.crossEncountersV16.map(e=>[...e.captains].sort().join("/")));expect(HL.DATA.crossEncountersV16.length===15,"encounter count");expect(pairs.size===15,"encounter pair uniqueness");
for(const c of HL.DATA.captainsV16)expect(HL.DATA.crossEncountersV16.filter(e=>e.captains.includes(c.id)).length===5,`${c.id} encounter coverage`);
for(const c of HL.DATA.captainsV16){const state=HL.applyCaptainV16(HL.Game.freshState(),c.id);expect(state.version===16&&state.captainId===c.id,`${c.id} start state`);expect(state.currentPort===c.startPort,`${c.id} start location`);expect(state.money===c.money,`${c.id} start money`);expect(state.fleet[0].type===c.ship,`${c.id} flagship`);const system=new HL.CampaignSystem();system.ensure(state);let guard=0;while(!state.flags.campaignComplete&&guard++<200){const t=system.currentTask(state);if(!t){failures.push(`${c.id} lost task`);break}const event={...t.trigger};const result=system.evaluate(state,event);if(!result){failures.push(`${c.id} failed ${t.id}`);break}}expect(state.flags.campaignComplete,`${c.id} campaign completion`);expect(state.campaign.completed.length===18,`${c.id} completed tasks ${state.campaign.completed.length}`)}
const old=HL.Game.freshState();old.version=15;old.money=777;old.captain="rian";const migrated=HL.migrateStateV16(old);expect(migrated.version===16,"migration version");expect(migrated.money===777,"migration money");expect(migrated.legacyCampaign&&migrated.campaignId==="legacy-rian-v15","legacy Rian preservation");
const engine=Object.create(HL.Engine.prototype);engine.saveSlot=(i,s)=>localStorage.setItem(engine.slotKey(i),JSON.stringify({...s,version:16}));localStorage.setItem(engine.v15SlotKey(1),JSON.stringify(old));engine.migrateOld(1);expect(JSON.parse(localStorage.getItem(engine.v15SlotKey(1))).version===15,"V15 original save changed");expect(engine.loadSlot(1)?.version===16,"V15 save not copied to V16");
let scenarioHtml="";const uiGame=Object.create(HL.Game.prototype);uiGame.mode="file";uiGame.e={selectedSlot:1,selectedCaptain:"kemal",button:(label,action,cls="")=>`<button class="${cls}" data-action="${action}">${label}</button>`,window:html=>{scenarioHtml=html}};uiGame.showScenarios(1,"ines");expect((scenarioHtml.match(/captain-preview:/g)||[]).length===6,"scenario card count");expect(!scenarioHtml.includes("disabled"),"captain remains locked");expect(scenarioHtml.includes("captain-start:ines"),"selected captain start action");
console.log(JSON.stringify({version:HL.DATA.version,captains:HL.DATA.captainsV16.length,chapters,tasks,cutscenes,encounters:pairs.size,failures},null,2));if(failures.length)process.exitCode=1;
