const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};global.Audio=class{play(){return Promise.resolve()}pause(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.indexedDB={open(){return{}}};
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
const ctx={imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},ellipse(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},scale(){},createLinearGradient(){return{addColorStop(){}}},createRadialGradient(){return{addColorStop(){}}},measureText(v){return{width:String(v).length*8}},fillText(){}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return ctx}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v17_data.js","v17_systems.js","v17_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)};
expect(HL.DATA.version===16||HL.DATA.version===17,"data boot");
expect(HL.DATA.captainsV16.map(c=>c.name).join("|")==="카이르 사판|세리아 알렌|로안 벨라르|테오란 코르비|에린 펜로|메이라 벨든","captain display names");
expect(typeof HL.Art.prototype.v16Prologue==="function"&&typeof HL.Art.prototype.v16Cutscene==="function","V17 campaign art");
expect(!HL.Art.prototype.v16Canvas,"V16 half-resolution surface leaked");
let floorCount=0;
function reachable(floor){const blocked=(x,y)=>floor.collision.solids.some(r=>x+.5>=r[0]&&x+.5<=r[0]+r[2]&&y+.5>=r[1]&&y+.5<=r[1]+r[3]),start=[Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])],seen=new Set([start.join(",")]),queue=[start];while(queue.length){const [x,y]=queue.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=`${nx},${ny}`;if(nx<0||ny<0||nx>=floor.width||ny>=floor.height||seen.has(k)||blocked(nx,ny))continue;seen.add(k);queue.push([nx,ny])}}const near=rect=>{for(const k of seen){const [x,y]=k.split(",").map(Number);if(x+1>=rect[0]-.5&&x<=rect[0]+rect[2]+.5&&y+1>=rect[1]-.5&&y<=rect[1]+rect[3]+.5)return true}return false};return floor.hotspots.every(h=>near(h.rect))&&floor.stairs.every(s=>near(s.rect))&&near(floor.exit.rect)}
for(const portId of HL.DATA.portOrder)for(const building of Object.values(HL.DATA.buildingScenes[portId]))for(const floor of Object.values(building.floors)){floorCount++;expect(floor.visual.version===17,`${floor.id} visual`);expect(!floor.collision.solids.some(r=>floor.spawn[0]>=r[0]&&floor.spawn[0]<=r[0]+r[2]&&floor.spawn[1]>=r[1]&&floor.spawn[1]<=r[1]+r[3]),`${floor.id} spawn blocked`);expect(floor.hotspots.length>=3,`${floor.id} hotspots`);expect(reachable(floor),`${floor.id} unreachable target`)}
expect(floorCount===1800,`floor count ${floorCount}`);
const old=HL.applyCaptainV16(HL.Game.freshState(),"ines");old.version=16;old.money=777;const migrated=HL.migrateStateV17(old);expect(migrated.version===17&&migrated.money===777,"V16 migration");expect(migrated.captainId==="ines"&&migrated.captainName==="세리아 알렌","captain identity migration");
const engine=Object.create(HL.Engine.prototype);engine.saveSlot=(i,s)=>localStorage.setItem(engine.slotKey(i),JSON.stringify({...s,version:17}));localStorage.setItem(engine.v16SlotKey(1),JSON.stringify(old));engine.migrateOld(1);expect(JSON.parse(localStorage.getItem(engine.v16SlotKey(1))).version===16,"V16 original save changed");expect(engine.loadSlot(1)?.version===17,"V16 save not copied");
let html="";const game=Object.create(HL.Game.prototype);game.e={selectedSlot:1,selectedCaptain:"kemal",button:(l,a,c="")=>`<button class="${c}" data-action="${a}">${l}</button>`,window:v=>html=v};game.showScenarios(1,"anne");expect((html.match(/captain-preview:/g)||[]).length===6,"captain card count");expect(html.includes("v17-portrait")&&html.includes("captain_portraits_v17.png"),"portrait panel");expect(html.includes("에린 펜로")&&html.includes("captain-start:anne"),"selected captain");
console.log(JSON.stringify({version:17,floors:floorCount,captains:HL.DATA.captainsV16.length,failures},null,2));if(failures.length)process.exitCode=1;
