const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};global.Audio=class{play(){return Promise.resolve()}pause(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.indexedDB={open(){return{}}};
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
const ctx={imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},arc(){},ellipse(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},scale(){},createLinearGradient(){return{addColorStop(){}}},createRadialGradient(){return{addColorStop(){}}},measureText(v){return{width:String(v).length*8}},fillText(){}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return ctx}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v17_data.js","v17_systems.js","v17_art.js","v18_data.js","v18_systems.js","v18_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)};
function reach(floor){const blocked=(x,y)=>floor.collision.solids.some(r=>x+.5>=r[0]&&x+.5<=r[0]+r[2]&&y+.5>=r[1]&&y+.5<=r[1]+r[3]),start=[Math.floor(floor.spawn[0]),Math.floor(floor.spawn[1])],seen=new Set([start.join(",")]),q=[start];while(q.length){const [x,y]=q.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,k=`${a},${b}`;if(a<0||b<0||a>=floor.width||b>=floor.height||seen.has(k)||blocked(a,b))continue;seen.add(k);q.push([a,b])}}const near=r=>[...seen].some(k=>{const [x,y]=k.split(",").map(Number);return x+1>=r[0]-.5&&x<=r[0]+r[2]+.5&&y+1>=r[1]-.5&&y<=r[1]+r[3]+.5});return floor.hotspots.every(h=>near(h.rect))&&floor.stairs.every(s=>near(s.rect))&&near(floor.exit.rect)}
expect(HL.DATA.version===18,`version ${HL.DATA.version}`);expect(HL.DATA.tileMetaV18.tileSize===16&&HL.DATA.tileMetaV18.pixelScale===2,"pixel profile");let floors=0;
for(const port of HL.DATA.portOrder)for(const b of Object.values(HL.DATA.buildingScenes[port]))for(const floor of Object.values(b.floors)){floors++;expect(floor.visual.version===18,`${floor.id} visual`);expect(floor.width===30&&floor.height===16,`${floor.id} compact size`);expect(floor.hotspots.length>=5&&floor.hotspots.length<=8,`${floor.id} interactions`);expect(reach(floor),`${floor.id} unreachable`)}
expect(floors===1800,`floor count ${floors}`);
for(const cap of HL.DATA.captainsV16){const rule=HL.DATA.careerProgressionV18[cap.id],state=HL.migrateStateV18(HL.applyCaptainV16(HL.Game.freshState(),cap.id)),system=new HL.CampaignSystem();system.ensure(state);let guard=0;while(!state.flags.campaignComplete&&guard++<100){if(state.careerProgress.waiting){const wait=state.careerProgress.waiting;state.fame[rule.career]=wait.required;const next=HL.DATA.campaignsV16[state.campaignId].chapters.find(ch=>ch.id===wait.nextChapter);state.campaign.chapterId=next.id;state.campaign.taskIndex=0;state.careerProgress.waiting=null;system.syncQuest(state);continue}const t=system.currentTask(state);if(!t){failures.push(`${cap.id} lost task`);break}const result=system.evaluateV18(state,{...t.trigger});if(!result){failures.push(`${cap.id} failed ${t.id}`);break}}expect(state.flags.campaignComplete,`${cap.id} completion`);expect(state.campaign.completed.length===18,`${cap.id} task count`)}
const old=HL.applyCaptainV16(HL.Game.freshState(),"anne");old.version=17;old.money=771;const migrated=HL.migrateStateV18(old);expect(migrated.version===18&&migrated.money===771,"V17 migration");expect(migrated.captainId==="anne","captain preserved");
console.log(JSON.stringify({version:HL.DATA.version,floors,captains:HL.DATA.captainsV16.length,failures},null,2));if(failures.length)process.exitCode=1;
