const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};global.Audio=class{play(){return Promise.resolve()}pause(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.indexedDB={open(){return{}}};
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
const ctx={imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},arc(){},ellipse(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},scale(){},createLinearGradient(){return{addColorStop(){}}},createRadialGradient(){return{addColorStop(){}}},measureText(v){return{width:String(v).length*8}},fillText(){}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return ctx}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v17_data.js","v17_systems.js","v17_art.js","v18_data.js","v18_systems.js","v18_art.js","v19_data.js","v19_systems.js","v19_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)};
function reachable(scene,start,targets){const blocked=(x,y)=>scene.collision.solids.some(r=>x+.5>=r[0]&&x+.5<=r[0]+r[2]&&y+.5>=r[1]&&y+.5<=r[1]+r[3]),s=[Math.floor(start[0]),Math.floor(start[1])],seen=new Set([s.join(",")]),q=[s];while(q.length){const [x,y]=q.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,k=`${a},${b}`;if(a<0||b<0||a>=scene.width||b>=scene.height||seen.has(k)||blocked(a,b))continue;seen.add(k);q.push([a,b])}}return targets.every(target=>{const rect=target.length===2?[target[0]-.1,target[1]-.1,.2,.2]:target;return[...seen].some(k=>{const [x,y]=k.split(",").map(Number),px=x+.5,py=y+.5,cx=Math.max(rect[0],Math.min(px,rect[0]+rect[2])),cy=Math.max(rect[1],Math.min(py,rect[1]+rect[3]));return Math.hypot(px-cx,py-cy)<2.2})})}
expect(HL.DATA.version===19,`version ${HL.DATA.version}`);expect(HL.DATA.portOrder.length===120,"120 ports");
const maps=Object.values(HL.DATA.townDefinitionsV19),signatures=new Set(maps.map(m=>m.signature));expect(signatures.size===120,`unique signatures ${signatures.size}`);expect(new Set(maps.map(m=>m.size)).size===3,"three town sizes");
for(const map of maps){expect(map.visual.version===19,`${map.id} visual`);expect(map.buildings.length>=7,`${map.id} facilities`);expect(!map.collision.solids.some(r=>map.spawn[0]>=r[0]&&map.spawn[0]<=r[0]+r[2]&&map.spawn[1]>=r[1]&&map.spawn[1]<=r[1]+r[3]),`${map.id} blocked spawn`);for(const npc of map.npcs)expect(!map.collision.solids.some(r=>npc.x>=r[0]&&npc.x<=r[0]+r[2]&&npc.y>=r[1]&&npc.y<=r[1]+r[3]),`${map.id} blocked npc`);expect(reachable(map,map.spawn,map.buildings.map(b=>b.door)),`${map.id} blocked building`);const harbor=map.buildings.find(b=>b.id==="harbor"),nearest=Math.min(...map.buildings.map(b=>Math.hypot(b.door[0]-map.spawn[0],b.door[1]-map.spawn[1])));expect(Math.hypot(harbor.door[0]-map.spawn[0],harbor.door[1]-map.spawn[1])<=nearest+.01,`${map.id} harbor not nearest dock`);for(let i=0;i<map.buildings.length;i++)for(let j=i+1;j<map.buildings.length;j++){const a=map.buildings[i].rect,b=map.buildings[j].rect;expect(!(a[0]<b[0]+b[2]&&a[0]+a[2]>b[0]&&a[1]<b[1]+b[3]&&a[1]+a[3]>b[1]),`${map.id} building overlap`)}}
let floors=0;for(const port of HL.DATA.portOrder)for(const building of Object.values(HL.DATA.buildingScenes[port]))for(const floor of Object.values(building.floors)){floors++;expect(floor.visual.version===19,`${floor.id} visual`);expect(reachable(floor,floor.spawn,[...floor.hotspots.map(h=>h.rect),...floor.stairs.map(s=>s.rect)]),`${floor.id} blocked target`)}expect(floors===1800,`floor count ${floors}`);
for(const cap of HL.DATA.captainsV16){
  expect(!!HL.DATA.captainVisualDefinitionsV19[cap.id],`${cap.id} visual`);
  const state=HL.migrateStateV19(HL.applyCaptainV16(HL.Game.freshState(),cap.id)),opening=HL.DATA.playableOpeningsV19[cap.id],floor=HL.DATA.buildingScenes[cap.startPort][opening.facility].floors["1f"];
  expect(floor.hotspots.some(h=>h.action===`facility:${opening.facility}`||["bank-menu","property-menu","home-menu"].includes(h.action)),`${cap.id} facility service preserved`);
  const fake={s:state,mode:"v16-prologue",e:{close(){},playMusic(){},toast(){},dialogue(){return true}},playerVelocity:{},save(){},resetFollowersV19:HL.Game.prototype.resetFollowersV19};
  HL.Game.prototype.beginPlayableOpeningV19.call(fake,cap.id);expect(fake.mode==="interior",`${cap.id} immediate control`);expect(fake.s.interior.buildingId===opening.facility,`${cap.id} start facility`);expect(fake.s.openingV19.step===0&&!fake.s.openingV19.completed,`${cap.id} opening state`);
  for(const step of ["work","witness","confirm"])HL.Game.prototype.handleOpeningV19.call(fake,step);
  expect(fake.s.openingV19.completed&&fake.s.quest.objective===opening.objective,`${cap.id} opening completion`)
}
expect(HL.DATA.actorMovementProfileV19.speed===4.5,"shared movement speed");
const old=HL.applyCaptainV16(HL.Game.freshState(),"ines");old.version=18;old.money=4321;const migrated=HL.migrateStateV19(old);expect(migrated.version===19&&migrated.money===4321&&migrated.captainId==="ines","V18 migration");
localStorage.data.clear();localStorage.setItem("horizon-ledger-v18-slot-2",JSON.stringify(old));const engineStub={v18SlotKey:HL.Engine.prototype.v18SlotKey,slotKey:HL.Engine.prototype.slotKey,loadSlot(i){try{const s=JSON.parse(localStorage.getItem(this.slotKey(i)));return s?.version===19?s:null}catch{return null}},saveSlot(i,s){localStorage.setItem(this.slotKey(i),JSON.stringify(s))}};HL.Engine.prototype.migrateOld.call(engineStub,2);const copied=JSON.parse(localStorage.getItem("horizon-ledger-v19-slot-2"));expect(copied?.version===19&&copied.money===4321,"V18 slot copied to V19");expect(!!localStorage.getItem("horizon-ledger-v18-slot-2"),"V18 source slot preserved");
console.log(JSON.stringify({version:HL.DATA.version,ports:maps.length,uniqueTowns:signatures.size,floors,captains:HL.DATA.captainsV16.length,failures},null,2));if(failures.length)process.exitCode=1;
