const fs=require("fs"),vm=require("vm"),path=require("path");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{constructor(){this.complete=false;this.naturalWidth=0}};global.Audio=class{play(){return Promise.resolve()}pause(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.indexedDB={open(){return{}}};
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
const ctx={imageSmoothingEnabled:false,clearRect(){},drawImage(){},fillRect(){},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},arc(){},ellipse(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},scale(){},createLinearGradient(){return{addColorStop(){}}},createRadialGradient(){return{addColorStop(){}}},measureText(v){return{width:String(v).length*8}},fillText(){}};
global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:1,height:1,getContext(){return ctx}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v17_data.js","v17_systems.js","v17_art.js","v18_data.js","v18_systems.js","v18_art.js","v19_data.js","v19_systems.js","v19_art.js","v20_data.js","v20_systems.js","v20_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)};
function reachable(scene,start,target){const blocked=(x,y)=>scene.collision.solids.some(r=>x+.5>=r[0]&&x+.5<=r[0]+r[2]&&y+.5>=r[1]&&y+.5<=r[1]+r[3]),s=[Math.floor(start[0]),Math.floor(start[1])],seen=new Set([s.join(",")]),q=[s];while(q.length){const [x,y]=q.shift();for(const[d,e]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=x+d,b=y+e,k=`${a},${b}`;if(a<0||b<0||a>=scene.width||b>=scene.height||seen.has(k)||blocked(a,b))continue;seen.add(k);q.push([a,b])}}return[...seen].some(k=>{const[x,y]=k.split(",").map(Number),px=x+.5,py=y+.5,cx=Math.max(target[0],Math.min(px,target[0]+target[2])),cy=Math.max(target[1],Math.min(py,target[1]+target[3]));return Math.hypot(px-cx,py-cy)<2.2})}
expect(HL.DATA.version===20,`version ${HL.DATA.version}`);expect(Object.keys(HL.DATA.captainSpriteManifestsV20).length===6,"six captain manifests");
for(const [id,m] of Object.entries(HL.DATA.captainSpriteManifestsV20)){expect(Object.keys(m.frames).length===8,`${id} directions`);for(const dir of m.directions)expect(m.frames[dir].length===10,`${id} ${dir} frames`);expect(fs.existsSync(path.resolve(root,m.images.town)),`${id} town image`);expect(fs.existsSync(path.resolve(root,m.images.interior)),`${id} interior image`)}
let specialCount=0,floors=0;for(const port of HL.DATA.portOrder)for(const building of Object.values(HL.DATA.buildingScenes[port]))for(const floor of Object.values(building.floors)){floors++;expect(floor.visual.version===20,`${floor.id} visual`);if(floor.visual.background){specialCount++;expect(fs.existsSync(path.resolve(root,floor.visual.background)),`${floor.id} background`);for(const hotspot of floor.hotspots)expect(reachable(floor,floor.spawn,hotspot.rect),`${floor.id} blocked ${hotspot.id}`)}}
expect(floors===1800,`floor count ${floors}`);expect(specialCount===6,`special interiors ${specialCount}`);
const specialTowns=Object.values(HL.DATA.specialTownDefinitionsV20);expect(specialTowns.length===6,`special towns ${specialTowns.length}`);expect(new Set(specialTowns.map(m=>m.visual.theme)).size===6,"unique town themes");
for(const map of specialTowns){expect(map.visual.version===20&&map.visual.special,`${map.id} v20 town`);expect(map.props.length>=18,`${map.id} prop density ${map.props.length}`);for(const building of map.buildings)expect(reachable(map,map.spawn,[building.door[0]-.5,building.door[1]-.5,1,1]),`${map.id} blocked ${building.id}`)}
const old=HL.applyCaptainV16(HL.Game.freshState(),"ines");old.version=19;old.money=7654;localStorage.setItem("horizon-ledger-v19-slot-2",JSON.stringify(old));const stub={slotKey:HL.Engine.prototype.slotKey,v19SlotKey:HL.Engine.prototype.v19SlotKey,loadSlot(i){try{const s=JSON.parse(localStorage.getItem(this.slotKey(i)));return s?.version===20?s:null}catch{return null}},saveSlot(i,s){localStorage.setItem(this.slotKey(i),JSON.stringify(s))}};HL.Engine.prototype.migrateOld.call(stub,2);const migrated=JSON.parse(localStorage.getItem("horizon-ledger-v20-slot-2"));expect(migrated?.version===20&&migrated.money===7654&&migrated.captainId==="ines","V19 to V20 migration");expect(!!localStorage.getItem("horizon-ledger-v19-slot-2"),"V19 source preserved");
console.log(JSON.stringify({version:HL.DATA.version,captains:Object.keys(HL.DATA.captainSpriteManifestsV20).length,specialInteriors:specialCount,specialTowns:specialTowns.length,floors,failures},null,2));if(failures.length)process.exitCode=1;
