const fs=require("fs"),vm=require("vm"),path=require("path"),{loadImage}=require("@napi-rs/canvas");
global.window=global;global.HL={};global.performance={now:()=>1000};global.Image=class{};global.Audio=class{play(){return Promise.resolve()}pause(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.prompt=()=>null;global.indexedDB={open(){return{}}};
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}};
const ctx=new Proxy({imageSmoothingEnabled:false,measureText:v=>({width:String(v).length*8})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});global.document={querySelector(){return null},getElementById(){return null},createElement(){return{width:960,height:540,getContext(){return ctx}}}};
const root=path.resolve(__dirname,".."),files=["data.js","world_data.js","v5_data.js","assets.js","collision.js","systems.js","v5_systems.js","sea_navigation_v6.js","engine.js","art.js","game.js","expansion.js","v5_art.js","v5_expansion.js","dos_sea_v6.js","horizon_v7.js","story_v8.js","story_v9_data.js","story_v9.js","topdown_v10_data.js","topdown_v10.js","topdown_v10_art.js","graphics_v11_data.js","graphics_v11.js","graphics_v11_art.js","v12_data.js","v12_systems.js","v12_art.js","v13_data.js","v13_systems.js","v13_art.js","v15_data.js","v15_systems.js","v15_art.js","v16_data.js","v16_systems.js","v17_data.js","v17_systems.js","v17_art.js","v18_data.js","v18_systems.js","v18_art.js","v19_data.js","v19_systems.js","v19_art.js","v20_data.js","v20_systems.js","v20_art.js","v21_generated.js","v21_data.js","v21_systems.js","v21_art.js"];
for(const file of files)vm.runInThisContext(fs.readFileSync(path.join(root,file),"utf8"),{filename:file});
const failures=[],expect=(ok,msg)=>{if(!ok)failures.push(msg)},starts=Object.keys(HL.DATA.townVisualSetsV21);
function edgeReachable(scene,target){const world=new HL.CollisionWorld(.28),sx=Math.floor(scene.spawn[0]),sy=Math.floor(scene.spawn[1]),q=[[sx,sy]],seen=new Set([`${sx},${sy}`]);while(q.length){const[x,y]=q.shift(),px=x+.5,py=y+.5,cx=Math.max(target[0],Math.min(px,target[0]+target[2])),cy=Math.max(target[1],Math.min(py,target[1]+target[3]));if(Math.hypot(px-cx,py-cy)<1.5)return true;for(const[d,e]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=x+d,b=y+e,k=`${a},${b}`;if(a<0||b<0||a>=scene.width||b>=scene.height||seen.has(k)||world.blocked(scene.collision,a+.5,b+.5,.28))continue;seen.add(k);q.push([a,b])}}return false}
async function main(){
  expect(HL.DATA.version===21,`version ${HL.DATA.version}`);expect(starts.length===6,`start towns ${starts.length}`);
  const hashes=new Set();let floors=0,assets=0;
  for(const portId of starts){const map=HL.DATA.townVisualSetsV21[portId];expect(map.width===64&&map.height===36,`${portId} size`);for(const b of map.buildings)expect(edgeReachable(map,[b.door[0]-.5,b.door[1]-.5,1,1]),`${portId} blocked ${b.id}`);for(const src of[map.visual.background,map.visual.foreground,map.visual.collisionImage]){expect(fs.existsSync(path.resolve(root,src)),`${portId} asset ${src}`);assets++}
    let local=0;for(const building of Object.values(HL.DATA.floorVisualSetsV21[portId]))for(const scene of Object.values(building)){floors++;local++;hashes.add(scene.visual.structuralHash);for(const src of[scene.visual.background,scene.visual.foreground,scene.visual.collisionImage]){expect(fs.existsSync(path.resolve(root,src)),`${scene.id} asset`);assets++}if(scene.floorId==="1f")expect(edgeReachable(scene,scene.exit.rect),`${scene.id} exit`);for(const stair of scene.stairs)expect(edgeReachable(scene,stair.rect),`${scene.id} stair ${stair.id}`);for(const hot of scene.hotspots)expect(edgeReachable(scene,hot.rect),`${scene.id} hotspot ${hot.id}`)}expect(local===20,`${portId} floors ${local}`)}
  expect(floors===120,`floor total ${floors}`);expect(hashes.size===120,`unique hashes ${hashes.size}`);expect(assets===378,`assets ${assets}`);
  const old=HL.applyCaptainV16(HL.Game.freshState(),"ines");old.version=20;old.money=7654;old.cargo.glass=999;localStorage.setItem("horizon-ledger-v20-slot-2",JSON.stringify(old));const stub={slotKey:HL.Engine.prototype.slotKey,v20SlotKey:HL.Engine.prototype.v20SlotKey,loadSlot(i){try{const s=JSON.parse(localStorage.getItem(this.slotKey(i)));return s?.version===21?s:null}catch{return null}},saveSlot(i,s){localStorage.setItem(this.slotKey(i),JSON.stringify(s))}};HL.Engine.prototype.migrateOld.call(stub,2);const migrated=JSON.parse(localStorage.getItem("horizon-ledger-v21-slot-2"));expect(migrated?.version===21&&migrated.money===7654,"V20 migration");expect(!!localStorage.getItem("horizon-ledger-v20-slot-2"),"V20 preserved");expect((migrated.portWarehouses[migrated.currentPort].glass||0)>0,"cargo overflow warehouse");
  const state=HL.migrateStateV21(HL.applyCaptainV16(HL.Game.freshState(),"marieke"));state.money=100000;state.fleet[0].food=0;state.fleet[0].water=0;state.fleet[0].tradeCargo={};const market=new HL.ClassicMarketStateV21(state),before=market.quote(state.currentPort,Object.keys(HL.DATA.ports[state.currentPort].market)[0],"buy"),good=Object.keys(HL.DATA.ports[state.currentPort].market)[0];market.commit(state.currentPort,good,"buy",5);const after=market.quote(state.currentPort,good,"buy");expect(after>before,"repeat buying raises price");state.day+=10;market.ensure();expect(market.quote(state.currentPort,good,"buy")<after,"daily recovery");expect(market.hasBookkeeper(),"merchant bookkeeping");
  const sea=state;sea.sea={heading:2,wind:2};sea.crew=sea.crew||{roles:{}};const sim=new HL.SeaSimulation();sim.ensure(sea);const fast=sim.shipSpeed(sea,sea.fleet[0],0);sea.sea.wind=6;const slow=sim.shipSpeed(sea,sea.fleet[0],0);expect(fast>slow,"tailwind relationship");sea.fleet.push(copyShip(sea.fleet[0],"cog"));sim.ensure(sea);expect(sim.fleetSpeed(sea)===Math.min(sim.shipSpeed(sea,sea.fleet[0],0),sim.shipSpeed(sea,sea.fleet[1],1)),"slowest fleet rule");
  const townImage=await loadImage(path.resolve(root,HL.DATA.townVisualSetsV21.constantinople.visual.background));expect(townImage.width===1920&&townImage.height===1080,"town native size");const floorImage=await loadImage(path.resolve(root,HL.DATA.floorVisualSetsV21.seville.guild["2f"].visual.background));expect(floorImage.width===960&&floorImage.height===540,"floor native size");
  console.log(JSON.stringify({version:HL.DATA.version,startTowns:starts.length,floors,uniqueFloorLayouts:hashes.size,assets,failures},null,2));if(failures.length)process.exitCode=1
}
function copyShip(ship,type){const s=JSON.parse(JSON.stringify(ship));s.id="slow";s.type=type;s.name="느린 배";return s}
main().catch(e=>{console.error(e);process.exitCode=1});
