window.HL=window.HL||{};
(function(){
  const proto=HL.Game.prototype;
  const originalFresh=HL.Game.freshState;
  const originalRender=proto.render;
  const originalUpdate=proto.update;
  const originalDispatch=proto.dispatchAction;
  const originalFinishCutscene=proto.finishCutscene;
  const originalAccept=proto.action;
  const originalMansionStory=proto.mansionStory;

  HL.Game.freshState=function(){
    const state=originalFresh.call(this),cargo={};
    for(const good of HL.DATA.goods)cargo[good.id]=state.cargo[good.id]||0;
    state.version=4;state.currentPort="bella";state.lastPort="bella";state.worldPhase=1;state.cargo=cargo;state.rngSeed=15260517;state.voyageDays=0;
    state.sea={...state.sea,lon:-10.2,lat:38.72,x:-10.2,y:38.72,zoom:1,wind:2,current:2,depth:120,weather:"맑음",flooding:0};
    state.crew={health:100,fatigue:0,morale:82,disease:null};state.bank={balance:0,loan:0,dueDay:0};state.properties={};state.storage={};state.discoveries=[];
    state.nationRelations=Object.fromEntries(Object.keys(HL.DATA.nations).map(id=>[id,id==="portugal"?35:0]));state.encounters={piratePity:false,caribbeanPirate:false,tavernRiotDay:-99};
    state.stats={navigation:42,combat:35,knowledge:48,intuition:44,leadership:40,charm:37,luck:51};
    state.fleet=state.fleet.map(ship=>({...ship,sailCondition:100,cannonballs:24,equipment:{figurehead:"none",sail:"square",hull:"wood"}}));
    state.quest.objective="오프닝 기록을 보고 리스본 조선소에서 새벽까마귀를 인수하라.";
    return state;
  };

  proto.ensureExpansion=function(){
    if(!this.navigation)this.navigation=new HL.WorldNavigation();
    if(!this.economy)this.economy=new HL.EconomySystem();
    if(!this.encounters)this.encounters=new HL.EncounterSystem(this.navigation);
    if(!this.battleSystem)this.battleSystem=new HL.BattleSystem();
    if(!this.spriteAnimator)this.spriteAnimator=new HL.SpriteAnimator();
    if(!this.seaGrid)this.seaGrid=new HL.SeaNavigationGrid(this.navigation);
    if(!this.routeGuide)this.routeGuide=new HL.SeaRouteGuide(this.seaGrid);
    if(this.s){const fresh=HL.Game.freshState();this.s.worldPhase=this.s.worldPhase||1;this.s.rngSeed=this.s.rngSeed||fresh.rngSeed;this.s.voyageDays=this.s.voyageDays||0;this.s.crew={...fresh.crew,...this.s.crew};this.s.bank={...fresh.bank,...this.s.bank};this.s.properties=this.s.properties||{};this.s.storage=this.s.storage||{};this.s.discoveries=this.s.discoveries||[];this.s.encounters={...fresh.encounters,...this.s.encounters};this.s.stats={...fresh.stats,...this.s.stats};this.s.nationRelations={...fresh.nationRelations,...this.s.nationRelations};for(const ship of this.s.fleet){ship.sailCondition??=100;ship.cannonballs??=24;ship.equipment={...fresh.fleet[0].equipment,...ship.equipment}}if(this.s.sea.lon==null){const p=HL.DATA.ports[this.s.currentPort]||HL.DATA.ports.bella;this.s.sea.lon=p.lon;this.s.sea.lat=p.lat;this.s.sea.x=p.lon;this.s.sea.y=p.lat}}
  };

  proto.showScenarios=function(slot){
    this.e.selectedSlot=slot;this.mode="scenario";
    const stats=HL.Game.freshState().stats;
    this.e.window(`<h1>선장 능력치</h1><p>리안 팔코 · 항해 견습생 · 리스본</p><div class="captain-profile"><div class="captain-silhouette">RF</div><div class="status-grid">${Object.entries({항해:stats.navigation,전투:stats.combat,지식:stats.knowledge,직감:stats.intuition,통솔:stats.leadership,매력:stats.charm,운:stats.luck}).map(([k,v])=>`<div class="status-cell"><small>${k}</small><b>${v}</b><i><span style="width:${v}%"></span></i></div>`).join("")}</div></div><p>시작 자금 1,200 · 카라벨 새벽까마귀 · 특기: 역풍 항해 경험 +10%</p><div class="toolbar right">${this.e.button("이 선장으로 시작","captain:0","primary")}${this.e.button("파일 선택","files")}</div>`,"center wide");
  };

  proto.resume=function(i){
    this.s=this.e.loadSlot(i);if(!this.s)return this.showFiles();this.s.slot=i;this.ensureExpansion();
    this.s.flags={...HL.Game.freshState().flags,...this.s.flags};
    if(this.s.quest.stage>0||this.s.flags.metFather&&this.s.mates?.length)this.s.flags.shipGranted=true;
    this.s.fleet[0].locked=!!(!this.s.flags.shipGranted&&this.s.quest.stage===0);
    this.mode=this.s.mode==="cutscene"?"town":this.s.mode||"town";
    if(this.mode==="interior"&&!this.s.interior)this.mode="town";
    if(this.mode==="interior"&&this.s.interior){
      const scene=HL.DATA.interiorScenes[this.s.interior.id];
      if(!scene||this.collision.blocked(scene.collision,this.s.interior.x,this.s.interior.y,.28)){
        if(!scene){this.mode="town";this.s.interior=null}
        else{this.s.interior.x=scene.spawn[0];this.s.interior.y=scene.spawn[1];this.lastSafe={x:scene.spawn[0],y:scene.spawn[1]}}
      }
    }
    this.spawnTownNpcs();this.e.close();this.e.playMusic(this.mode==="sea"?"sea":"port");this.ensureSafePosition()
  };
  proto.townMap=function(){return HL.WorldData.townMapFor(this.s.currentPort)};
  proto.townBuildings=function(){const p=HL.DATA.ports[this.s.currentPort];return this.townMap().buildings.map(b=>({...b,name:b.id==="mansion"?(this.s.currentPort==="bella"?"팔코 저택":p.facilities.includes("bank")?"은행":"상인회관"):b.name}))};
  proto.ownerName=function(id){if(id==="mansion"&&this.s.currentPort!=="bella")return HL.DATA.ports[this.s.currentPort].facilities.includes("bank")?"은행가":"상인회 대표";return{market:"시장 주인",inn:"술집 주인",shipyard:"조선공",guild:this.s.currentPort==="genoa"?"서점 주인 아셀":"길드장",lodge:"여관 주인",harbor:"항만 관리인",mansion:"데미안 팔코"}[id]};

  proto.finishCutscene=function(){originalFinishCutscene.call(this);if(this.s&&!this.cutscene){this.s.quest.objective="리스본 조선소에서 새벽까마귀와 오르소 벤을 만나라.";this.save()}};
  proto.mansionStory=function(){if(this.s.currentPort!=="bella"){const p=HL.DATA.ports[this.s.currentPort];return p.facilities.includes("bank")?this.bankMenu():this.e.dialogue("상인회 대표",`${p.name}의 교역 기록은 길드에 제출해 주시오.`,[{label:"확인",action:"close"}])}if(this.s.quest.stage===0&&!this.s.flags.shipGranted)return this.e.dialogue("데미안 팔코","새벽까마귀와 오르소가 리스본 조선소에서 기다린다. 먼저 바다를 견딜 배와 선원을 갖추어라.",[{label:"조선소로 간다",action:"close",primary:true}]);return originalMansionStory.call(this)};

  proto.renderHud=function(){if(["file","scenario","cutscene","worldmap","tavernEvent"].includes(this.mode)){this.e.hud.innerHTML="";return}const ship=this.s.fleet[0],p=HL.DATA.ports[this.s.currentPort],sea=this.s.sea,where=this.mode==="sea"?`${Math.abs(sea.lat).toFixed(1)}°${sea.lat>=0?"N":"S"} ${Math.abs(sea.lon).toFixed(1)}°${sea.lon>=0?"E":"W"}`:p.name;this.e.hud.innerHTML=`<div class="hud-group"><span class="hud-gold">${this.s.year}.${this.s.month}.${this.s.day} ${String(this.s.hour).padStart(2,"0")}:00</span><span>${where}</span><span>침로 ${HL.DATA.directionNames[sea.heading]}</span><span>${this.navigation?this.navigation.speed(this.s).toFixed(1):"0.0"}kn</span><span>선체 ${ship.hull}%</span><span>돛 ${ship.sailCondition}%</span><span>선원 ${ship.crew} · 건강 ${this.s.crew.health}</span><span>식량 ${ship.food} · 물 ${ship.water}</span></div><div class="hud-objective">목표 · ${this.s.quest.objective}</div>`};

  proto.update=function(dt){this.ensureExpansion();if(this.mode==="worldmap"){if(this.e.hit("m","M","Escape","x","X"))this.closeWorldMap();return}if(this.mode==="tavernEvent")return this.updateTavernEvent(dt);if(this.s&&this.e.hit("m","M")&&!this.e.overlay.innerHTML)return this.openWorldMap();return originalUpdate.call(this,dt)};
  proto.render=function(){this.ensureExpansion();if(this.mode==="worldmap"){this.art.worldMap(this);this.help("M/Esc 세계지도 닫기 · 발견한 항구와 보물만 표시");return}if(this.mode==="tavernEvent"){this.art.tavernEvent(this);return}return originalRender.call(this)};

  proto.isLand=function(lon,lat){this.ensureExpansion();return this.navigation.isLand(lon,lat)};
  proto.findSeaSpawn=function(port){this.ensureExpansion();const approach=this.seaGrid.portApproach(port);return{x:approach.spawn[0],y:approach.spawn[1],heading:approach.heading,channel:approach.channel}};
  proto.setSail=function(){this.ensureExpansion();const ship=this.s.fleet[0];if(!this.s.flags.shipGranted)return this.e.toast("먼저 조선소에서 새벽까마귀를 인수하십시오");if(ship.crew<HL.DATA.ships[ship.type].crewMin)return this.e.toast("운항에 필요한 선원이 부족합니다");if(this.s.quest.stage===1&&(this.s.cargo.glass||0)<1)return this.e.toast("첫 교역을 위해 유리를 한 상자 이상 실으십시오");const p=HL.DATA.ports[this.s.currentPort],spawn=this.findSeaSpawn(p);this.mode="sea";this.s.lastPort=this.s.currentPort;this.s.sea.lon=spawn.x;this.s.sea.lat=spawn.y;this.s.sea.x=spawn.x;this.s.sea.y=spawn.y;this.s.sea.heading=spawn.heading;this.s.sea.harborChannel=spawn.channel;this.s.sea.anchor=false;this.s.sea.groundingCooldown=0;this.s.voyageDays=0;this.e.close();this.e.playMusic("sea");this.save();this.e.toast("침로를 직접 조정하십시오 · M 세계지도 · Enter 해상 명령")};
  proto.headingTo=function(port){const dx=(port.lon-this.s.sea.lon)*Math.cos(this.s.sea.lat*Math.PI/180),dy=port.lat-this.s.sea.lat;let best=0,score=-Infinity;for(let i=0;i<8;i++){const d=HL.DATA.directions[i],dot=d[0]*dx+(-d[1])*dy;if(dot>score){score=dot;best=i}}return best};
  proto.updateSea=function(dt){if(this.e.overlay.innerHTML||this.seaMenu)return;const input=this.inputDirection();if(input>=0){this.s.sea.heading=input;this.s.sea.anchor=false}const scale=this.s.sea.speed||1;this.seaClock+=dt*scale;this.s.sea.groundingCooldown=Math.max(0,(this.s.sea.groundingCooldown||0)-dt*scale);if(!this.s.sea.anchor){const velocity=this.navigation.speed(this.s)*.42*scale,result=this.seaGrid.move(this.s,velocity*dt);this.s.sea.depth=this.seaGrid.depth(this.s.sea.lon,this.s.sea.lat);this.s.sea.current=this.navigation.current(this.s.sea.lon,this.s.sea.lat);if(result.blocked&&this.s.sea.groundingCooldown<=0){const hard=result.impact>.12||this.s.sea.depth<7;if(hard){this.s.fleet[0].hull=Math.max(0,this.s.fleet[0].hull-2);this.s.fleet[0].sailCondition=Math.max(0,this.s.fleet[0].sailCondition-1);this.e.toast("강한 좌초 충격! 속도를 낮추고 외해로 선회하십시오")}else this.e.toast(result.slid?"연안을 따라 미끄러졌습니다":"해안이 가깝습니다. 외해로 선회하십시오");this.s.sea.groundingCooldown=2.4}}if(this.seaClock>=1.2){this.seaClock=0;this.advanceHour();this.discoverNearby()}if(this.s.fleet[0].hull<=0||this.s.fleet[0].crew<=0)return this.rescueAfterLoss("함대가 항해 불능이 되었습니다");if(this.e.hit("Enter","z","Z"," "))this.openSeaMenu()};
  proto.advanceHour=function(){this.s.hour++;if(this.s.hour<24)return;this.s.hour=0;this.s.day++;this.s.voyageDays++;const ship=this.s.fleet[0],use=this.s.sea.ration>=100?1:.5;ship.food=Math.max(0,ship.food-use);ship.water=Math.max(0,ship.water-use);this.s.crew.fatigue=Math.min(100,this.s.crew.fatigue+3);if(ship.food<=0||ship.water<=0){this.s.crew.health=Math.max(0,this.s.crew.health-9);this.s.crew.morale=Math.max(0,this.s.crew.morale-7);if(this.s.crew.health<20)ship.crew=Math.max(0,ship.crew-1)}this.s.sea.wind=this.navigation.wind(this.s.day,this.s.month,this.s.sea.lat);const events=this.encounters.daily(this.s);if(events.includes("storm")){this.s.sea.weather="폭풍";const damage=this.encounters.stormDamage(this.s);this.e.toast(`폭풍! 선체 ${damage} 피해`)}else this.s.sea.weather=(this.s.day%11===0?"안개":"맑음");if(events.includes("scurvy")){this.encounters.disease(this.s,"괴혈병");this.e.toast("선원 사이에 괴혈병이 퍼졌습니다")}else if(events.includes("disease")){this.encounters.disease(this.s,"열병");this.e.toast("선원들이 열병에 걸렸습니다")}const inCaribbean=this.s.sea.lon>-88&&this.s.sea.lon<-60&&this.s.sea.lat>9&&this.s.sea.lat<26;if(inCaribbean&&!this.s.encounters.caribbeanPirate&&!this.e.overlay.innerHTML){this.s.encounters.caribbeanPirate=true;this.e.dialogue("재스퍼 로크","검은 나침반이 자네 배를 가리키는군. 한판 겨루겠나, 아니면 럼주 한 잔과 암초 지도를 바꾸겠나?",[{label:"결투를 받아들인다",action:"caribbean-duel"},{label:"럼주를 나눈다",action:"caribbean-toast",primary:true}])}else if(events.includes("pirate")&&!this.e.overlay.innerHTML)this.startPirateEncounter();if(this.s.crew.health<=0||ship.crew<=0)this.rescueAfterLoss("선원들이 더는 항해할 수 없습니다");if(this.s.fame.adventure>=1200)this.s.worldPhase=3;else if(this.s.flags.chapterComplete)this.s.worldPhase=Math.max(2,this.s.worldPhase);this.save()};
  proto.discoverNearby=function(){const range=this.s.inventory.telescope?3.8:2.1;for(const id of HL.WorldData.activePorts(this.s.worldPhase)){const p=HL.DATA.ports[id],entrance=this.seaGrid.portApproach(p).spawn,d=Math.min(Math.hypot((this.s.sea.lon-p.lon)*Math.cos(this.s.sea.lat*Math.PI/180),this.s.sea.lat-p.lat),Math.hypot((this.s.sea.lon-entrance[0])*Math.cos(this.s.sea.lat*Math.PI/180),this.s.sea.lat-entrance[1]));if(d<range&&!this.s.knownPorts.includes(id)){this.s.knownPorts.push(id);this.s.fame.adventure+=15;this.e.toast(`${p.name}을 발견했습니다`);this.save()}}};
  proto.nearbyPort=function(){let best=null;for(const id of HL.WorldData.activePorts(this.s.worldPhase)){const p=HL.DATA.ports[id],entrance=this.seaGrid.portApproach(p).spawn,d=Math.min(Math.hypot((this.s.sea.lon-p.lon)*Math.cos(this.s.sea.lat*Math.PI/180),this.s.sea.lat-p.lat),Math.hypot((this.s.sea.lon-entrance[0])*Math.cos(this.s.sea.lat*Math.PI/180),this.s.sea.lat-entrance[1]));if(d<=2.4&&(!best||d<best.distance))best={id,distance:d}}return best?.id||null};
  proto.openWorldMap=function(){if(!this.s)return;this.modeBeforeMap=this.mode;this.mode="worldmap";this.seaMenu=false;this.e.close()};
  proto.closeWorldMap=function(){this.mode=this.modeBeforeMap||"town";this.seaMenu=false;this.e.close()};

  proto.openSeaMenu=function(){this.seaMenu=true;const port=this.nearbyPort(),warning=this.seaGrid.forecast(this.s.sea.lon,this.s.sea.lat,this.s.sea.heading);this.e.window(`<h1>해상 명령</h1><p>${this.s.sea.weather} · 수심 ${this.s.sea.depth}m · 풍 ${HL.DATA.directionNames[this.s.sea.wind]} · 조류 ${HL.DATA.directionNames[this.s.sea.current]}${warning.danger?` · <span class="risk">전방 ${warning.kind}</span>`:""}</p><div class="menu-grid">${this.e.button(this.s.sea.anchor?"돛 올리기":"정박","anchor")}${this.e.button("관찰","inspect")}${this.e.button("수색","search-sea")}${this.e.button("교전","battle-command")}${this.e.button(port?`${HL.DATA.ports[port].name} 입항`:"입항","dock",port?"primary":"")}${this.e.button("세계지도","world-map")}${this.e.button("항로 설정","auto-route")}${this.e.button(`속도 ${this.s.sea.speed}×`,"speed")}${this.e.button("라임 주스 사용","use-lime")}${this.e.button("의약품 사용","use-medicine")}${this.e.button("함대 정보","fleet-info")}${this.e.button("화물 정보","cargo-info")}${this.e.button("배급 설정","ration")}${this.e.button("닫기","sea-close")}</div>`,"sea-menu")};
  proto.renderSea=function(){this.art.worldSea(this);if(!this.e.overlay.innerHTML)this.help("방향키/WASD 침로 · M 세계지도 · Enter/Z 해상 명령")};
  proto.routeMenu=function(){const known=this.s.knownPorts.filter(id=>HL.DATA.ports[id]?.tier<=this.s.worldPhase);this.e.window(`<h1>항로 설정</h1><p>목적지 방위와 안전 경유지만 표시합니다. 배의 침로는 직접 조정해야 합니다.</p><div class="route-list">${known.map(id=>this.e.button(`${HL.DATA.ports[id].name} · ${HL.DATA.ports[id].modern}`,`route:${id}`)).join("")}${this.e.button("취소","sea-close")}</div>`,"center")};

  proto.dock=function(){const id=this.nearbyPort();if(!id)return this.e.toast("입항 가능한 항구가 가깝지 않습니다");const p=HL.DATA.ports[id],relation=this.s.nationRelations[p.nation]||0;if(relation<-20)return this.hostilePortMenu(id);return this.completeDock(id)};
  proto.completeDock=function(id){const p=HL.DATA.ports[id],map=HL.WorldData.townMapFor(id);this.s.currentPort=id;this.s.lastPort=id;this.mode="town";this.s.town={x:map.spawn[0],y:map.spawn[1],dir:0};this.s.sea.anchor=true;this.s.voyageDays=0;this.seaMenu=false;this.s.crew.fatigue=Math.max(0,this.s.crew.fatigue-15);this.e.close();this.spawnTownNpcs();this.e.playMusic("port");if(id==="lume"&&this.s.quest.stage===1){this.s.quest.stage=2;this.s.quest.objective="안트베르펜 시장에 유리를 팔고 포도주와 목재를 사라."}if(id==="genoa"&&this.s.quest.stage===4)this.s.quest.objective="제노바 길드에서 푸른 장부를 조사하라.";this.save();this.e.sfx("port_bell");this.e.toast(`${p.name} 입항 · ${HL.DATA.nations[p.nation].name}`)};
  proto.hostilePortMenu=function(id){this.pendingPort=id;const p=HL.DATA.ports[id];this.e.window(`<h1>${p.name} 봉쇄</h1><p>이 항구는 현재 함대에 적대적입니다.</p><div class="menu-grid">${this.e.button("뇌물 300","hostile-bribe")}${this.e.button("위장 입항","hostile-disguise")}${this.e.button("봉쇄 돌파","hostile-break","danger")}${this.e.button("물러난다","sea-close")}</div>`,"center")};

  proto.startBattle=function(kind="pirate"){if(this.s.hour<6||this.s.hour>=18){this.s.hour=7;this.s.day++;this.e.toast("동틀 무렵 전투가 시작됩니다")}this.battleReturn={lon:this.s.sea.lon,lat:this.s.sea.lat};this.mode="battle";this.battle={kind,player:{x:2,y:4,hp:this.s.fleet[0].hull,crew:this.s.fleet[0].crew},enemy:{x:10,y:4,hp:kind==="port"?125:88,crew:kind==="port"?28:20},turn:"player",log:kind==="port"?"항만 경비 함대가 수로를 봉쇄했다.":"해적 함대가 포문을 열었다.",round:1,portTarget:kind==="port"?this.pendingPort:null};this.e.close();this.seaMenu=false;this.e.playMusic("danger");this.openBattleMenu()};
  proto.openBattleMenu=function(){if(this.mode!=="battle")return;const ship=this.s.fleet[0];this.e.window(`<h2>함대전 · 제 ${this.battle.round}턴</h2><p>선체 ${this.battle.player.hp} · 선원 ${this.battle.player.crew} · 포탄 ${ship.cannonballs}</p><div class="menu-grid">${this.e.button("이동·선회","battle-move")}${this.e.button("포격","battle-fire")}${this.e.button("백병 돌격","battle-rush")}${this.e.button("응급 수리","battle-repair")}${this.e.button("대기","battle-wait")}${this.e.button("도주","battle-flee")}</div>`,"battle-menu");this.e.overlay.firstElementChild?.insertAdjacentHTML("beforeend",`<section class="window battle-log">${this.battle.log}</section>`)};
  proto.battleAction=function(kind){const b=this.battle,ship=this.s.fleet[0],dist=Math.abs(b.player.x-b.enemy.x)+Math.abs(b.player.y-b.enemy.y),rng=new HL.SeededRandom(this.s.rngSeed);this.s.rngSeed=rng.seed;if(kind==="move"){b.player.x+=Math.sign(b.enemy.x-b.player.x);b.log="바람을 타고 적선에 접근했다."}if(kind==="fire"){if(ship.cannonballs<=0)return this.e.toast("포탄이 없습니다");ship.cannonballs--;const damage=this.battleSystem.cannonDamage({...ship,guns:ship.guns},b.enemy,dist,rng);b.log=`현측 포격 명중 · 적 선체 -${damage}`;this.e.sfx("wood_knock")}if(kind==="rush"){if(dist<=1){const result=this.battleSystem.boardingDamage(b.player,b.enemy,rng);b.log=`백병전 · ${result.winner==="attacker"?"적 선원 제압":"아군 후퇴"} · 손실 ${result.loss}`;if(b.enemy.crew<=4)return this.startDuel()}else{b.player.x+=Math.sign(b.enemy.x-b.player.x);b.log="갈고리를 준비하며 접근했다."}}if(kind==="repair"){if(ship.lumber<=0)return this.e.toast("수리용 목재가 없습니다");ship.lumber--;b.player.hp=Math.min(HL.DATA.ships[ship.type].hull,b.player.hp+16);b.log="목재 1을 사용해 선체를 응급 수리했다."}if(kind==="flee"){if(rng.next()+this.s.stats.navigation/100>.85){this.mode="sea";this.e.close();this.e.playMusic("sea");return this.e.toast("전장에서 이탈했습니다")}b.log="퇴로가 막혔다."}if(kind==="wait")b.log="사정거리를 유지하며 다음 기회를 기다렸다.";if(b.enemy.hp<=0)return this.winBattle("sunk");this.enemyTurn()};
  proto.enemyTurn=function(){const b=this.battle,rng=new HL.SeededRandom(this.s.rngSeed),dist=Math.abs(b.player.x-b.enemy.x);this.s.rngSeed=rng.seed;if(dist<=1&&rng.next()>.55){const result=this.battleSystem.boardingDamage(b.enemy,b.player,rng);b.log+=`\n적의 백병 돌격 · 아군 선원 손실 ${result.loss}`}else if(dist<=5){const damage=this.battleSystem.cannonDamage({guns:4},b.player,dist,rng);b.log+=`\n적 포격 · 선체 -${damage}`}else{b.enemy.x-=Math.sign(b.enemy.x-b.player.x);b.log+="\n적선이 접근했다."}b.round++;if(b.player.hp<=0||b.player.crew<=0)return this.loseBattle();this.openBattleMenu()};
  proto.startDuel=function(){this.mode="duel";this.duel={playerHp:100,enemyHp:this.battle?.kind==="port"?110:86,enemyMax:this.battle?.kind==="port"?110:86,stamina:100,enemyStamina:90,log:"양 선장이 넓은 갑판 한가운데서 맞섰다."};this.e.close();this.openDuelMenu()};
  proto.openDuelMenu=function(){const d=this.duel;this.e.window(`<h2>선장 결투</h2><div class="duel-fighters"><div><strong>리안 팔코</strong><div class="hp"><i style="width:${d.playerHp}%"></i></div><small>기력 ${d.stamina}</small></div><div><strong>${this.battle?.kind==="port"?"항만 경비대장":"해적 선장"}</strong><div class="hp"><i style="width:${d.enemyHp/d.enemyMax*100}%"></i></div><small>기력 ${d.enemyStamina}</small></div></div><p>${d.log}</p><div class="toolbar" style="justify-content:center">${this.e.button("베기","duel:slash")}${this.e.button("찌르기","duel:thrust")}${this.e.button("막기","duel:guard")}${this.e.button("회피","duel:dodge")}${this.e.button("반격","duel:counter")}</div>`,"duel")};
  proto.duelAction=function(move){const d=this.duel,moves=["slash","thrust","guard","dodge","counter"],rng=new HL.SeededRandom(this.s.rngSeed),enemy=moves[Math.floor(rng.next()*moves.length)],beats={slash:"counter",counter:"thrust",thrust:"guard",guard:"dodge",dodge:"slash"};this.s.rngSeed=rng.seed;let playerDamage=7,enemyDamage=7;if(beats[move]===enemy){enemyDamage=23;playerDamage=2}else if(beats[enemy]===move){playerDamage=19;enemyDamage=1}else if(move==="guard"||move==="dodge"){playerDamage=3;enemyDamage=4}d.enemyHp-=enemyDamage;d.playerHp-=playerDamage;d.stamina=Math.max(0,d.stamina-(move==="guard"?3:move==="dodge"?7:11));d.enemyStamina=Math.max(0,d.enemyStamina-9);const names={slash:"베기",thrust:"찌르기",guard:"막기",dodge:"회피",counter:"반격"};d.log=`리안 ${names[move]} · 적 ${names[enemy]}`;if(d.enemyHp<=0)return this.winBattle("captured");if(d.playerHp<=0)return this.loseBattle();this.openDuelMenu()};
  proto.winBattle=function(result="captured"){const target=this.battle?.portTarget,returnPos=this.battleReturn;this.s.flags.battleWon=true;this.s.fame.battle+=result==="captured"?120:80;this.s.fame.adventure+=30;this.s.fleet[0].hull=Math.max(20,Math.round(this.battle?.player.hp||55));this.s.fleet[0].crew=Math.max(1,this.battle?.player.crew||this.s.fleet[0].crew);if(result==="captured"){this.s.money+=260;this.s.cargo.spice=(this.s.cargo.spice||0)+1}this.battle=null;this.duel=null;if(target){this.s.nationRelations[HL.DATA.ports[target].nation]-=10;return this.completeDock(target)}this.mode="sea";if(returnPos){this.s.sea.lon=returnPos.lon;this.s.sea.lat=returnPos.lat;this.s.sea.x=returnPos.lon;this.s.sea.y=returnPos.lat}this.e.close();this.e.playMusic("sea");this.save();this.e.toast(result==="captured"?"적선을 나포해 화물과 260금을 얻었습니다":"적선을 침몰시켰습니다")};
  proto.loseBattle=function(){this.battle=null;this.duel=null;this.rescueAfterLoss("전투에서 패배했습니다.")};

  proto.marketMenu=function(){const p=HL.DATA.ports[this.s.currentPort],ids=[...new Set([...p.specialties,"grain","salt","timber","wine","medicine","lime_juice","gunpowder","weapons"])],goods=ids.map(id=>HL.DATA.goods.find(g=>g.id===id)).filter(Boolean);this.e.window(`<div class="shop-head"><h1>${p.name} 시장</h1><span>금화 ${this.s.money}</span></div><p>특산품 · ${p.specialties.map(id=>HL.DATA.goods.find(g=>g.id===id)?.name).join(" · ")}</p><div class="rows">${goods.map(g=>{const q=this.s.cargo[g.id]||0,buy=this.economy.price(p,g.id,this.s.day,true),sell=this.economy.price(p,g.id,this.s.day,false);return`<div class="row"><span>${g.name}<small>구입 ${buy} · 판매 ${sell} · 보유 ${q}</small></span>${this.e.button("구입",`buy:${g.id}`)}${this.e.button("판매",`sell:${g.id}`)}</div>`}).join("")}</div><div class="toolbar">${this.e.button("1,000 투자","market-invest")}${this.e.button("끝내기","close")}</div>`,"shop facility-panel")};
  proto.trade=function(id,buy){const p=HL.DATA.ports[this.s.currentPort],price=this.economy.price(p,id,this.s.day,buy),ship=this.s.fleet[0],used=Object.values(this.s.cargo).reduce((a,b)=>a+b,0);if(buy){if(this.s.money<price)return this.e.toast("금화가 부족합니다");if(used>=HL.DATA.ships[ship.type].cargo)return this.e.toast("화물칸이 가득 찼습니다");this.s.money-=price;this.s.cargo[id]=(this.s.cargo[id]||0)+1;if(this.s.currentPort==="lume"&&id==="wine")this.s.flags.boughtWine=true;if(this.s.currentPort==="lume"&&id==="timber")this.s.flags.boughtTimber=true}else{if(!(this.s.cargo[id]>0))return this.e.toast("판매할 화물이 없습니다");this.s.money+=price;this.s.cargo[id]--;if(this.s.currentPort==="lume"&&id==="glass")this.s.flags.soldGlass=true}if(this.s.quest.stage===2&&this.s.flags.soldGlass&&this.s.flags.boughtWine&&this.s.flags.boughtTimber){this.s.quest.stage=3;this.s.quest.objective="안트베르펜 술집에서 소문을 듣고 길드 의뢰를 확인하라."}this.s.fame.trade+=1;this.e.sfx("coin_trade");this.save();this.marketMenu()};
  proto.innMenu=function(){this.e.window(`<h1>술집과 여관</h1><p>선원 모집, 소문, 포커와 숙박을 이용할 수 있습니다.</p><div class="menu-grid">${this.e.button("선원 5명 모집 · 50","recruit")}${this.e.button("소문 듣기 · 10","gossip")}${this.e.button("포커 · 20","poker:20")}${this.e.button("포커 · 100","poker:100")}${this.e.button("숙박 · 20","rest")}${this.e.button("부동산","property-menu")}${this.e.button("끝내기","close")}</div>`,"facility-panel")};
  proto.lodgeMenu=function(){const sh=this.s.fleet[0];this.e.window(`<h1>상태와 숙박</h1><div class="status-grid"><div class="status-cell"><small>선원 건강</small>${this.s.crew.health} · ${this.s.crew.disease||"정상"}</div><div class="status-cell"><small>피로 / 사기</small>${this.s.crew.fatigue} / ${this.s.crew.morale}</div><div class="status-cell"><small>함선</small>${sh.name} · 선체 ${sh.hull} · 돛 ${sh.sailCondition}</div><div class="status-cell"><small>발견</small>${this.s.knownPorts.length}개 항구 · ${this.s.discoveries.length}개 보물</div></div><div class="toolbar">${this.e.button("숙박 · 20","rest")}${this.e.button("부동산","property-menu")}${this.e.button("은행","bank-menu")}${this.e.button("끝내기","close")}</div>`,"facility-panel")};
  proto.shipyardMenu=function(){const ship=this.s.fleet[0];if(this.s.currentPort==="bella"&&!this.s.flags.shipGranted)return this.e.dialogue("오르소 벤","새벽까마귀를 인수하시죠. 선원과 유리를 준비하면 안트베르펜까지 첫 항로를 가르쳐 드리겠습니다.",[{label:"배와 항해사를 인수한다",action:"accept-ship",primary:true}]);this.e.window(`<h1>조선소</h1><p>${ship.name} · 선체 ${ship.hull} · 돛 ${ship.sailCondition} · ${this.economy.effectSummary(ship)}</p><div class="menu-grid">${this.e.button("전체 수리","repair")}${this.e.button("대포 증설 · 200","remodel-guns")}${this.e.button("용 선수상 · 900","equip:figurehead:dragon")}${this.e.button("돌고래 선수상 · 650","equip:figurehead:dolphin")}${this.e.button("삼각돛 · 750","equip:sail:lateen")}${this.e.button("복합 상돛 · 1,300","equip:sail:topsail")}${this.e.button("구리 외장 · 1,600","equip:hull:copper")}${this.e.button("삼나무 선체 · 1,200","equip:hull:cedar")}${this.e.button("선명 변경","rename")}${this.e.button("끝내기","close")}</div>`,"facility-panel")};
  proto.bankMenu=function(){this.e.window(`<h1>은행</h1><div class="status-grid"><div class="status-cell"><small>휴대금</small>${this.s.money}</div><div class="status-cell"><small>예금</small>${this.s.bank.balance}</div><div class="status-cell"><small>대출</small>${this.s.bank.loan}</div></div><div class="menu-grid">${this.e.button("100 예금","bank-deposit:100")}${this.e.button("전액 예금","bank-deposit:all")}${this.e.button("100 인출","bank-withdraw:100")}${this.e.button("전액 인출","bank-withdraw:all")}${this.e.button("500 대출","bank-loan")}${this.e.button("대출 상환","bank-repay")}${this.e.button("끝내기","close")}</div>`,"facility-panel")};
  proto.propertyMenu=function(){const owned=this.s.properties[this.s.currentPort],p=HL.DATA.ports[this.s.currentPort],price=1800+Math.round(p.economy*2);this.e.window(`<h1>${p.name} 부동산</h1><p>${owned?"이 항구에 선장의 집이 있습니다.":`작은 항구 주택 가격 ${price}`}</p><div class="menu-grid">${owned?this.e.button("집에서 휴식","home-rest","primary"):this.e.button(`주택 구입 · ${price}`,"buy-property","primary")}${owned?this.e.button("귀환항 지정","home-port"):""}${owned?this.e.button("창고 확인","home-storage"):""}${this.e.button("끝내기","close")}</div>`,"facility-panel")};
  proto.openPause=function(){this.e.window(`<h1>항해 일지</h1><p><strong>${this.s.quest.title}</strong><br>${this.s.quest.objective}</p><p>추천 보급 · 식량 ${Math.max(12,this.s.fleet[0].crew)} / 물 ${Math.max(12,this.s.fleet[0].crew)} · 선원 건강 ${this.s.crew.health}</p><div class="menu-grid">${this.e.button("세계지도 · M","world-map")}${this.e.button("저장","manual-save")}${this.e.button("상태","status")}${this.e.button("발견 기록","discovery-log")}${this.e.button("오프닝 다시 보기","cutscene-replay")}${this.e.button("소리 설정","settings")}${this.e.button("파일 선택으로","files")}${this.e.button("닫기","close")}</div>`,"center")};

  proto.searchSea=function(){const rng=new HL.SeededRandom(this.s.rngSeed),roll=rng.next();this.s.rngSeed=rng.seed;if(roll<.28){const id=`wreck-${Math.round(this.s.sea.lon)}-${Math.round(this.s.sea.lat)}`;if(!this.s.discoveries.some(d=>d.id===id)){const discovery={id,name:roll<.1?"침몰선의 은화 상자":"표류한 항해 장부",lon:this.s.sea.lon,lat:this.s.sea.lat,value:180+Math.round(rng.next()*420)};this.s.discoveries.push(discovery);this.s.money+=discovery.value;this.s.fame.adventure+=35;this.e.toast(`${discovery.name} 발견 · ${discovery.value}금`)}else this.e.toast("이미 수색한 해역입니다")}else if(roll<.48){this.s.fleet[0].water+=3;this.e.toast("빗물을 모아 물 3을 확보했습니다")}else this.e.toast("수평선과 해저에서 특별한 흔적을 찾지 못했습니다");this.save();this.openSeaMenu()};
  proto.startPirateEncounter=function(){this.e.dialogue("해적 감시수","검은 돛 함대가 접근합니다. 포격전을 벌이거나 화물을 넘길 수 있습니다.",[{label:"교전",action:"pirate-fight",primary:true},{label:"항복",action:"pirate-surrender"},{label:"도주 시도",action:"pirate-flee"}])};
  proto.pirateSurrender=function(){const cargoValue=this.economy.cargoValue(this.s),poor=this.s.money<=10&&cargoValue<=100;if(poor&&!this.s.encounters.piratePity){this.s.encounters.piratePity=true;this.s.money+=100;this.e.close();this.e.toast("해적이 가엾다며 100금을 던져 주었습니다")}else{this.s.money=0;for(const id of Object.keys(this.s.cargo))this.s.cargo[id]=0;this.s.crew.morale=Math.max(0,this.s.crew.morale-18);this.e.close();this.e.toast("휴대금과 화물을 모두 빼앗겼습니다")}this.save()};
  proto.rescueAfterLoss=function(reason){const port=this.s.homePort||this.s.lastPort||"bella",map=HL.WorldData.townMapFor(port);this.s.currentPort=port;this.s.money=Math.floor(this.s.money*.5);for(const id of Object.keys(this.s.cargo))this.s.cargo[id]=0;this.s.fleet[0].hull=35;this.s.fleet[0].crew=Math.max(8,Math.floor(this.s.fleet[0].crew*.6));this.s.fleet[0].sailCondition=40;this.s.crew.health=45;this.s.crew.fatigue=65;this.s.day+=3;this.s.hour=9;this.mode="town";this.s.town={x:map.spawn[0],y:map.spawn[1],dir:0};this.spawnTownNpcs();this.e.close();this.e.playMusic("port");this.save();this.e.dialogue("항만 의사",`${reason} 구조선이 함대를 ${HL.DATA.ports[port].name}으로 데려왔습니다.`,[{label:"회복한다",action:"close"}])};

  proto.startTavernEvent=function(){this.mode="tavernEvent";this.tavernEvent={elapsed:0,beat:0};this.e.close();this.e.playMusic("danger")};
  proto.updateTavernEvent=function(dt){this.tavernEvent.elapsed+=dt;const beat=Math.floor(this.tavernEvent.elapsed/.55);if(beat>this.tavernEvent.beat&&beat<=3){this.tavernEvent.beat=beat;this.e.sfx("wood_knock",.8)}if(this.tavernEvent.elapsed>=2.5){this.s.day++;this.s.hour=9;this.s.crew.morale=Math.max(0,this.s.crew.morale-12);this.s.encounters.tavernRiotDay=this.s.day;this.mode="town";this.e.playMusic("port");this.save();this.e.dialogue("오르소 벤","선장님을 술집 밖에서 발견했습니다. 다음부터는 마지막 동전까지 걸지 마십시오.",[{label:"일어난다",action:"close"}])}};

  proto.dispatchAction=function(a,b){
    this.ensureExpansion();
    if(a==="world-map")return this.openWorldMap();if(a==="world-close")return this.closeWorldMap();if(a==="search-sea")return this.searchSea();
    if(a==="use-lime"){if(!(this.s.cargo.lime_juice>0))return this.e.toast("라임 주스가 없습니다");this.s.cargo.lime_juice--;this.s.crew.health=Math.min(100,this.s.crew.health+18);if(this.s.crew.disease==="괴혈병")this.s.crew.disease=null;this.save();this.e.toast("괴혈병 증상이 가라앉았습니다");return this.openSeaMenu()}if(a==="use-medicine"){if(!(this.s.cargo.medicine>0))return this.e.toast("의약품이 없습니다");this.s.cargo.medicine--;this.s.crew.health=Math.min(100,this.s.crew.health+14);if(this.s.crew.disease==="열병")this.s.crew.disease=null;this.save();this.e.toast("열병을 치료했습니다");return this.openSeaMenu()}
    if(a==="bank-menu")return this.bankMenu();if(a.startsWith("bank-deposit:")){const v=a.split(":")[1],amount=v==="all"?this.s.money:Math.min(this.s.money,+v);this.s.money-=amount;this.s.bank.balance+=amount;this.save();return this.bankMenu()}if(a.startsWith("bank-withdraw:")){const v=a.split(":")[1],amount=v==="all"?this.s.bank.balance:Math.min(this.s.bank.balance,+v);this.s.bank.balance-=amount;this.s.money+=amount;this.save();return this.bankMenu()}if(a==="bank-loan"){if(this.s.bank.loan)return this.e.toast("기존 대출을 먼저 상환하십시오");this.s.bank.loan=500;this.s.bank.dueDay=this.s.day+30;this.s.money+=500;this.save();return this.bankMenu()}if(a==="bank-repay"){if(!this.s.bank.loan)return this.e.toast("상환할 대출이 없습니다");if(this.s.money<this.s.bank.loan)return this.e.toast("휴대금이 부족합니다");this.s.money-=this.s.bank.loan;this.s.bank.loan=0;this.save();return this.bankMenu()}
    if(a==="property-menu")return this.propertyMenu();if(a==="buy-property"){const p=HL.DATA.ports[this.s.currentPort],price=1800+Math.round(p.economy*2);if(this.s.money<price)return this.e.toast("주택 구입금이 부족합니다");this.s.money-=price;this.s.properties[this.s.currentPort]={boughtDay:this.s.day};this.s.storage[this.s.currentPort]={};this.save();return this.propertyMenu()}if(a==="home-rest"){this.s.day++;this.s.hour=8;this.s.crew.health=100;this.s.crew.fatigue=0;this.s.crew.disease=null;this.s.fleet[0].crew=Math.max(8,this.s.fleet[0].crew);this.save();return this.e.toast("집에서 충분히 쉬었습니다")}if(a==="home-port"){this.s.homePort=this.s.currentPort;this.save();return this.e.toast("이 항구를 귀환항으로 지정했습니다")}if(a==="home-storage")return this.e.toast("보관 창고가 비어 있습니다")
    if(a.startsWith("poker:")){const bet=+a.split(":")[1];if(this.s.money<bet)return this.e.toast("판돈이 부족합니다");const rng=new HL.SeededRandom(this.s.rngSeed),player=Math.floor(rng.next()*9)+Math.floor(rng.next()*9),dealer=Math.floor(rng.next()*9)+Math.floor(rng.next()*9);this.s.rngSeed=rng.seed;if(player>=dealer){this.s.money+=bet;this.e.toast(`포커 승리 · ${bet}금 획득`)}else{this.s.money-=bet;this.e.toast(`포커 패배 · ${bet}금 손실`)}this.save();if(this.s.money===0)return this.e.dialogue("술집 주인","마지막 동전까지 잃었습니다. 조용히 나가시겠습니까?",[{label:"조용히 나간다",action:"close"},{label:"상을 내리친다",action:"tavern-rage",primary:true}]);return this.innMenu()}if(a==="tavern-rage")return this.startTavernEvent();
    if(a.startsWith("equip:")){const[,slot,id]=a.split(":"),part=HL.DATA.shipEquipment[slot==="figurehead"?"figureheads":slot==="sail"?"sails":"hulls"][id];if(this.s.money<part.price)return this.e.toast("개조 비용이 부족합니다");this.s.money-=part.price;this.s.fleet[0].equipment[slot]=id;this.save();return this.shipyardMenu()}
    if(a==="pirate-fight"){this.e.close();return this.startBattle("pirate")}if(a==="pirate-surrender")return this.pirateSurrender();if(a==="pirate-flee"){const rng=new HL.SeededRandom(this.s.rngSeed);this.s.rngSeed=rng.seed;if(rng.next()+this.s.stats.navigation/100>.8){this.e.close();return this.e.toast("해적 함대의 추격을 따돌렸습니다")}return this.startBattle("pirate")}
    if(a==="caribbean-duel"){this.e.close();return this.startBattle("pirate")}if(a==="caribbean-toast"){this.s.crew.morale=Math.min(100,this.s.crew.morale+8);this.e.close();this.save();return this.e.toast("재스퍼 로크가 숨겨진 암초 항로를 알려 주었습니다")}
    if(a==="hostile-bribe"){if(this.s.money<300)return this.e.toast("뇌물이 부족합니다");this.s.money-=300;this.s.nationRelations[HL.DATA.ports[this.pendingPort].nation]+=5;return this.completeDock(this.pendingPort)}if(a==="hostile-disguise"){const ok=(this.s.stats.charm+this.s.stats.luck)%100>45;return ok?this.completeDock(this.pendingPort):this.e.toast("위장이 발각되었습니다") }if(a==="hostile-break"){this.e.close();return this.startBattle("port")}
    if(a==="discovery-log")return this.e.dialogue("발견 기록",this.s.discoveries.length?this.s.discoveries.map(d=>`${d.name} · 가치 ${d.value}`).join("\n"):"아직 보고할 발견물이 없습니다.",[{label:"확인",action:"close"}]);
    if(a==="rest"){if(this.s.money<20)return this.e.toast("금화가 부족합니다");this.s.money-=20;this.s.day++;this.s.hour=8;this.s.crew.health=Math.min(100,this.s.crew.health+45);this.s.crew.fatigue=0;this.s.crew.morale=Math.min(100,this.s.crew.morale+18);this.s.crew.disease=null;this.save();return this.lodgeMenu()}
    if(a.startsWith("route:")){const id=a.split(":")[1];this.s.sea.autoTarget=id;this.s.sea.anchor=false;this.seaMenu=false;this.mode="sea";this.e.close();return}
    return originalDispatch.call(this,a,b);
  };

  const art=HL.Art.prototype;
  art.worldProject=function(lon,lat,centerLon,centerLat,scale){let dx=lon-centerLon;if(centerLon>120&&lon<-120)dx+=360;if(centerLon<-120&&lon>120)dx-=360;return[480+dx*Math.cos(centerLat*Math.PI/180)*scale,295-(lat-centerLat)*scale]};
  art.worldSea=function(game){const e=game.e,c=e.ctx,s=game.s,t=performance.now()/1000,scale=30*(s.sea.zoom||1);e.clear("#061b31");const ocean=c.createLinearGradient(0,80,0,540);ocean.addColorStop(0,"#0a3158");ocean.addColorStop(.55,"#07517a");ocean.addColorStop(1,"#043b60");c.fillStyle=ocean;c.fillRect(0,72,960,468);for(let y=90;y<540;y+=22)for(let x=-30;x<990;x+=54){const wave=Math.sin(x*.023+y*.017+t*1.8)*7;c.strokeStyle="rgba(104,202,213,.18)";c.beginPath();c.moveTo(x+wave,y);c.quadraticCurveTo(x+20+wave,y-4,x+40+wave,y);c.stroke()}
    for(const poly of game.navigation.land){c.beginPath();poly.forEach(([lon,lat],i)=>{const[x,y]=this.worldProject(lon,lat,s.sea.lon,s.sea.lat,scale);i?c.lineTo(x,y):c.moveTo(x,y)});c.closePath();c.fillStyle="#274d37";c.fill();c.strokeStyle="#58a390";c.lineWidth=7;c.stroke();c.strokeStyle="#b4b06d";c.lineWidth=2;c.stroke()}c.lineWidth=1;
    for(const[id,p]of Object.entries(HL.DATA.ports)){if(p.tier>s.worldPhase)continue;const[x,y]=this.worldProject(p.lon,p.lat,s.sea.lon,s.sea.lat,scale);if(x<-30||x>990||y<65||y>560)continue;const known=s.knownPorts.includes(id);c.fillStyle=known?"#e3bd58":"#7db8ad";c.beginPath();c.arc(x,y,known?7:4,0,Math.PI*2);c.fill();if(known)e.text(p.name,x,y-12,"#fff0bd","center",12)}for(const[x,y,r]of game.navigation.reefs){const[px,py]=this.worldProject(x,y,s.sea.lon,s.sea.lat,scale);if(px>0&&px<960&&py>70&&py<540){c.strokeStyle="rgba(114,225,207,.55)";c.beginPath();c.arc(px,py,r*scale,0,Math.PI*2);c.stroke()}}
    if(s.sea.autoTarget){const p=HL.DATA.ports[s.sea.autoTarget],[tx,ty]=this.worldProject(p.lon,p.lat,s.sea.lon,s.sea.lat,scale);c.setLineDash([8,8]);c.strokeStyle="#e5bf59";c.beginPath();c.moveTo(480,295);c.lineTo(tx,ty);c.stroke();c.setLineDash([])}const bob=Math.sin(t*2.4)*3;c.save();c.translate(480,295+bob);c.rotate(Math.sin(t*1.3)*.02);this.ship(e,0,0,s.sea.heading,s.fleet[0].type,1.45);c.restore();
    const eq=s.fleet[0].equipment||{};c.save();c.translate(480,295+bob);c.rotate(s.sea.heading*Math.PI/4);if(eq.figurehead&&eq.figurehead!=="none"){c.fillStyle=eq.figurehead==="dragon"?"#e6b94e":"#8ed0c5";c.beginPath();c.moveTo(0,-65);c.lineTo(7,-52);c.lineTo(-7,-52);c.closePath();c.fill()}if(eq.sail==="lateen"||eq.sail==="topsail"){c.strokeStyle=eq.sail==="lateen"?"#e0c570":"#d76d54";c.lineWidth=3;c.beginPath();c.moveTo(-14,-34);c.lineTo(14,-14);c.stroke();c.lineWidth=1}c.restore();c.fillStyle="rgba(2,13,20,.88)";c.fillRect(0,468,960,72);e.text(`해류·항로 예보  ${s.sea.weather} | 풍 ${HL.DATA.directionNames[s.sea.wind]} | 해류 ${HL.DATA.directionNames[s.sea.current]} | 수심 ${s.sea.depth}m | 폭풍 위험 ${Math.round((.025*(1-game.navigation.reduction(s.fleet[0],"stormReduction")))*100)}%`,24,498,"#d9d4a4","left",14);e.text("M 세계지도",24,526,"#f0bd55","left",13);for(const[label,y]of[["관찰",380],["수색",414],["교전",448]]){c.fillStyle="rgba(10,36,43,.9)";c.fillRect(835,y,100,28);c.strokeStyle="#9b7b38";c.strokeRect(835.5,y+.5,99,27);e.text(label,885,y+19,"#f5dfaa","center",13)}};
  art.worldMap=function(game){const e=game.e,c=e.ctx,s=game.s;e.clear("#071923");c.fillStyle="#0b3e58";c.fillRect(25,55,910,420);const project=(lon,lat)=>[25+(lon+180)/360*910,55+(80-lat)/140*420];for(const poly of game.navigation.land){c.beginPath();poly.forEach(([lon,lat],i)=>{const[x,y]=project(lon,lat);i?c.lineTo(x,y):c.moveTo(x,y)});c.closePath();c.fillStyle="#355d43";c.fill();c.strokeStyle="#839264";c.stroke()}for(const id of s.knownPorts){const p=HL.DATA.ports[id];if(!p)continue;const[x,y]=project(p.lon,p.lat);c.fillStyle="#e2b84f";c.fillRect(x-3,y-3,7,7)}for(const d of s.discoveries){const[x,y]=project(d.lon,d.lat);e.text("◆",x,y,"#f4e6a4","center",12)}const[x,y]=project(s.sea.lon,s.sea.lat);c.fillStyle="#fff";c.beginPath();c.arc(x,y,5,0,Math.PI*2);c.fill();e.text("세계 해도",32,38,"#e9bd59","left",24);e.text(`발견 항구 ${s.knownPorts.length}/120 · 발견물 ${s.discoveries.length} · 개방 단계 ${s.worldPhase}`,928,38,"#d8ddb9","right",14);e.text("M / Esc 닫기",928,515,"#e9bd59","right",14)};
  art.duel=function(game){const e=game.e,c=e.ctx,t=performance.now()/1000;e.clear("#0b2430");const sky=c.createLinearGradient(0,0,0,330);sky.addColorStop(0,"#275a70");sky.addColorStop(1,"#d19555");c.fillStyle=sky;c.fillRect(0,0,960,330);c.fillStyle="#1b5670";c.fillRect(0,260,960,130);for(let x=0;x<960;x+=56){c.strokeStyle="rgba(205,235,225,.25)";c.beginPath();c.moveTo(x,285+Math.sin(x*.03+t)*7);c.lineTo(x+35,285+Math.sin(x*.03+t+1)*7);c.stroke()}c.fillStyle="#5c3821";c.fillRect(0,350,960,190);for(let y=365;y<540;y+=29){c.strokeStyle="#29170f";c.beginPath();c.moveTo(0,y);c.lineTo(960,y);c.stroke()}for(let x=20;x<960;x+=76){c.strokeStyle="rgba(218,166,91,.22)";c.beginPath();c.moveTo(x,350);c.lineTo(x-20,540);c.stroke()}c.strokeStyle="#b49359";c.lineWidth=5;c.beginPath();c.moveTo(70,0);c.lineTo(170,360);c.moveTo(890,0);c.lineTo(790,360);c.stroke();c.lineWidth=1;this.person(e,230,500,2,true,t,3,"rian",true);this.person(e,730,500,6,false,t+.5,3,"vardo",true);e.text("새벽까마귀 갑판",480,42,"#fff0bd","center",24)};
  art.tavernEvent=function(game){const e=game.e,c=e.ctx,t=game.tavernEvent.elapsed;e.clear("#000");if(t>1.75){const a=Math.min(1,(t-1.75)/.65);c.fillStyle=`rgba(96,61,37,${a})`;c.fillRect(0,0,960,540);e.text("술집 밖 골목",480,230,`rgba(244,224,174,${a})`,"center",25);e.text("리안은 몇 걸음도 떼지 못하고 쓰러졌다.",480,278,`rgba(220,211,185,${a})`,"center",18)}};
})();
