window.HL=window.HL||{};
(function(){
  "use strict";
  const copy=value=>JSON.parse(JSON.stringify(value)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const firstChapter=state=>!state?.campaign?.chapterId||["lights-out","inherited-route"].includes(state.campaign.chapterId);
  HL.isBeginnerProtected=state=>!!(state?.beginnerProtection?.enabled&&!state.beginnerProtection.completed&&firstChapter(state));
  const blocked=(scene,x,y)=>!scene||x<scene.navigation.walkBounds[0]||y<scene.navigation.walkBounds[1]||x>scene.navigation.walkBounds[0]+scene.navigation.walkBounds[2]||y>scene.navigation.walkBounds[1]+scene.navigation.walkBounds[3]||scene.navigation.solids.some(r=>x>=r[0]&&y>=r[1]&&x<=r[0]+r[2]&&y<=r[1]+r[3]);
  const nearestSafe=(scene,x,y)=>{if(!blocked(scene,x,y))return[x,y];for(let radius=.5;radius<10;radius+=.5)for(let a=0;a<Math.PI*2;a+=Math.PI/8){const nx=x+Math.cos(a)*radius,ny=y+Math.sin(a)*radius;if(!blocked(scene,nx,ny))return[nx,ny]}return[...scene.spawn]};

  HL.migrateStateV13=function(prior){
    const state=HL.migrateStateV12(prior||HL.Game.freshState());state.version=13;state.graphicsVersion=13;
    state.onboarding={enabled:true,seen:[],...(state.onboarding||{})};
    state.beginnerProtection={enabled:true,completed:false,announcedEnd:false,...(state.beginnerProtection||{})};
    state.tradeState={selected:"glass",intent:"buy",quantity:1,...(state.tradeState||{})};state.averageCost=state.averageCost||{};state.marketStock=state.marketStock||{};
    state.v13={playSeconds:0,lastEvent:"항해를 준비하고 있습니다.",autosaveAt:0,sessionAt:Date.now(),...(state.v13||{})};
    if(state.mode==="interior"&&state.interior){const facility=state.interior.buildingId||state.interior.id,building=HL.DATA.buildingScenes[state.currentPort]?.[facility],floor=building?.floors[state.interior.floorId]||building?.floors[building?.entryFloor];if(floor){const safe=nearestSafe(floor,Number(state.interior.x)||floor.spawn[0],Number(state.interior.y)||floor.spawn[1]);Object.assign(state.interior,{buildingId:facility,floorId:floor.floorId,x:safe[0],y:safe[1]})}else{state.mode="town";state.interior=null}}
    return state;
  };

  class TradeViewModel{
    constructor(state){this.state=state}
    capacity(){const ship=this.state.fleet[0],spec=HL.DATA.ships[ship.type]||HL.DATA.ships.caravel;return spec.cargo}
    used(){return Object.values(this.state.cargo||{}).reduce((n,v)=>n+(typeof v==="number"?v:0),0)}
    stock(portId,goodId){const market=this.state.marketStock[portId]||(this.state.marketStock[portId]={});return market[goodId]??(market[goodId]=36+(Math.abs(this.hash(portId+goodId))%65))}
    hash(text){let h=0;for(const c of text)h=(Math.imul(h,31)+c.charCodeAt(0))|0;return h}
    item(portId,goodId,intent="buy",quantity=1){const good=HL.DATA.goods.find(g=>g.id===goodId)||HL.DATA.goods[0],port=HL.DATA.ports[portId],prices=port.market[good.id]||null,owned=this.state.cargo[good.id]||0,stock=prices?this.stock(portId,good.id):0,free=Math.max(0,this.capacity()-this.used()),price=prices?prices[intent==="buy"?0:1]:0,max=!prices?0:intent==="buy"?Math.max(0,Math.min(stock,free,Math.floor(this.state.money/Math.max(1,price)))):owned,qty=clamp(quantity,1,Math.max(1,max)),average=this.state.averageCost[good.id]||0,profit=intent==="sell"&&average?Math.round((price-average)*qty):null;
      const reason=max>0?"":!prices?"이 항구에서는 취급하지 않는 품목입니다.":intent==="buy"?(stock<=0?"항구 재고가 없습니다.":free<=0?"화물칸이 가득 찼습니다.":`금화 ${Math.max(0,price-this.state.money)}이 더 필요합니다.`):"판매할 화물이 없습니다.";
      return{good,price,owned,stock,free,max,quantity:qty,total:price*qty,average,profit,reason,intent}
    }
    commit(portId,goodId,intent,quantity){const v=this.item(portId,goodId,intent,quantity);if(!v.max)return v;const qty=Math.min(v.quantity,v.max),stock=this.state.marketStock[portId];if(intent==="buy"){const before=this.state.cargo[goodId]||0,old=this.state.averageCost[goodId]||0;this.state.money-=v.price*qty;this.state.cargo[goodId]=before+qty;this.state.averageCost[goodId]=Math.round(((old*before)+(v.price*qty))/(before+qty));stock[goodId]-=qty}else{this.state.money+=v.price*qty;this.state.cargo[goodId]-=qty;stock[goodId]+=qty}return{...v,quantity:qty,total:v.price*qty}}
  }
  HL.TradeViewModel=TradeViewModel;

  const engine=HL.Engine.prototype,oldDelete=engine.deleteSlot;
  engine.v12SlotKey=i=>`horizon-ledger-v12-slot-${i}`;engine.slotKey=i=>`horizon-ledger-v13-slot-${i}`;
  engine.loadSlot=function(i){try{const value=JSON.parse(localStorage.getItem(this.slotKey(i)));return value&&value.version===13?value:null}catch{return null}};
  engine.migrateOld=function(i){if(this.loadSlot(i))return;try{const keys=[this.v12SlotKey(i),`horizon-ledger-v11-slot-${i}`,`horizon-ledger-v10-slot-${i}`,`horizon-ledger-v9-slot-${i}`,`horizon-ledger-v8-slot-${i}`,`horizon-ledger-v7-slot-${i}`,`horizon-ledger-v6-slot-${i}`,`horizon-ledger-v5-slot-${i}`],prior=keys.map(k=>JSON.parse(localStorage.getItem(k)||"null")).find(Boolean);if(prior)this.saveSlot(i,HL.migrateStateV13(prior))}catch(error){console.warn("v13 save migration failed",error)}};
  engine.deleteSlot=function(i){oldDelete.call(this,i);localStorage.removeItem(this.slotKey(i))};

  const proto=HL.Game.prototype,oldFresh=HL.Game.freshState,oldEnsure=proto.ensureExpansion,oldSave=proto.save,oldShowFiles=proto.showFiles,oldMarket=proto.marketMenu,oldShipyard=proto.shipyardMenu,oldHarbor=proto.harborMenu,oldSetSail=proto.setSail,oldJournal=proto.openJournal,oldDispatch=proto.dispatchAction,oldHud=proto.renderHud,oldLoseBattle=proto.loseBattle,oldSettings=proto.settings,oldProgress=proto.progressCampaign;
  HL.Game.freshState=function(){const s=oldFresh.call(this);s.version=13;s.graphicsVersion=13;s.onboarding={enabled:true,seen:[]};s.beginnerProtection={enabled:true,completed:false,announcedEnd:false};s.tradeState={selected:"glass",intent:"buy",quantity:1};s.averageCost={};s.marketStock={};s.v13={playSeconds:0,lastEvent:"첫 항해를 준비한다.",autosaveAt:0,sessionAt:Date.now()};return s};
  proto.ensureExpansion=function(){oldEnsure.call(this);if(!this.s)return;this.s.version=13;this.s.graphicsVersion=13;this.s.onboarding={enabled:true,seen:[],...(this.s.onboarding||{})};this.s.beginnerProtection={enabled:true,completed:false,announcedEnd:false,...(this.s.beginnerProtection||{})};this.s.tradeState={selected:"glass",intent:"buy",quantity:1,...(this.s.tradeState||{})};this.s.averageCost=this.s.averageCost||{};this.s.marketStock=this.s.marketStock||{};this.s.v13={playSeconds:0,lastEvent:"항해 중",autosaveAt:0,sessionAt:Date.now(),...(this.s.v13||{})}};
  proto.save=function(){if(this.s){this.ensureExpansion();const now=Date.now(),last=this.s.v13.sessionAt||now;this.s.v13.playSeconds+=Math.max(0,Math.min(300,(now-last)/1000));this.s.v13.sessionAt=now;this.s.v13.autosaveAt=performance.now()}return oldSave.call(this)};
  proto.coachV13=function(id,text){this.ensureExpansion();if(!this.s.onboarding.enabled||this.s.onboarding.seen.includes(id))return false;this.s.onboarding.seen.push(id);this.s.v13.lastEvent=text;this.e.toast(`오르소 · ${text}`);oldSave.call(this);return true};

  proto.showFiles=function(){const result=oldShowFiles.call(this),slots=this.e.overlay.querySelectorAll?.(".slot");slots?.forEach((el,index)=>{const s=this.e.loadSlot(index+1);if(!s)return;const location=s.mode==="sea"?"해상":`${HL.DATA.ports[s.currentPort]?.name||"미확인 항구"}${s.mode==="interior"?` · ${s.interior?.buildingId||s.interior?.id} ${s.interior?.floorId||"1f"}`:""}`,hours=Math.floor((s.v13?.playSeconds||0)/3600),minutes=Math.floor((s.v13?.playSeconds||0)%3600/60),small=el.querySelector("small");if(small)small.innerHTML=`${s.year}년 ${s.month}월 ${s.day}일 · ${location}<br>${s.quest?.objective||"자유 항해"}<br>플레이 ${hours}시간 ${minutes}분 · ${s.v13?.lastEvent||"최근 기록 없음"}`});return result};

  proto.renderV13Trade=function(){
    const state=this.s.tradeState,vm=new TradeViewModel(this.s),p=HL.DATA.ports[this.s.currentPort],goods=HL.DATA.goods.filter(g=>p.market[g.id]);
    if(!p.market[state.selected]){state.selected=(goods.find(g=>(this.s.cargo[g.id]||0)>0)||goods[0]||HL.DATA.goods[0]).id;state.quantity=1}
    const v=vm.item(this.s.currentPort,state.selected,state.intent,state.quantity),used=vm.used(),capacity=vm.capacity(),rows=goods.map(g=>{const x=vm.item(this.s.currentPort,g.id,state.intent,1);return`<button class="trade-item ${g.id===state.selected?"selected":""}" data-action="v13-trade-select:${g.id}"><strong>${g.name}</strong><span>구입 ${p.market[g.id][0]} · 판매 ${p.market[g.id][1]}</span><small>보유 ${x.owned} · 재고 ${x.stock}</small></button>`}).join("");
    const disabled=v.max?"":"disabled",profit=v.profit==null?"평균 매입가가 기록되면 예상 손익을 계산합니다.":`예상 손익 ${v.profit>=0?"+":""}${v.profit}금`;
    this.e.window(`<div class="v13-shop-head"><div><small>${p.name}</small><h1>교역소</h1></div><div><b>금화 ${this.s.money}</b><span>적재 ${used}/${capacity}</span></div></div><div class="v13-trade"><section class="trade-list">${rows}</section><section class="trade-detail"><small>${state.intent==="buy"?"구입":"판매"}</small><h2>${v.good.name}</h2><div class="trade-stat"><span>현지 단가</span><b>${v.price}금</b><span>보유 / 항구 재고</span><b>${v.owned} / ${v.stock}</b><span>평균 매입가</span><b>${v.average||"기록 없음"}</b><span>거래 후 금화</span><b>${state.intent==="buy"?this.s.money-v.total:this.s.money+v.total}</b><span>거래 후 적재</span><b>${state.intent==="buy"?used+v.quantity:used-v.quantity}/${capacity}</b></div><p class="trade-profit">${profit}</p><div class="trade-mode">${this.e.button("구입","v13-trade-mode:buy",state.intent==="buy"?"primary":"")}${this.e.button("판매","v13-trade-mode:sell",state.intent==="sell"?"primary":"")}</div><div class="quantity"><button data-action="v13-trade-qty:-5">-5</button><button data-action="v13-trade-qty:-1">-1</button><b>${v.quantity}개 · ${v.total}금</b><button data-action="v13-trade-qty:1">+1</button><button data-action="v13-trade-qty:5">+5</button></div><div class="toolbar"><button data-action="v13-trade-max" ${disabled}>최대 ${v.max}</button><button class="primary" data-action="v13-trade-commit" ${disabled}>${state.intent==="buy"?"구입":"판매"} 확정</button>${this.e.button("끝내기","close")}</div>${v.reason?`<p class="blocked-reason">${v.reason}</p>`:""}</section></div>`,"center wide v13-shop");
  };
  proto.marketMenu=function(){oldMarket.call(this);if(this.v9Challenge||this.e.overlay.querySelector?.(".fragment-puzzle,.dialogue"))return;this.coachV13("trade","목록에서 품목을 고르면 가격과 거래 뒤 상태를 미리 볼 수 있습니다.");this.renderV13Trade()};
  proto.commitV13Trade=function(){const t=this.s.tradeState,vm=new TradeViewModel(this.s),result=vm.commit(this.s.currentPort,t.selected,t.intent,t.quantity);if(!result.max)return this.e.toast(result.reason);if(t.intent==="buy"){if(this.s.currentPort==="lume"&&t.selected==="wine")this.s.flags.boughtWine=true;if(this.s.currentPort==="lume"&&t.selected==="timber")this.s.flags.boughtTimber=true}else if(this.s.currentPort==="lume"&&t.selected==="glass")this.s.flags.soldGlass=true;if(this.s.quest.stage===2&&this.s.flags.soldGlass&&this.s.flags.boughtWine&&this.s.flags.boughtTimber){this.s.quest.stage=3;this.s.quest.objective="안트베르펜 여관에서 소문을 듣고 길드 의뢰를 확인하라."}this.s.v13.lastEvent=`${result.good.name} ${result.quantity}개 ${t.intent==="buy"?"구입":"판매"}`;this.e.sfx("coin_trade");this.save();this.renderV13Trade()};

  proto.shipyardMenu=function(){oldShipyard.call(this);if(this.e.overlay.querySelector?.(".dialogue"))return;const ship=this.s.fleet[0],spec=HL.DATA.ships[ship.type]||HL.DATA.ships.caravel,max=spec.hull||ship.hull;this.coachV13("shipyard","개조 전후 수치와 비용을 확인한 뒤 장비를 선택하십시오.");this.e.window(`<div class="facility-title"><div><small>${HL.DATA.ports[this.s.currentPort].name}</small><h1>조선소</h1></div><b>${ship.name}</b></div><div class="v13-shipyard"><canvas id="ship-preview-v13" width="384" height="256"></canvas><section><div class="ship-stats"><span>선체</span><b>${ship.hull}/${max}</b><span>적재량</span><b>${spec.cargo}</b><span>추진력</span><b>${spec.power}</b><span>조종성</span><b>${spec.handling||5}</b><span>대포</span><b>${ship.guns}문 → ${ship.guns+2}문</b><span>폭풍 저항</span><b>${Math.round((HL.DATA.shipEquipment?.figureheads?.[ship.equipment?.figurehead||"none"]?.stormReduction||0)*100)}%</b></div><div class="ship-actions">${this.e.button("전체 수리 · 상태 복구","repair")}${this.e.button("대포 +2 · 200금","remodel-guns")}${this.e.button("돛 개조 · 150금","remodel-sail")}${this.e.button("선수상 · 180금","figurehead")}${this.e.button("중고 코그 · 1,200금","buy-ship")}${this.e.button("선박 판매","sell-ship")}${this.e.button("선명 변경","rename")}${this.e.button("끝내기","close")}</div></section></div>`,"center wide v13-shipyard-window");this.renderV13ShipPreview?.()};

  proto.departureInfoV13=function(){const ship=this.s.fleet[0],task=this.campaignSystem?.currentTask(this.s),rec=this.campaignSystem?.recommendation(this.s,task)||{days:6,food:8,water:8,danger:"보통"},min=HL.DATA.ships[ship.type]?.crewMin||1,medicine=this.s.cargo?.medicine||0,checks=[{id:"crew",label:`선원 ${ship.crew}/${min}`,ok:ship.crew>=min,fix:"여관에서 선원을 모집하십시오."},{id:"food",label:`식량 ${Math.floor(ship.food)}/${rec.food}`,ok:ship.food>=rec.food,fix:`식량을 ${Math.ceil(rec.food-ship.food)} 이상 더 싣는 편이 안전합니다.`},{id:"water",label:`물 ${Math.floor(ship.water)}/${rec.water}`,ok:ship.water>=rec.water,fix:`물을 ${Math.ceil(rec.water-ship.water)} 이상 더 싣는 편이 안전합니다.`},{id:"medicine",label:`의약품 ${medicine}`,ok:rec.days<14||medicine>0,fix:"장거리 항해에는 의약품을 권장합니다."},{id:"lumber",label:`수리 목재 ${ship.lumber||0}`,ok:(ship.lumber||0)>=2,fix:"폭풍과 좌초에 대비해 목재 2 이상을 권장합니다."},{id:"ammo",label:`포탄 ${ship.cannonballs||0}`,ok:(ship.cannonballs||0)>=12,fix:"해적 해역에는 포탄 12발 이상을 권장합니다."}];return{ship,task,rec,checks,warnings:checks.filter(c=>!c.ok)}};
  proto.harborMenu=function(){oldHarbor.call(this);if(this.e.overlay.querySelector?.(".dialogue"))return;const d=this.departureInfoV13();this.coachV13("harbor","출항 전에 선원과 보급을 확인하십시오. 부족해도 출항할 수 있지만 위험합니다.");this.e.window(`<div class="facility-title"><div><small>${HL.DATA.ports[this.s.currentPort].name}</small><h1>항만 사무소</h1></div><b>${d.task?`목적 · ${d.task.title}`:"자유 항해"}</b></div><div class="departure-grid"><section><h2>출항 점검</h2>${d.checks.map(c=>`<div class="departure-check ${c.ok?"ok":"warn"}"><b>${c.ok?"✓":"!"} ${c.label}</b><small>${c.ok?"준비됨":c.fix}</small></div>`).join("")}</section><section><h2>항해 예상</h2><p>예상 ${d.rec.days}일 · 위험도 ${d.rec.danger}</p><p>바람과 폭풍으로 실제 일정은 달라질 수 있습니다.</p><div class="menu-grid">${this.e.button("권장 보급 채우기","v13-provision","primary")}${this.e.button("식량 +10 · 40금","food")}${this.e.button("물 +10 · 30금","water")}${this.e.button("화물·선원 이동","transfer")}</div></section></div><div class="toolbar right">${this.e.button(d.warnings.length?`경고 ${d.warnings.length}건 확인 후 출항`:"출항","set-sail",d.warnings.length?"":"primary")}${this.e.button("끝내기","close")}</div>`,"center wide v13-harbor")};
  proto.setSail=function(){const d=this.departureInfoV13();if(!this.v13DepartureConfirmed&&d.warnings.length){this.e.window(`<h1>준비가 부족합니다</h1>${d.warnings.map(w=>`<p class="warning-line">${w.fix}</p>`).join("")}<p>수동 항해에서는 폭풍과 해적을 자동으로 피하지 않습니다.</p><div class="toolbar right">${this.e.button("보급으로 돌아가기","v13-harbor")}${this.e.button("위험을 감수하고 출항","v13-confirm-sail","danger")}</div>`,"center departure-warning");return}this.v13DepartureConfirmed=false;this.coachV13("sailing","방향키로 침로를 정하고 Enter로 관측·정박·함대 명령을 여십시오.");return oldSetSail.call(this)};

  proto.openJournal=function(){this.ensureExpansion();const info=this.campaignSystem.checklist(this.s),task=info.task,rec=info.recommendation,port=task?.port&&HL.DATA.ports[task.port],checks=info.checks.length?info.checks:[{done:false,text:"표시된 장소나 인물을 조사한다."}],recent=this.s.campaign.log.slice(0,3);this.e.window(`<div class="journal-head"><div><small>리안 팔코의 항해 일지</small><h1>${info.chapter.title}</h1></div><strong>${this.s.fragmentBoard.owned.length}/12</strong></div><section class="v13-next"><small>지금 할 일</small><h2>${task?.title||"자유 항해"}</h2><p>${task?.description||this.s.endingState?.epilogue||"새로운 항로와 발견물을 찾는다."}</p></section><div class="v13-journal-grid"><section><h3>가는 곳</h3><b>${port?.name||"현재 해역"}${task?.facility?` · ${this.campaignSystem.facilityName(task.facility)}`:""}</b><p>거리 약 ${rec.distance}° · 예상 ${rec.days}일</p></section><section><h3>필요한 준비</h3><p>선원 ${rec.crew} · 식량 ${rec.food} · 물 ${rec.water}</p><p>의약품 ${rec.medicine} · 위험도 ${rec.danger}</p></section><section><h3>완료 조건</h3>${checks.map(c=>`<p class="check ${c.done?"done":""}">${c.done?"✓":"□"} ${c.text}</p>`).join("")}</section></div><section class="recent-log"><h3>최근 기록</h3>${recent.length?recent.map(x=>`<span>${x}</span>`).join(""):"<span>아직 기록이 없습니다.</span>"}</section><div class="toolbar right">${this.e.button("세부 일지","v13-journal-details")}${this.e.button("황혼 해도편","fragment-board")}${this.e.button("세계지도 · M","world-map")}${this.e.button("저장","manual-save")}${this.e.button("닫기","close","primary")}</div>`,"center wide journal v13-journal")};

  proto.renderHud=function(){oldHud.call(this);if(!this.s)return;const hud=this.e.hud,saveFresh=performance.now()-(this.s.v13?.autosaveAt||-99999)<1600;if(saveFresh)hud.insertAdjacentHTML("beforeend",'<span class="autosave-v13">▣ 항해 일지 기록 중</span>');if(this.mode==="town"||this.mode==="interior")hud.classList.add("guided-hud");else hud.classList.remove("guided-hud")};
  proto.loseBattle=function(){const protectedNow=HL.isBeginnerProtected(this.s),before=protectedNow?{money:this.s.money,cargo:copy(this.s.cargo),crew:this.s.fleet.map(x=>x.crew),companions:copy(this.s.companions||{})}:null,result=oldLoseBattle.call(this);if(protectedNow){this.s.money+=Math.floor((before.money-this.s.money)/2);for(const [id,amount] of Object.entries(before.cargo))if((this.s.cargo[id]||0)<amount)this.s.cargo[id]+=Math.ceil((amount-this.s.cargo[id])/2);this.s.fleet.forEach((ship,i)=>ship.crew=Math.max(ship.crew,before.crew[i]||ship.crew));for(const[id,c]of Object.entries(before.companions))if(c.alive&&this.s.companions?.[id])this.s.companions[id].alive=true;this.s.v13.lastEvent="초보 항해 지원으로 손실 일부를 보전받았다.";this.save();this.e.dialogue("항만 구조대",`최근 안전 항구로 구조되었습니다.\n초보 항해 지원으로 금화와 화물 손실의 절반이 보전됐고 주요 동료도 구조됐습니다.\n선체를 수리하고 보급을 다시 점검하십시오.`,[{label:"복구 항목 확인",action:"close",primary:true}])}return result};
  proto.settings=function(){oldSettings.call(this);const panel=this.e.overlay.querySelector?.(".settings-v11");if(panel&&this.s){panel.insertAdjacentHTML("beforeend",`<section><h3>초보 항해 지원</h3><p>1장 동안 폭풍·좌초·질병·패배 손실을 완화합니다.</p>${this.e.button(HL.isBeginnerProtected(this.s)?"지원 조기 해제":"지원 종료됨","v13-toggle-protection",HL.isBeginnerProtected(this.s)?"danger":"")}</section>`)}};
  proto.progressCampaign=function(event){const was=HL.isBeginnerProtected(this.s),result=oldProgress.call(this,event);if(was&&!firstChapter(this.s)){this.s.beginnerProtection.completed=true;this.s.beginnerProtection.announcedEnd=true;this.e.toast("1장 완료 · 이제 일반 항해 규칙이 적용됩니다");this.save()}return result};

  proto.dispatchAction=function(action,button){
    if(action.startsWith("v13-inspect:")){const key=action.slice(12),texts={barrels:"항구 인장이 찍힌 술통이다. 산지와 도착일이 분필로 적혀 있다.",fireplace:"불가에는 젖은 외투와 오래된 항해담이 함께 마르고 있다.",meal:"오늘의 식사는 염장 고기와 검은 빵이다. 먼 항해를 앞둔 선원들이 말없이 그릇을 비운다.",crane:"도르래 홈과 밧줄의 마모가 오늘 처리한 화물의 무게를 말해 준다.",rigging:"밧줄마다 용도가 달라 묶는 법과 굵기도 다르다.",telescope:"황동 경통에는 여러 위도에서 생긴 작은 흠집이 남아 있다.",medicine:"열병약, 붕대, 라임 즙이 항해 날짜별로 정리돼 있다.",signal:"유리 덮개 안의 등불은 바람이 거세져도 꺼지지 않게 설계됐다.",portrait:"초상 속 사람들은 모두 바다 대신 서로 다른 방향을 보고 있다.",scale:"추의 마모는 고르다. 적어도 이 저울은 정직하다.",plans:"항구의 창고와 골목, 우물의 위치가 표시된 도면이다.",model:"축척 모형에는 아직 지어지지 않은 방 한 칸이 표시되어 있다.",window:"창 너머로 돛대와 항구 지붕이 겹쳐 보인다.",room:"매일 쓰이는 물건들이 손이 닿기 좋은 순서로 놓여 있다.",samples:"밀랍 봉인이 다른 여러 항구의 견본품이다.",chest:"여행객 이름과 맡긴 날짜가 적힌 꼬리표가 달려 있다.",keepsake:"오래된 나침반과 편지가 천으로 감싸여 있다."};return this.e.dialogue("조사",texts[key]||"오래 사용한 흔적에서 이곳 사람들의 생활이 느껴진다.",[{label:"돌아선다",action:"close"}])}
    if(action.startsWith("v13-trade-select:")){this.s.tradeState.selected=action.split(":")[1];this.s.tradeState.quantity=1;return this.renderV13Trade()}
    if(action.startsWith("v13-trade-mode:")){this.s.tradeState.intent=action.split(":")[1];this.s.tradeState.quantity=1;return this.renderV13Trade()}
    if(action.startsWith("v13-trade-qty:")){const delta=+action.split(":")[1],vm=new TradeViewModel(this.s),v=vm.item(this.s.currentPort,this.s.tradeState.selected,this.s.tradeState.intent,this.s.tradeState.quantity);this.s.tradeState.quantity=clamp(this.s.tradeState.quantity+delta,1,Math.max(1,v.max));return this.renderV13Trade()}
    if(action==="v13-trade-max"){const vm=new TradeViewModel(this.s),v=vm.item(this.s.currentPort,this.s.tradeState.selected,this.s.tradeState.intent,1);this.s.tradeState.quantity=Math.max(1,v.max);return this.renderV13Trade()}
    if(action==="v13-trade-commit")return this.commitV13Trade();
    if(action==="v13-harbor")return this.harborMenu();
    if(action==="v13-confirm-sail"){this.v13DepartureConfirmed=true;return this.setSail()}
    if(action==="v13-provision"){const d=this.departureInfoV13(),food=Math.max(0,Math.ceil(d.rec.food-d.ship.food)),water=Math.max(0,Math.ceil(d.rec.water-d.ship.water)),cost=Math.ceil(food/10)*40+Math.ceil(water/10)*30;if(this.s.money<cost)return this.e.toast(`권장 보급에 금화 ${cost-this.s.money}이 더 필요합니다.`);this.s.money-=cost;d.ship.food+=Math.ceil(food/10)*10;d.ship.water+=Math.ceil(water/10)*10;this.save();return this.harborMenu()}
    if(action==="v13-journal-details")return oldJournal.call(this);
    if(action==="v13-toggle-protection"){if(HL.isBeginnerProtected(this.s)){this.s.beginnerProtection.enabled=false;this.save();this.e.toast("초보 항해 지원을 해제했습니다")}return this.settings()}
    return oldDispatch.call(this,action,button);
  };

  const sim=HL.SeaSimulation.prototype,oldStorm=sim.applyStormHour,oldStep=sim.step,oldDay=sim.advanceDay;
  sim.applyStormHour=function(state,weather,events){const active=HL.isBeginnerProtected(state),before=active?state.fleet.map(s=>({h:s.hull,sa:s.sailCondition,c:s.crew})):null,health=state.crew.health,result=oldStorm.call(this,state,weather,events);if(active){state.fleet.forEach((s,i)=>{s.hull=Math.round((s.hull+before[i].h)/2);s.sailCondition=Math.round((s.sailCondition+before[i].sa)/2);s.crew=Math.max(s.crew,before[i].c)});state.crew.health=Math.round((state.crew.health+health)/2)}return result};
  sim.step=function(state,grid){const active=HL.isBeginnerProtected(state),before=active?state.fleet.map(s=>({h:s.hull,sa:s.sailCondition})):null,result=oldStep.call(this,state,grid);if(active&&result.some(e=>e.type==="grounding"))state.fleet.forEach((s,i)=>{s.hull=Math.round((s.hull+before[i].h)/2);s.sailCondition=Math.round((s.sailCondition+before[i].sa)/2)});return result};
  sim.advanceDay=function(state){const health=state.crew.health,result=oldDay.call(this,state);if(HL.isBeginnerProtected(state)&&state.crew.disease&&state.crew.health<health)state.crew.health=Math.round((state.crew.health+health)/2);return result};

  // 시설 전용 UX보다 캠페인 퍼즐이 우선한다. 이후 항만·조선소 퍼즐이 추가돼도 화면을 덮지 않는다.
  for(const [method,facility] of [["shipyardMenu","shipyard"],["harborMenu","harbor"]]){
    const enhanced=proto[method];
    proto[method]=function(){
      this.ensureExpansion();
      const task=this.campaignSystem?.currentTask(this.s);
      if(task?.trigger?.type==="challenge"&&task.port===this.s.currentPort&&task.facility===facility)return this.openV9Challenge(task.trigger.id);
      return enhanced.call(this);
    };
  }
})();
