window.HL=window.HL||{};
(function(){
  "use strict";
  const T=30,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),art=HL.Art.prototype,oldInterior=art.v10InteriorScene,oldTown=art.town,oldBattle=art.battle;
  art.v13Camera=function(scene,position){const ww=scene.width*T,wh=scene.height*T,x=ww<=960?-(960-ww)/2:clamp(position.x*T-480,0,ww-960),y=wh<=540?-(540-wh)/2:clamp(position.y*T-300,0,wh-540);return{x:Math.round(x),y:Math.round(y)}};
  art.drawV13FloorMap=function(e,scene,position,camera,target){const c=e.ctx,w=138,h=86,x=804,y=80,s=Math.min((w-12)/scene.width,(h-12)/scene.height);c.save();c.fillStyle="rgba(3,16,20,.88)";c.fillRect(x,y,w,h);c.strokeStyle="#8f733d";c.strokeRect(x+.5,y+.5,w-1,h-1);for(let ty=0;ty<scene.height;ty++)for(let tx=0;tx<scene.width;tx++){const wall=scene.tiles[ty][tx]==="wallBase"||scene.tiles[ty][tx]==="wallTop";if(wall){c.fillStyle="#745a3f";c.fillRect(x+6+tx*s,y+6+ty*s,Math.ceil(s),Math.ceil(s))}}for(const p of scene.props.filter(p=>p.solid)){c.fillStyle="#47615b";c.fillRect(x+6+p.x*s,y+6+p.y*s,Math.max(1,p.w*s),Math.max(1,p.h*s))}if(target){c.fillStyle="#efbd55";c.fillRect(x+5+(target.rect[0]+target.rect[2]/2)*s-2,y+5+(target.rect[1]+target.rect[3]/2)*s-2,5,5)}c.fillStyle="#f5efe0";c.fillRect(x+5+position.x*s-2,y+5+position.y*s-2,5,5);c.restore()};
  art.drawV13Objective=function(game,scene,position,camera){const targetFacility=game.questTarget?.(),inTarget=!targetFacility||targetFacility===scene.facility;if(!inTarget)return;const target=scene.hotspots.find(h=>h.id==="owner")||scene.hotspots[0];if(!target)return;const c=game.e.ctx,tx=(target.rect[0]+target.rect[2]/2)*T-camera.x,ty=(target.rect[1]+target.rect[3]/2)*T-camera.y,visible=tx>40&&tx<920&&ty>80&&ty<490,cx=480,cy=280;if(visible){c.fillStyle="#f2bd50";c.beginPath();c.moveTo(tx,ty-17);c.lineTo(tx+8,ty-9);c.lineTo(tx,ty-1);c.lineTo(tx-8,ty-9);c.fill();return}const angle=Math.atan2(ty-cy,tx-cx),x=clamp(cx+Math.cos(angle)*380,45,915),y=clamp(cy+Math.sin(angle)*190,95,475);c.save();c.translate(x,y);c.rotate(angle+Math.PI/2);c.fillStyle="#f2bd50";c.beginPath();c.moveTo(0,-11);c.lineTo(8,8);c.lineTo(0,4);c.lineTo(-8,8);c.closePath();c.fill();c.restore()};
  art.v13InteriorScene=function(game,scene,position,actorId="rian"){
    this.ensureV12();const e=game.e,c=e.ctx,time=performance.now()/1000,camera=this.v13Camera(scene,position),startX=Math.max(0,Math.floor(camera.x/T)-1),endX=Math.min(scene.width,Math.ceil((camera.x+960)/T)+1),startY=Math.max(0,Math.floor(camera.y/T)-1),endY=Math.min(scene.height,Math.ceil((camera.y+540)/T)+1);e.clear("#05090b");c.save();c.translate(-camera.x,-camera.y);
    for(let y=startY;y<endY;y++)for(let x=startX;x<endX;x++)this.drawV12Tile(c,scene.cultureRow,scene.tiles[y][x],x*T,y*T);
    const drawProp=(p,alpha=1)=>this.drawV12Object(c,scene,p,time,alpha);
    for(const p of scene.props)if(!p.high)drawProp(p);
    const actors=[...scene.npcs.map(n=>({npc:n,y:n.y})),{player:true,y:position.y}].sort((a,b)=>a.y-b.y);
    for(const actor of actors){if(actor.player)this.person(e,position.x*T+T/2,position.y*T+25,position.dir,actorId==="rian",game.playerAnim,scene.actorScale,actorId,game.playerMoving);else{const n=actor.npc;this.person(e,n.x*T+T/2,n.y*T+25,n.dir??4,false,time+(this.hash(n.appearanceId)%37)/11,scene.actorScale,n.appearanceId,false)}}
    for(const p of scene.props)if(p.high){const covered=position.x>p.x-.2&&position.x<p.x+p.w+.2&&position.y>p.y-.5&&position.y<p.y+p.h;drawProp(p,covered ? .46 : 1)}c.restore();
    const near=this.nearV10Interaction(position,scene),targetFacility=game.questTarget?.(),target=targetFacility===scene.facility?(scene.hotspots.find(h=>h.id==="owner")||scene.hotspots[0]):null;this.drawV13FloorMap(e,scene,position,camera,target);this.drawV13Objective(game,scene,position,camera);
    if(near){const quest=target&&near.id===target.id,label=`Enter/Z  ${near.label}`,w=Math.max(190,label.length*14+34);c.fillStyle=quest?"rgba(73,48,15,.96)":"rgba(4,18,22,.94)";c.fillRect(480-w/2,493,w,33);c.strokeStyle=quest?"#f2bd50":"#78948d";c.strokeRect(481-w/2,494,w-2,31);e.text(label,480,516,quest?"#fff0ad":"#ecf0dc","center",14)}
    const building=game.currentBuilding?.(),entered=game.s.v12?.enteredAt||0;if(performance.now()-entered<1800){c.fillStyle="rgba(3,13,16,.9)";c.fillRect(18,82,390,40);e.text(`${HL.DATA.ports[game.s.currentPort]?.name||""} · ${building?.name||scene.facility} ${scene.floorId.toUpperCase()}`,34,108,"#f2d079","left",17)}
  };
  art.v10InteriorScene=function(game,scene,position,actorId="rian",prologue=false){if(scene?.visual?.version===13)return this.v13InteriorScene(game,scene,position,actorId,prologue);return oldInterior.call(this,game,scene,position,actorId,prologue)};

  art.town=function(game){oldTown.call(this,game);if(!game.s||game.mode!=="town")return;const target=game.questTarget?.(),building=game.townBuildings?.().find(b=>b.id===target||b.facility===target);if(!building)return;const c=game.e.ctx,x=(building.door?.[0]??building.x)*30,y=(building.door?.[1]??building.y)*30;c.save();c.fillStyle="rgba(3,16,20,.88)";c.fillRect(clamp(x-70,8,812),clamp(y-58,74,466),140,28);c.strokeStyle="#eab84f";c.strokeRect(clamp(x-70,8,812)+.5,clamp(y-58,74,466)+.5,139,27);game.e.text(`◆ ${building.label||building.name||target}`,clamp(x,78,882),clamp(y-39,94,486),"#ffe49a","center",13);c.restore()};

  art.battle=function(game){oldBattle.call(this,game);const b=game.battle;if(!b)return;const c=game.e.ctx,px=(100+b.player.x*40)*1.5,py=(40+b.player.y*40)*1.5,ex=(100+b.enemy.x*40)*1.5,ey=(40+b.enemy.y*40)*1.5,dist=Math.abs(b.player.x-b.enemy.x)+Math.abs(b.player.y-b.enemy.y);c.save();c.setLineDash([5,4]);c.strokeStyle="rgba(111,218,204,.8)";c.lineWidth=2;c.beginPath();c.arc(px,py,60,0,Math.PI*2);c.stroke();c.strokeStyle=dist<=5?"rgba(245,189,75,.9)":"rgba(195,94,70,.85)";c.beginPath();c.arc(ex,ey,34,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle="rgba(3,15,19,.88)";c.fillRect(360,76,240,30);game.e.text(`거리 ${dist}칸 · ${dist<=1?"백병 가능":dist<=5?"포격 유효":"포격 위력 감소"}`,480,97,dist<=5?"#f5d77f":"#e9a08b","center",13);c.restore()};

  HL.Game.prototype.renderV13ShipPreview=function(){const canvas=document.querySelector("#ship-preview-v13");if(!canvas)return;const draw=()=>{const c=canvas.getContext("2d");c.imageSmoothingEnabled=false;const g=c.createLinearGradient(0,0,0,256);g.addColorStop(0,"#183b48");g.addColorStop(1,"#0b2731");c.fillStyle=g;c.fillRect(0,0,384,256);c.strokeStyle="rgba(120,190,190,.22)";for(let y=35;y<256;y+=20){c.beginPath();c.moveTo(0,y);c.quadraticCurveTo(96,y-7,192,y);c.quadraticCurveTo(288,y+7,384,y);c.stroke()}const e={ctx:c};this.art.ensureV12();this.art.shipRendererV12.draw(e,this.s.fleet[0].type,192,140,2,this.s.fleet[0].hull,performance.now()/1000,.78,"battle",this.s.fleet[0].equipment||{})};draw();setTimeout(draw,120);setTimeout(draw,400)};
})();
