window.HL=window.HL||{};
(function(){
  "use strict";
  const D=HL.DATA,T=24,two=new Set(["market","inn","lodge","guild","mansion"]);
  const names={market:"시장",inn:"여관",lodge:"숙소",harbor:"항만",guild:"항해자 길드",shipyard:"조선소",mansion:"저택",bank:"은행",estate:"부동산 사무소",home:"선장의 집"};
  const sizes={bank:[36,24],estate:[36,24],home:[36,24],market:[48,32],inn:[48,32],lodge:[48,32],harbor:[48,32],guild:[56,36],mansion:[64,40],shipyard:[64,40]};
  const cultures=["iberia","north","med","island","maghreb","ottoman","africa","arabia","india","seasia","china","japan","caribbean","americas"];
  const palettes={
    iberia:["#9a7450","#d3b276","#664236","#b64e37","#3e665f"],north:["#766f68","#b8a584","#3d4d59","#75433a","#536649"],med:["#a07b55","#d7bd83","#66504a","#a94f3d","#356c72"],island:["#92704d","#cba66d","#5d4936","#b56b3c","#347671"],maghreb:["#a78252","#d4bc7b","#71533e","#a7613f","#3f706d"],ottoman:["#876849","#c4a46d","#593c52","#8d3f4e","#36716b"],africa:["#76583d","#b58b58","#51392f","#9d5c34","#527247"],arabia:["#9a784d","#d0b477","#634b36","#9b5d3e","#406a6f"],india:["#8e6847","#c49c67","#663c48","#ad563d","#3b7270"],seasia:["#77583f","#b98b58","#4b4536","#a54e37","#37746a"],china:["#846247","#c3a06b","#5b3937","#a63d38","#37666b"],japan:["#786954","#b7a27e","#3e4a55","#98564b","#486c68"],caribbean:["#91704d","#cba56d","#594338","#ae6136","#31747d"],americas:["#7b6044","#b98d58","#514034","#a85b38","#577146"]
  };
  D.tileMetaV17={tileSize:T,palettes};
  const captainNames={kemal:"카이르 사판",ines:"세리아 알렌",duarte:"로안 벨라르",matteo:"테오란 코르비",anne:"에린 펜로",marieke:"메이라 벨든"};
  const replacements=[["케말 빈 유수프","카이르 사판"],["케말","카이르"],["레일라","라에나"],["이네스 데 알라르콘","세리아 알렌"],["이네스","세리아"],["두아르트 드 아벨라르","로안 벨라르"],["두아르트","로안"],["마테오 다 코르바라","테오란 코르비"],["마테오","테오란"],["앤 펜윅","에린 펜로"],["앤은","에린은"],["앤의","에린의"],["마리커 판 데르 펠데","메이라 벨든"],["마리커","메이라"]];
  const rename=value=>{if(typeof value==="string"){for(const [a,b] of replacements)value=value.split(a).join(b);return value}if(Array.isArray(value)){value.forEach((v,i)=>value[i]=rename(v));return value}if(value&&typeof value==="object")for(const k of Object.keys(value))value[k]=rename(value[k]);return value};
  for(const c of D.captainsV16){c.displayName=captainNames[c.id];c.name=c.displayName;c.portrait="../Assets/Resources/Sprites/Game/V17/Captains/captain_portraits_v17.png";c.portraitCell={column:D.captainsV16.indexOf(c)%3,row:Math.floor(D.captainsV16.indexOf(c)/3),columns:3,rows:2};c.portraitFallback=c.role}
  rename(D.campaignsV16);rename(D.crossEncountersV16);
  D.coreCastV17={layna:{name:"라에나 사판",role:"실종 선원 기록원"},ordel:{name:"오르델",role:"추방된 지도 스승"},beric:{name:"베릭 벨라르",role:"경쟁 원정가"},marcan:{name:"마르칸 로제",role:"유물 채권자"},roderic:{name:"로드릭 베인",role:"해군 대신"},sain:{name:"세인 도르프",role:"실종된 동업자"}};

  function hash(v){let h=2166136261;for(const ch of String(v))h=Math.imul(h^ch.charCodeAt(0),16777619);return h>>>0}
  function rng(seed){return()=>{seed|=0;seed=seed+0x6d2b79f5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
  function tileGrid(w,h,base="floor"){return Array.from({length:h},()=>Array(w).fill(base))}
  function carveRoom(tiles,r){for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++){const edge=x===r.x||y===r.y||x===r.x+r.w-1||y===r.y+r.h-1;tiles[y][x]=edge?(y===r.y?"wallTop":"wall"):"floor"}}
  function doorway(tiles,x,y,horizontal=true){tiles[y][x]="door";if(horizontal&&tiles[y]?.[x+1]!=null)tiles[y][x+1]="door"}
  function roomsFor(w,h,count){const rooms=[],cols=count>6?3:2,rows=Math.ceil(count/cols),rw=Math.floor((w-2)/cols),rh=Math.floor((h-2)/rows);for(let i=0;i<count;i++){const col=i%cols,row=Math.floor(i/cols),x=1+col*rw,y=1+row*rh;rooms.push({id:`room-${i+1}`,x,y,w:col===cols-1?w-1-x:rw,h:row===rows-1?h-1-y:rh})}return rooms}
  const roomCount={bank:4,estate:4,home:4,market:6,inn:6,lodge:5,harbor:5,guild:7,mansion:8,shipyard:8};
  const propSets={market:["counter","scale","shelf","supplies","loom","crates"],inn:["counter","fireplace","table","kitchen","barrels","bed"],lodge:["counter","treatment","wardrobe","bed","supplies","desk"],guild:["counter","notice","mapTable","shelf","telescope","desk"],shipyard:["counter","hull","crane","ropes","desk","supplies"],harbor:["counter","supplies","crane","ropes","desk","barrels"],mansion:["desk","fireplace","table","shelf","wardrobe","bed"],bank:["counter","desk","chest","shelf"],estate:["counter","desk","shelf","notice"],home:["table","fireplace","wardrobe","bed"]};
  const actions={market:"facility:market",inn:"facility:inn",lodge:"facility:lodge",guild:"facility:guild",shipyard:"facility:shipyard",harbor:"facility:harbor",mansion:"facility:mansion",bank:"bank-menu",estate:"property-menu",home:"home-menu"};
  function floorFor(portId,facility,floor,culture,seed){
    const [w,h]=sizes[facility],random=rng(seed+floor*991),count=roomCount[facility],rooms=roomsFor(w,h,count),tiles=tileGrid(w,h,"floor"),props=[],hotspots=[],solids=[],cx=Math.floor(w/2),cols=count>6?3:2,rows=Math.ceil(count/cols),rw=Math.floor((w-2)/cols),rh=Math.floor((h-2)/rows);
    for(let x=0;x<w;x++){tiles[0][x]="wallTop";tiles[h-1][x]="wall"}for(let y=0;y<h;y++){tiles[y][0]="wall";tiles[y][w-1]="wall"}
    for(let col=1;col<cols;col++){const x=1+col*rw;for(let y=1;y<h-1;y++)tiles[y][x]="wall";for(let row=0;row<rows;row++){const cy=1+row*rh+Math.floor(rh/2);tiles[cy][x]="door";if(cy+1<h-1)tiles[cy+1][x]="door"}}
    for(let row=1;row<rows;row++){const y=1+row*rh;for(let x=1;x<w-1;x++)tiles[y][x]="wall";for(let col=0;col<cols;col++){const rx=1+col*rw+Math.floor(rw/2);tiles[y][rx]="door";if(rx+1<w-1)tiles[y][rx+1]="door"}}
    for(let y=h-6;y<h-1;y++)for(let x=cx-2;x<=cx+2;x++)tiles[y][x]=(x===cx-2||x===cx+2)?"rugEdge":"rug";tiles[h-2][cx]="door";
    const set=propSets[facility]||propSets.home,labels={counter:"업무대",scale:"저울과 장부",shelf:"진열 선반",supplies:"보급품",loom:"직물 작업대",crates:"화물 상자",fireplace:"벽난로",table:"공용 탁자",kitchen:"부엌",barrels:"술통",bed:"침대",treatment:"치료대",wardrobe:"수납장",notice:"게시판",mapTable:"해도 작업대",telescope:"관측 기구",desk:"문서 책상",hull:"건조 중인 선체",crane:"도르래",ropes:"밧줄",chest:"금고"};
    rooms.forEach((r,i)=>{const sprite=set[i%set.length],pw=["counter","hull","mapTable"].includes(sprite)?3:2,ph=sprite==="hull"?3:2,x=Math.floor(r.x+r.w/2-pw/2),y=r.y+2;props.push({type:"v17Prop",sprite,x,y,w:pw,h:ph,solid:true,high:["counter","shelf","wardrobe","notice"].includes(sprite)});hotspots.push({id:`${facility}-${floor}-${i}`,rect:[x,y,pw,ph],label:labels[sprite],action:i===0?actions[facility]:`v17-inspect:${sprite}`});if(r.h>7){const second=set[(i+3)%set.length],sw=second==="hull"?3:2,sh=2,sx=i%2?r.x+2:r.x+r.w-sw-2,sy=r.y+r.h-sh-2;props.push({type:"v17Prop",sprite:second,x:sx,y:sy,w:sw,h:sh,solid:true,high:["counter","shelf","wardrobe","notice"].includes(second)})}const decorCount=Math.min(10,Math.max(5,Math.floor(r.w*r.h/13)));for(let d=0;d<decorCount;d++){let dx=r.x+1+Math.floor(random()*Math.max(1,r.w-2)),dy=r.y+1+Math.floor(random()*Math.max(1,r.h-2));const edge=d%2===0;dx=edge?(d%4===0?r.x+1:r.x+r.w-2):dx;dy=edge?(d%4===2?r.y+1:r.y+r.h-2):dy;if(Math.abs(dx-cx)<3&&dy>h-7)continue;props.push({type:"v17Decor",sprite:["crate","jar","stool","papers","plant","lantern"][Math.floor(random()*6)],x:dx,y:dy,w:1,h:1,solid:false,high:false})}});
    for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(tiles[y][x]==="void"||tiles[y][x]==="wall"||tiles[y][x]==="wallTop")solids.push([x,y,1,1]);for(const p of props)if(p.solid)solids.push([p.x+.12,p.y+.2,p.w-.24,p.h-.25]);
    const upper=floor===2,stairs=[];if(two.has(facility)){const room=rooms[rooms.length-1],x=room.x+Math.max(1,room.w-5),y=room.y+Math.max(2,room.h-5);props.push({type:"v17Prop",sprite:["guild","mansion"].includes(facility)?"grandStair":"sideStair",x,y,w:3,h:3,solid:false,high:true});stairs.push({id:upper?"down":"up",rect:[x+.5,y+.3,2,2.5],toFloor:upper?"1f":"2f",spawn:[x+1.5,y+2.5],approach:upper?6:2,label:upper?"1층으로":"2층으로"})}
    const owner=floor===1?{id:"owner",name:{market:"시장 상인",inn:"여관 주인",lodge:"숙소 관리인",guild:"길드장",shipyard:"조선공",harbor:"항만 관리인",mansion:"저택 관리인",bank:"은행가",estate:"중개인",home:"집사"}[facility],x:rooms[0].x+Math.floor(rooms[0].w/2),y:rooms[0].y+4,dir:4,appearanceId:`owner_${portId}_${facility}`,workZone:[rooms[0].x+1,rooms[0].y+2,rooms[0].w-2,4]}:null;
    return{id:`${portId}:${facility}:${floor}`,floorId:`${floor}f`,portId,facility,culture,width:w,height:h,tiles,rooms,props,hotspots,npcs:owner?[owner]:[],stairs,spawn:[cx,h-2.6],exit:{rect:[cx-1,h-2,2,1.4],label:"나가기"},actorScale:1.15,visual:{version:17},navigation:{walkBounds:[1,1,w-2,h-2],solids,ownerZones:owner?[owner.workZone]:[],corridorWidth:2},collision:{walkBounds:[1,1,w-2,h-2],solids,polygons:[],doors:[],interactions:hotspots}}
  }
  D.interiorTemplatesV17={};D.buildingScenes=D.buildingScenes||{};
  D.portOrder.forEach((portId,pi)=>{const port=D.ports[portId],culture=cultures.includes(port.culture)?port.culture:"med";D.buildingScenes[portId]=D.buildingScenes[portId]||{};D.interiorTemplatesV17[portId]={};Object.keys(sizes).forEach((facility,fi)=>{const floors={"1f":floorFor(portId,facility,1,culture,hash(`${portId}:${facility}`))};if(two.has(facility))floors["2f"]=floorFor(portId,facility,2,culture,hash(`${portId}:${facility}:2`));const building={id:`${portId}:${facility}`,portId,facility,culture,name:names[facility],entryFloor:"1f",floors,version:17};D.buildingScenes[portId][facility]=building;D.interiorTemplatesV17[portId][facility]=building})});
  D.tileMetaV17={tileSize:T,cultures,palettes};D.roomGraphV17={sizes,roomCount};D.propClustersV17=propSets;D.version=17;
})();
