window.HL=window.HL||{};
(function(){
  "use strict";
  const copy=v=>JSON.parse(JSON.stringify(v)),captain=id=>HL.DATA.captainsV16.find(c=>c.id===id)||HL.DATA.captainsV16[0];
  HL.migrateStateV17=function(prior){const s=copy(prior||HL.Game.freshState());s.version=17;s.graphicsVersion=15;s.v17={migratedAt:Date.now(),restoredV15Graphics:true,...(s.v17||{})};s.partyFollowerState=s.partyFollowerState||{active:[],history:[],spacing:.72};if(s.captainId&&s.captainId!=="rian")s.captainName=captain(s.captainId).name;if(s.mode==="interior"&&s.interior){const f=s.interior.buildingId||s.interior.id,b=HL.DATA.buildingScenes[s.currentPort]?.[f],floor=b?.floors[s.interior.floorId]||b?.floors[b?.entryFloor];if(floor){s.interior.buildingId=f;s.interior.floorId=floor.floorId;s.interior.x=floor.spawn[0];s.interior.y=floor.spawn[1]}else{s.mode="town";s.interior=null}}return s};
  const engine=HL.Engine.prototype;engine.v16SlotKey=i=>`horizon-ledger-v16-slot-${i}`;engine.v15SlotKey=i=>`horizon-ledger-v15-slot-${i}`;engine.slotKey=i=>`horizon-ledger-v17-slot-${i}`;
  engine.loadSlot=function(i){try{const s=JSON.parse(localStorage.getItem(this.slotKey(i)));return s?.version===17?s:null}catch{return null}};
  engine.migrateOld=function(i){if(this.loadSlot(i))return;try{const keys=[this.v16SlotKey(i),this.v15SlotKey(i),`horizon-ledger-v14-slot-${i}`,`horizon-ledger-v13-slot-${i}`],old=keys.map(k=>JSON.parse(localStorage.getItem(k)||"null")).find(Boolean);if(old)this.saveSlot(i,HL.migrateStateV17(old))}catch(error){console.warn("V17 저장 변환 실패",error)}};
  engine.deleteSlot=function(i){localStorage.removeItem(this.slotKey(i))};
  const oldApply=HL.applyCaptainV16,defaultCompanion={kemal:"kayir_helmsman",ines:"seria_assistant",duarte:"loan_guide",matteo:"teoran_diver",anne:"erin_gunner",marieke:"meira_clerk"};
  HL.applyCaptainV16=function(state,id){const s=oldApply(state,id),mate=defaultCompanion[id];s.partyFollowerState={active:mate?[mate]:[],history:[],spacing:.72};return s};
  const game=HL.Game.prototype,oldFresh=HL.Game.freshState,oldEnsure=game.ensureExpansion,oldResume=game.resume,oldNew=game.newGame,oldUpdateInterior=game.updateInterior,oldChangeFloor=game.changeFloor,oldEnter=game.enterInterior,oldLeave=game.leaveInterior,oldEnding=game.showV16Ending,oldExecute=game.executeV10InteriorAction;
  HL.Game.freshState=function(){const s=oldFresh.call(this);s.version=17;s.graphicsVersion=15;s.v17={restoredV15Graphics:true};s.partyFollowerState={active:[],history:[],spacing:.72};return s};
  game.ensureExpansion=function(){oldEnsure.call(this);if(this.s){this.s.version=17;this.s.graphicsVersion=15;this.s.v17={restoredV15Graphics:true,...(this.s.v17||{})};this.s.partyFollowerState=this.s.partyFollowerState||{active:[],history:[],spacing:.72}}};
  game.newGame=function(id=this.e.selectedCaptain||"kemal"){oldNew.call(this,id);this.s=HL.migrateStateV17(this.s);this.save()};
  game.resume=function(i){const s=this.e.loadSlot(i);if(!s)return this.showFiles();if(s.legacyCampaign){this.s=HL.migrateStateV17(s);this.s.slot=i;this.mode=this.s.mode||"town";this.ensureExpansion();this.spawnTownNpcs();this.e.close();this.ensureSafePosition();return}this.s=HL.migrateStateV17(s);this.s.slot=i;this.mode=this.s.mode||"town";if(this.mode==="v16-prologue"&&!this.s.prologueV16)this.mode="town";this.ensureExpansion();this.spawnTownNpcs();this.e.close();this.ensureSafePosition();this.e.playMusic(this.mode==="sea"?"sea":"port")};
  game.showScenarios=function(slot,selected="kemal"){
    this.e.selectedSlot=slot;this.e.selectedCaptain=selected;this.mode="scenario";const chosen=captain(selected),cell=chosen.portraitCell;
    const cards=HL.DATA.captainsV16.map(c=>`<button class="captain v17-captain ${c.id===selected?"selected":""}" data-action="captain-preview:${c.id}" style="--captain:${c.color}"><strong>${c.name}</strong><small>${c.nation} · ${c.role}</small></button>`).join("");
    const bars=Object.entries(chosen.stats).map(([key,value])=>`<div class="stat-line"><span>${{sailing:"항해",battle:"전투",knowledge:"지식",intuition:"직감",leadership:"통솔",charm:"매력",luck:"운"}[key]}</span><i><b style="width:${value}%"></b></i><em>${value}</em></div>`).join("");
    const portrait=`<div class="v17-portrait" role="img" aria-label="${chosen.name} 선장 초상"><img src="${chosen.portrait}" alt="" style="width:${cell.columns*100}%;height:${cell.rows*100}%;left:-${cell.column*100}%;top:-${cell.row*100}%"><span>${chosen.portraitFallback}</span></div>`;
    this.e.window(`<header class="scenario-head"><div><small>여섯 항로 중 하나를 선택하십시오</small><h1>선장 선택</h1></div><span>파일 ${slot}</span></header><div class="v17-scenario"><nav class="v17-captain-list">${cards}</nav><section class="v17-captain-detail" style="--captain:${chosen.color}">${portrait}<div class="v17-biography"><small>${chosen.nation}</small><h2>${chosen.name}</h2><p>${chosen.hook}</p><strong>${chosen.specialty}</strong><dl><div><dt>시작항</dt><dd>${HL.DATA.ports[chosen.startPort].name}</dd></div><div><dt>자금</dt><dd>${chosen.money.toLocaleString()} 금</dd></div><div><dt>기함</dt><dd>${chosen.shipName}</dd></div></dl></div><div class="captain-stats">${bars}</div></section></div><div class="toolbar right">${this.e.button("파일 선택","files")}${this.e.button(`${chosen.name}로 시작`,`captain-start:${chosen.id}`,"primary")}</div>`,`center wide v17-select`)
  };
  game.activeFollowersV17=function(){const ids=(this.s.partyFollowerState?.active||this.s.mates||[]).map(x=>typeof x==="string"?x:x.id).filter(Boolean);return ids.filter(id=>id!==this.s.captainId).slice(0,3)};
  game.resetFollowersV17=function(){if(!this.s)return;const pos=this.s.interior||this.s.town;this.s.partyFollowerState=this.s.partyFollowerState||{active:[],history:[],spacing:.72};this.s.partyFollowerState.history=Array.from({length:90},()=>({x:pos.x,y:pos.y,dir:pos.dir||4}))};
  game.updateFollowersV17=function(dt){if(this.mode!=="interior"||!this.s?.interior)return;const p=this.s.partyFollowerState,h=p.history||(p.history=[]),pos=this.s.interior,last=h[0];if(!last||Math.hypot(last.x-pos.x,last.y-pos.y)>.08)h.unshift({x:pos.x,y:pos.y,dir:pos.dir});if(h.length>180)h.length=180;p.render=this.activeFollowersV17().map((id,i)=>{const target=h[Math.min(h.length-1,Math.round((i+1)*13*p.spacing))]||pos;return{id,x:target.x,y:target.y,dir:target.dir,anim:(this.playerAnim||0)-i*.13}})};
  game.updateInterior=function(dt){const r=oldUpdateInterior.call(this,dt);if(this.s&&this.mode==="interior")this.updateFollowersV17(dt);return r};
  game.enterInterior=function(id){const r=oldEnter.call(this,id);setTimeout(()=>{if(this.s&&this.mode==="interior")this.resetFollowersV17()},240);return r};
  game.leaveInterior=function(){const r=oldLeave.call(this);if(this.s?.partyFollowerState)this.s.partyFollowerState.history=[];return r};
  game.changeFloor=function(link){const r=oldChangeFloor.call(this,link);setTimeout(()=>{if(this.s&&this.mode==="interior")this.resetFollowersV17()},240);return r};
  game.executeV10InteriorAction=function(action){if(!action.startsWith("v17-inspect:"))return oldExecute.call(this,action);const id=action.slice(12),lines={scale:"추가 달린 저울 옆에 오늘의 기준 가격이 정갈하게 적혀 있다.",shelf:"항구의 기후에 맞춘 물건들이 출항 순서대로 놓여 있다.",supplies:"물통과 포대마다 배 이름과 적재 날짜가 쓰여 있다.",loom:"상인은 실의 굵기만 보고도 어느 항구 물건인지 알아본다.",crates:"상자 틈에서 소금과 오래된 밧줄 냄새가 난다.",fireplace:"젖은 외투를 말리는 선원들이 작은 불을 나누어 쬔다.",table:"탁자에는 반쯤 지운 항로와 누군가의 농담이 함께 남아 있다.",kitchen:"향신료와 생선 국물 냄새가 항해의 피로를 잠시 잊게 한다.",barrels:"술통에는 주인이 세어 둔 잔 수가 분필로 표시되어 있다.",bed:"창 가까운 침대에는 교대 항해사의 외투가 가지런히 걸려 있다.",treatment:"붕대, 식초, 말린 약초가 쓰임새별로 정리되어 있다.",wardrobe:"옷장 문 안쪽에는 오래 머문 손님들의 항구 표식이 새겨져 있다.",notice:"새 의뢰와 실종 선원의 이름이 같은 판에 나란히 붙어 있다.",mapTable:"바람 방향을 여러 색 잉크로 겹쳐 그린 작업 중인 해도다.",telescope:"황동 몸통에는 여러 세대 항해사가 남긴 작은 흠집이 있다.",desk:"봉인용 밀랍과 잉크가 아직 마르지 않은 문서가 놓여 있다.",hull:"용골의 곡선만으로도 이 배가 먼 바다를 견디도록 만든 것임을 알 수 있다.",crane:"도르래마다 하중을 기록한 작은 나무패가 달려 있다.",ropes:"굵기와 꼬임이 다른 밧줄들이 쓰임새별로 걸려 있다.",chest:"두꺼운 철띠와 서로 다른 세 개의 자물쇠가 금고를 지킨다."};return this.e.dialogue("조사",lines[id]||"오랫동안 이곳에서 쓰인 물건이다.",[{label:"돌아선다",action:"close"}])};
  game.showV16Ending=function(){if(!this.s?.captainId||this.s.captainId==="rian")return oldEnding.call(this);const c=captain(this.s.captainId),seen=this.s.crossEncounters?.seen?.length||0,ending={kemal:"라에나는 살아 돌아왔다. 카이르와 라에나는 항구마다 흩어진 실종자의 이름을 한 장부에 모았다.",ines:"세리아의 지도에는 안전한 길뿐 아니라 위험과 오차도 함께 기록되었다.",duarte:"로안은 전설 대신 실제 나라와 길을 안내한 사람들의 이름을 가지고 귀환했다.",matteo:"테오란은 위조 채무를 무효로 만들고 발견물의 출처를 밝히는 항해 박물관을 열었다.",anne:"에린은 국새 없는 명령을 공개하고 전투선보다 구조선이 먼저 움직이는 함대를 세웠다.",marieke:"메이라는 큰 부를 이루었고, 항구 공동 보험과 비상 곡물 창고를 남겼다."}[c.id];this.s.campaignSpecial.endingShown=true;this.save();this.e.window(`<small>항해 완료</small><h1>${HL.DATA.campaignsV16[this.s.campaignId].title}</h1><p>${ending}</p><div class="status-grid"><div class="status-cell"><small>다른 항해자와의 조우</small>${seen} / 5</div><div class="status-cell"><small>선장</small>${c.name}</div></div><div class="toolbar right">${this.e.button("항해 계속","close","primary")}${this.e.button("파일 선택","files")}</div>`,`center wide v16-ending`)};
})();
