window.HL=window.HL||{};
(function(){
  "use strict";
  const D=HL.DATA,R=D.classicMarketRulesV21,copy=v=>JSON.parse(JSON.stringify(v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const dayNumber=s=>(s.year||1526)*372+(s.month||1)*31+(s.day||1);
  const aggregateCargo=s=>{const total={};for(const ship of s.fleet||[])for(const[id,n]of Object.entries(ship.tradeCargo||{}))total[id]=(total[id]||0)+n;s.cargo={...(s.cargo||{}),...total};for(const g of D.goods)if(!total[g.id])s.cargo[g.id]=0;return s.cargo};
  function shipCargoCapacity(ship){return Math.max(0,(D.ships[ship.type]||D.ships.caravel).cargo)}
  function shipCargoUsed(ship){return Object.values(ship.tradeCargo||{}).reduce((a,b)=>a+(Number(b)||0),0)+(ship.food||0)+(ship.water||0)+(ship.lumber||0)+(ship.cannonballs||0)*.08}
  function migrateCargo(s){
    s.portWarehouses=s.portWarehouses||{};s.portWarehouses[s.currentPort]=s.portWarehouses[s.currentPort]||{};
    const already=s.fleet?.some(ship=>ship.tradeCargo&&Object.keys(ship.tradeCargo).length);for(const ship of s.fleet||[])ship.tradeCargo=ship.tradeCargo||{};if(already)return aggregateCargo(s);
    const flagship=s.fleet?.[0];if(!flagship)return;let free=Math.max(0,Math.floor(shipCargoCapacity(flagship)-shipCargoUsed(flagship)));
    for(const g of D.goods){const amount=Math.max(0,Math.floor(s.cargo?.[g.id]||0)),aboard=Math.min(amount,free);flagship.tradeCargo[g.id]=aboard;free-=aboard;const overflow=amount-aboard;if(overflow)s.portWarehouses[s.currentPort][g.id]=(s.portWarehouses[s.currentPort][g.id]||0)+overflow}
    aggregateCargo(s)
  }
  HL.migrateStateV21=function(prior){
    const s=copy(prior||HL.Game.freshState());s.version=21;s.graphicsVersion=21;s.v21={migratedAt:Date.now(),townArt:"layered-1920",floorArt:"120-independent",classicEconomy:true,...(s.v21||{})};
    s.classicMarket=s.classicMarket||{ports:{},lastDay:dayNumber(s),tradeLog:[],selectedShip:0,digitPlace:1};s.classicSailing=s.classicSailing||{continuousHeading:true,informationRestricted:true};s.openingWakeV21=s.openingWakeV21||{completed:true,reveal:1,stage:4,checkpoints:[]};migrateCargo(s);
    const map=D.townVisualSetsV21?.[s.currentPort];if(s.mode==="town"&&map&&!s.v21.positionConverted){s.town={x:map.spawn[0],y:map.spawn[1],dir:s.town?.dir??4};s.v21.positionConverted=true}
    if(prior?.version!==21&&s.mode==="interior"&&s.interior){const id=s.interior.buildingId||s.interior.id,b=D.buildingScenes[s.currentPort]?.[id],f=b?.floors[s.interior.floorId]||b?.floors[b?.entryFloor];if(f){Object.assign(s.interior,{id,buildingId:id,floorId:f.floorId,x:f.spawn[0],y:f.spawn[1],dir:s.interior.dir??0})}else{s.mode="town";s.interior=null}}
    return s
  };
  class ClassicMarketStateV21{
    constructor(state){this.s=state;this.ensure()}
    hasBookkeeper(){return this.s.captainId==="marieke"||(this.s.crew?.roles?.bookkeeper||0)>0||(this.s.mates||[]).some(m=>m.skills?.accounting||m.accounting)}
    ensure(){const m=this.s.classicMarket||(this.s.classicMarket={ports:{},lastDay:dayNumber(this.s),tradeLog:[],selectedShip:0,digitPlace:1}),now=dayNumber(this.s),days=Math.max(0,now-(m.lastDay||now));for(const port of Object.values(m.ports))for(const good of Object.values(port.goods||{})){good.index=1+(good.index-1)*Math.pow(1-R.dailyRecovery,days);good.supply+=(good.baseSupply-good.supply)*(1-Math.pow(.88,days))}m.lastDay=now;return m}
    port(id){const m=this.ensure(),p=D.ports[id],record=m.ports[id]||(m.ports[id]={economy:p.economy||40,support:0,invested:0,goods:{}});for(const g of D.goods)if(p.market[g.id]&&!record.goods[g.id])record.goods[g.id]={index:1,supply:24+((id.length*13+g.id.length*7)%28),baseSupply:24+((id.length*13+g.id.length*7)%28)};return record}
    season(goodId){const month=this.s.month||1;if(goodId==="grain"||goodId==="food")return month>=8&&month<=10?.90:1.08;if(goodId==="spice")return month>=5&&month<=9?1.12:.96;return 1}
    quote(portId,goodId,intent){const base=D.ports[portId].market[goodId]?.[intent==="buy"?0:1]||0,g=this.port(portId).goods[goodId],season=this.season(goodId),spread=intent==="buy"?1:.94;return Math.max(1,Math.floor(base*g.index*season*spread))}
    owned(goodId){return(this.s.fleet||[]).reduce((n,ship)=>n+(ship.tradeCargo?.[goodId]||0),0)}
    free(shipIndex){const ship=this.s.fleet[shipIndex]||this.s.fleet[0];return Math.max(0,Math.floor(shipCargoCapacity(ship)-shipCargoUsed(ship)))}
    preview(portId,goodId,intent,qty,shipIndex=0){const port=this.port(portId),g=port.goods[goodId],price=this.quote(portId,goodId,intent),owned=this.owned(goodId),max=intent==="buy"?Math.min(Math.floor(g.supply),this.free(shipIndex),Math.floor(this.s.money/price)):owned,quantity=clamp(Math.floor(qty)||1,1,Math.max(1,max)),average=this.s.averageCost?.[goodId]||0;return{price,owned,stock:Math.floor(g.supply),max,quantity,total:price*quantity,average,profit:intent==="sell"&&average?(price-average)*quantity:null,exact:this.hasBookkeeper()}}
    commit(portId,goodId,intent,qty,shipIndex=0){const v=this.preview(portId,goodId,intent,qty,shipIndex);if(!v.max)return{...v,error:intent==="buy"?"금화·재고 또는 선택 선박의 적재 공간이 부족합니다.":"판매할 화물이 없습니다."};const n=Math.min(v.quantity,v.max),g=this.port(portId).goods[goodId];if(intent==="buy"){const ship=this.s.fleet[shipIndex]||this.s.fleet[0],before=this.owned(goodId),old=this.s.averageCost?.[goodId]||0;ship.tradeCargo[goodId]=(ship.tradeCargo[goodId]||0)+n;this.s.money-=v.price*n;this.s.averageCost=this.s.averageCost||{};this.s.averageCost[goodId]=Math.floor((old*before+v.price*n)/(before+n));g.supply-=n;g.index=clamp(g.index+n*R.repeatBuyImpact,R.minIndex,R.maxIndex)}else{let left=n;for(const ship of this.s.fleet){const take=Math.min(left,ship.tradeCargo?.[goodId]||0);ship.tradeCargo[goodId]=(ship.tradeCargo[goodId]||0)-take;left-=take;if(!left)break}this.s.money+=v.price*n;g.supply+=n;g.index=clamp(g.index-n*R.repeatSellImpact,R.minIndex,R.maxIndex)}aggregateCargo(this.s);this.s.fame.trade=(this.s.fame.trade||0)+Math.max(1,Math.floor(v.total/20));this.s.classicMarket.tradeLog.unshift({day:dayNumber(this.s),portId,goodId,intent,quantity:n,price:v.price});this.s.classicMarket.tradeLog=this.s.classicMarket.tradeLog.slice(0,120);return{...v,quantity:n,total:v.price*n}}
    invest(portId,amount){const p=this.port(portId),units=Math.floor(amount/R.investmentUnit);if(units<1||this.s.money<units*R.investmentUnit)return false;this.s.money-=units*R.investmentUnit;p.invested+=units*R.investmentUnit;p.economy+=units*R.economyPerUnit;p.support=clamp(p.support+units*2,0,100);this.s.investments[portId]=(this.s.investments[portId]||0)+units*R.investmentUnit;this.s.marketUnlocks=this.s.marketUnlocks||{};this.s.marketUnlocks[portId]=this.s.marketUnlocks[portId]||{specialty:false,shipTier:0};if(p.invested>=R.specialtyThreshold)this.s.marketUnlocks[portId].specialty=true;if(p.invested>=R.specialtyThreshold*2)this.s.marketUnlocks[portId].shipTier=1;return true}
  }
  HL.ClassicMarketStateV21=ClassicMarketStateV21;HL.aggregateCargoV21=aggregateCargo;HL.shipCargoUsedV21=shipCargoUsed;

  const engine=HL.Engine.prototype;engine.v20SlotKey=i=>`horizon-ledger-v20-slot-${i}`;engine.slotKey=i=>`horizon-ledger-v21-slot-${i}`;
  engine.loadSlot=function(i){try{const s=JSON.parse(localStorage.getItem(this.slotKey(i)));return s?.version===21?s:null}catch{return null}};
  engine.migrateOld=function(i){if(this.loadSlot(i))return;try{const keys=[this.v20SlotKey(i),`horizon-ledger-v19-slot-${i}`,`horizon-ledger-v18-slot-${i}`],old=keys.map(k=>JSON.parse(localStorage.getItem(k)||"null")).find(Boolean);if(old)this.saveSlot(i,HL.migrateStateV21(old))}catch(error){console.warn("V21 저장 변환 실패",error)}};engine.deleteSlot=i=>localStorage.removeItem(engine.slotKey(i));
  const game=HL.Game.prototype,oldFresh=HL.Game.freshState,oldEnsure=game.ensureExpansion,oldNew=game.newGame,oldResume=game.resume,oldUpdateInterior=game.updateInterior,oldExecute=game.executeV10InteriorAction,oldDispatch=game.dispatchAction,oldShipyard=game.shipyardMenu;
  HL.Game.freshState=function(){const s=oldFresh.call(this);s.version=21;s.graphicsVersion=21;s.openingWakeV21=null;s.classicMarket={ports:{},lastDay:dayNumber(s),tradeLog:[],selectedShip:0,digitPlace:1};s.classicSailing={continuousHeading:true,informationRestricted:true};return s};
  game.ensureExpansion=function(){oldEnsure.call(this);if(this.s){this.s.version=21;this.s.graphicsVersion=21;this.s.v21={townArt:"layered-1920",floorArt:"120-independent",classicEconomy:true,...(this.s.v21||{})};this.s.classicMarket=this.s.classicMarket||{ports:{},lastDay:dayNumber(this.s),tradeLog:[],selectedShip:0,digitPlace:1};this.s.classicSailing=this.s.classicSailing||{continuousHeading:true,informationRestricted:true};migrateCargo(this.s)}};
  game.beginWakeOpeningV21=function(id){const defs=D.openingWakeDefinitionsV21,port=defs.captainPort[id],floor=D.buildingScenes[port].lodge.floors["2f"],call=defs.calls[id];this.mode="interior";this.s.mode="interior";this.s.currentPort=port;this.s.openingWakeV21={captainId:id,reveal:0,stage:0,completed:false,heardCall:false,checkpoints:[{id:"wake",at:Date.now()}]};this.s.openingV19={captainId:id,step:0,completed:false,startedAt:Date.now(),log:[]};this.s.interior={id:"lodge",buildingId:"lodge",floorId:"2f",x:5.5,y:6.8,dir:4};this.s.quest={stage:0,title:"평범했던 아침",objective:`${call.caller}에게 말을 걸어 오늘 해야 할 일을 확인하라.`};this.lastSafe={x:5.5,y:6.8};this.playerVelocity={x:0,y:0};this.e.close();this.resetFollowersV19();this.save();this.e.playMusic("port")};
  game.newGame=function(id=this.e.selectedCaptain||"kemal"){oldNew.call(this,id);this.s=HL.migrateStateV21(this.s);this.s.slot=this.e.selectedSlot;this.beginWakeOpeningV21(id)};
  game.resume=function(i){const state=this.e.loadSlot(i);if(!state)return this.showFiles();this.s=HL.migrateStateV21(state);this.s.slot=i;this.mode=this.s.mode||"town";this.ensureExpansion();this.spawnTownNpcs();this.e.close();this.ensureSafePosition();this.resetFollowersV19();this.e.playMusic(this.mode==="sea"?"sea":"port")};
  game.updateInterior=function(dt){if(this.s?.openingWakeV21&&!this.s.openingWakeV21.completed)this.s.openingWakeV21.reveal=clamp(this.s.openingWakeV21.reveal+dt*.55,0,1);return oldUpdateInterior.call(this,dt)};
  game.checkpointWakeV21=function(id){const w=this.s.openingWakeV21;w.checkpoints.push({id,at:Date.now(),port:this.s.currentPort,floor:this.s.interior?.floorId});w.checkpoints=w.checkpoints.slice(-8);this.save()};
  game.handleWakeV21=function(action){const w=this.s.openingWakeV21,call=D.openingWakeDefinitionsV21.calls[this.s.captainId];if(action==="bed")return this.e.dialogue(this.s.captainName||"선장","익숙한 아침이다. 하지만 문밖의 목소리가 평소보다 다급하다.",[{label:"일어난다",action:"close",primary:true}]);if(action==="caller"){if(w.heardCall)return this.e.dialogue(call.caller,this.s.quest.objective,[{label:"알겠습니다",action:"close",primary:true}]);w.heardCall=true;w.stage=Math.max(w.stage||0,1);this.s.quest.objective=call.task;this.checkpointWakeV21("first-call");return this.e.dialogue(call.caller,call.wake+"\n\n"+call.task,[{label:"곧 내려가겠다",action:"close",primary:true}])}}
  game.handleOpeningV21=function(step){const w=this.s.openingWakeV21,call=D.openingWakeDefinitionsV21.calls[this.s.captainId];if(!w?.heardCall)return this.e.toast(`먼저 ${call.caller}의 부름을 확인하십시오.`);const order={work:1,news:2,consult:3,prepare:4},need=order[step];if(!need)return;if(need>(w.completedSteps?.length||0)+1)return this.e.toast("먼저 앞선 업무와 대화를 마쳐야 합니다.");w.completedSteps=w.completedSteps||[];if(w.completedSteps.includes(step))return this.e.toast("이미 마친 일입니다. 항해 일지의 다음 목적을 확인하십시오.");w.completedSteps.push(step);w.stage=Math.max(w.stage,need);const text={work:"평소 하던 일을 직접 마치자 장부의 작은 어긋남이 눈에 들어온다.",news:"전해진 물건과 증언은 우연이라 보기 어려울 만큼 구체적이다.",consult:"가족과 동료도 위험을 숨기지 않는다. 그래도 직접 확인하지 않으면 평범한 생활로 돌아갈 수 없다.",prepare:"선원 명부와 보급표를 확인했다. 이제 항만에서 배를 인수하고 출항할 수 있다."}[step];if(step==="work")this.checkpointWakeV21("daily-work");if(step==="prepare"){w.completed=true;this.s.flags.shipGranted=true;this.checkpointWakeV21("departure-ready")}this.s.quest.objective=step==="prepare"?"항만에서 선원과 보급을 확인한 뒤 첫 목적지로 출항하라.":call.task;this.save();return this.e.dialogue(step==="news"?call.caller:(this.s.captainName||"선장"),text,[{label:step==="prepare"?"출항 준비를 마친다":"계속",action:"close",primary:true}])};
  game.executeV10InteriorAction=function(action){if(action.startsWith("v21-wake:"))return this.handleWakeV21(action.slice(9));if(action.startsWith("v21-opening:"))return this.handleOpeningV21(action.slice(12));if(action.startsWith("v21-inspect:"))return this.e.dialogue("조사",`오랫동안 쓰인 ${action.slice(12)}에서 이 건물의 일과 생활 방식이 드러난다.`,[{label:"돌아선다",action:"close"}]);if(action==="facility:bank")return this.bankMenu?.();if(action==="facility:estate"||action==="facility:home")return this.propertyMenu?.();return oldExecute.call(this,action)};

  game.renderV21Trade=function(){const model=new ClassicMarketStateV21(this.s),p=D.ports[this.s.currentPort],t=this.s.tradeState||(this.s.tradeState={selected:Object.keys(p.market)[0],intent:"buy",quantity:1}),goods=D.goods.filter(g=>p.market[g.id]),shipIndex=clamp(this.s.classicMarket.selectedShip||0,0,this.s.fleet.length-1);if(!p.market[t.selected])t.selected=goods[0].id;const v=model.preview(this.s.currentPort,t.selected,t.intent,t.quantity,shipIndex),rows=goods.map(g=>{const x=model.preview(this.s.currentPort,g.id,t.intent,1,shipIndex),price=x.exact?`${x.price}금`:x.price>(p.market[g.id][t.intent==="buy"?0:1]||0)?"비쌈":"보통";return`<button class="trade-item ${g.id===t.selected?"selected":""}" data-action="v21-trade-select:${g.id}"><strong>${g.name}</strong><span>${t.intent==="buy"?"매입":"매각"} ${price}</span><small>선내 ${x.owned}${x.exact?` · 시장 ${x.stock}`:""}</small></button>`}).join("");const detail=v.exact?`<span>단가</span><b>${v.price}금</b><span>시장 재고</span><b>${v.stock}</b><span>평균 매입가</span><b>${v.average||"기록 없음"}</b><span>예상 손익</span><b>${v.profit==null?"기록 없음":`${v.profit>=0?"+":""}${v.profit}금`}</b>`:`<p>회계 담당자가 없어 정확한 시세율, 평균 매입가와 예상 손익을 알 수 없습니다.</p>`;this.e.window(`<div class="v13-shop-head"><div><small>${p.name}</small><h1>교역소</h1></div><div><b>금화 ${this.s.money}</b><span>${this.s.fleet[shipIndex].name} 여유 ${model.free(shipIndex)}</span></div></div><div class="v13-trade"><section class="trade-list">${rows}</section><section class="trade-detail"><div class="trade-mode">${this.e.button("구입","v21-trade-mode:buy",t.intent==="buy"?"primary":"")}${this.e.button("판매","v21-trade-mode:sell",t.intent==="sell"?"primary":"")}</div><h2>${D.goods.find(g=>g.id===t.selected).name}</h2><div class="trade-stat">${detail}</div><div class="quantity"><button data-action="v21-qty:-100">-100</button><button data-action="v21-qty:-10">-10</button><button data-action="v21-qty:-1">-1</button><b>${v.quantity}개</b><button data-action="v21-qty:1">+1</button><button data-action="v21-qty:10">+10</button><button data-action="v21-qty:100">+100</button></div><p>${v.exact?`합계 ${v.total}금`:"합계는 확정 단계에서 확인합니다."}</p><div class="toolbar">${this.e.button("최대","v21-qty:max")}${this.e.button("거래 확정","v21-trade-commit","primary")}${this.e.button("1,000 투자","v21-invest")}${this.e.button("끝내기","close")}</div></section></div>`,"center wide v13-shop")};
  game.marketMenu=function(){this.renderV21Trade()};
  game.shipyardMenu=function(){const result=oldShipyard.call(this),panel=this.e.overlay.querySelector?.(".v13-shipyard-window");if(panel)panel.insertAdjacentHTML("beforeend",`<div class="toolbar right">${this.e.button("조선소 1,000 투자","v21-shipyard-invest")}</div>`);return result};
  game.dispatchAction=function(action,button){const model=()=>new ClassicMarketStateV21(this.s),t=()=>this.s.tradeState;if(action.startsWith("v21-trade-select:")){t().selected=action.slice(17);t().quantity=1;return this.renderV21Trade()}if(action.startsWith("v21-trade-mode:")){t().intent=action.slice("v21-trade-mode:".length);t().quantity=1;return this.renderV21Trade()}if(action.startsWith("v21-qty:")){const q=action.slice(8);if(q==="max")t().quantity=model().preview(this.s.currentPort,t().selected,t().intent,1,this.s.classicMarket.selectedShip).max||1;else t().quantity=Math.max(1,t().quantity+(+q||0));return this.renderV21Trade()}if(action==="v21-trade-commit"){const r=model().commit(this.s.currentPort,t().selected,t().intent,t().quantity,this.s.classicMarket.selectedShip);if(r.error)return this.e.toast(r.error);this.e.sfx("coin_trade");this.save();return this.renderV21Trade()}if(action==="v21-invest"){if(!model().invest(this.s.currentPort,1000))return this.e.toast("투자하려면 1,000금이 필요합니다.");this.save();return this.renderV21Trade()}if(action==="v21-shipyard-invest"){if(this.s.money<1000)return this.e.toast("조선소 투자에는 1,000금이 필요합니다.");this.s.money-=1000;this.s.shipyardInvestments=this.s.shipyardInvestments||{};const total=this.s.shipyardInvestments[this.s.currentPort]=(this.s.shipyardInvestments[this.s.currentPort]||0)+1000;this.s.shipyardUnlocks=this.s.shipyardUnlocks||{};this.s.shipyardUnlocks[this.s.currentPort]=total>=6000?2:total>=3000?1:0;this.save();return this.shipyardMenu()}return oldDispatch.call(this,action,button)};

  const sim=HL.SeaSimulation.prototype;sim.shipSpeed=function(state,ship,index=0){this.ensureShip(ship,index===0?state.crew?.assignment:null);const spec=D.ships[ship.type]||D.ships.caravel,round=v=>Math.floor(v*1000)/1000,heading=state.sea.heading,wind=state.sea.wind,diff=Math.min((heading-wind+8)%8,(wind-heading+8)%8),sail=ship.equipment?.sail,lateen=sail==="lateen",square=sail==="topsail",windFactor=diff<=1?(square?1.34:lateen?1.08:1.25):diff<=3?(lateen?1.10:1):(lateen?.80:.46);let speed=round(spec.power/6);speed=round(speed*windFactor);speed=round(speed*(.72+(spec.handling||5)/8*.28));const ratio=this.cargoLoad(state,ship,index)/Math.max(1,spec.cargo),loadFactor=ratio<=.30?1:clamp(1-(ratio-.30)*.46,.42,1);speed=round(speed*loadFactor);const min=Math.max(1,spec.crewMin),nav=ship.voyage.assignment.navigation||0,crewFactor=clamp(nav/min,.35,1);speed=round(speed*crewFactor);const condition=clamp(Math.min(ship.hull/(spec.hull||ship.hull),ship.sailCondition/100,ship.voyage.rudder/100),.2,1);speed=round(speed*condition);speed=round(speed*(1+clamp((state.stats?.navigation||0)/500,0,.20)));return Math.max(.14,round(speed*D.classicSailingRulesV21.speedScale))};
  const oldCargoLoad=sim.cargoLoad;sim.cargoLoad=function(state,ship,index){if(ship.tradeCargo)return shipCargoUsed(ship);return oldCargoLoad.call(this,state,ship,index)};
})();
