window.HL=window.HL||{};
(function(){
  const art=HL.Art.prototype;
  art.ensureV5Images=function(){
    if(this.v5Ready)return;this.v5Ready=true;this.chunkCache=new HL.SeaChunkCache();for(const[id,sheet]of Object.entries(HL.DATA.spriteSheets)){this.images[`${id}Town`]=new Image();this.images[`${id}Town`].src=sheet.town.src;this.images[`${id}Interior`]=new Image();this.images[`${id}Interior`].src=sheet.interior.src}this.images.worldOverview=new Image();this.images.worldOverview.src=HL.DATA.worldChunks.overview;this.images.oceanV6=new Image();this.images.oceanV6.src="../Assets/Resources/Sprites/Game/SeaV6/ocean_depth_source_v6.png";this.images.terrainV6=new Image();this.images.terrainV6.src="../Assets/Resources/Sprites/Game/SeaV6/terrain_climate_source_v6.png";this.seaShipVisual=new HL.SeaShipVisual()
  };
  art.spriteFrame=function(dir,anim,moving,interior,sheetId="rian"){
    const meta=HL.DATA.spriteSheets[sheetId]||HL.DATA.spriteSheets.rian,mode=interior?meta.interior:meta.town,sequence=moving?meta.walkFrames:meta.idleFrames,fps=moving?meta.fps.walk:meta.fps.idle,index=sequence[Math.floor(anim*fps)%sequence.length];return mode.frames[(dir+8)%8][index]
  };
  art.person=function(e,x,y,dir=4,hero=false,anim=0,scale=1,appearanceId="citizen",moving=false){
    this.ensureV5Images();const c=e.ctx,interior=scale>1.2,sheetId=HL.DATA.spriteSheets[appearanceId]?appearanceId:"rian",img=this.images[`${sheetId}${interior?"Interior":"Town"}`],frame=this.spriteFrame(dir,anim,moving,interior,sheetId),appearance=HL.DATA.appearances[appearanceId]||HL.DATA.appearances.rian,w=frame.w,h=frame.h,bob=moving?Math.round(Math.sin(anim*Math.PI*2)):0;
    c.fillStyle="rgba(2,11,14,.34)";c.beginPath();c.ellipse(Math.round(x),Math.round(y+3),interior?18:14,interior?7:5,0,0,Math.PI*2);c.fill();if(!img.complete||!img.naturalWidth){c.fillStyle=appearance.palette?.[0]||"#245f77";c.fillRect(x-w*.2,y-h*.58,w*.4,h*.48);return}
    const dx=Math.round(x-w/2),dy=Math.round(y-h+4+bob);if(hero||sheetId!=="rian"||appearanceId==="rian"){c.drawImage(img,frame.x,frame.y,w,h,dx,dy,w,h);return}
    if(!this.spriteCanvasV5&&typeof document!=="undefined")this.spriteCanvasV5=document.createElement("canvas");const buffer=this.spriteCanvasV5;if(!buffer){c.drawImage(img,frame.x,frame.y,w,h,dx,dy,w,h);return}buffer.width=w;buffer.height=h;const b=buffer.getContext("2d");b.imageSmoothingEnabled=false;b.clearRect(0,0,w,h);b.drawImage(img,frame.x,frame.y,w,h,0,0,w,h);b.globalCompositeOperation="source-atop";b.fillStyle=(appearance.palette?.[0]||"#73513d")+"66";b.fillRect(0,Math.floor(h*.22),w,Math.floor(h*.64));b.globalCompositeOperation="source-over";c.drawImage(buffer,dx,dy);const hash=this.hash(appearanceId);c.fillStyle=appearance.palette?.[2]||"#d9ad59";if(appearance.hat!=="none")c.fillRect(dx+Math.floor(w*.3),dy+Math.floor(h*.12),Math.floor(w*.4),interior?4:3);if(appearance.accessory&&appearance.accessory!=="none")c.fillRect(dx+(hash%2?Math.floor(w*.77):Math.floor(w*.18)),dy+Math.floor(h*.54),interior?5:4,interior?13:10)
  };

  art.worldPoint=function(lon,lat,centerLon,centerLat,scale){let dx=lon-centerLon;if(dx>180)dx-=360;if(dx<-180)dx+=360;return[480+dx*(8192/360)*scale,276-(lat-centerLat)*(4096/180)*scale]};
  art.drawWorldChunks=function(c,lon,lat,scale){
    this.ensureV5Images();this.chunkCache.preload(lon,lat);const data=HL.DATA.worldChunks,cx=(lon+180)/360*data.width,cy=(90-lat)/180*data.height,viewW=960/scale,viewH=540/scale,startCol=Math.floor((cx-viewW/2)/data.tileSize),endCol=Math.floor((cx+viewW/2)/data.tileSize),startRow=Math.max(0,Math.floor((cy-viewH/2)/data.tileSize)),endRow=Math.min(data.rows-1,Math.floor((cy+viewH/2)/data.tileSize));let drew=false;
    for(let row=startRow;row<=endRow;row++)for(let col=startCol;col<=endCol;col++){const image=this.chunkCache.get(row,col),dx=Math.round(480+(col*data.tileSize-cx)*scale),dy=Math.round(270+(row*data.tileSize-cy)*scale),size=Math.ceil(data.tileSize*scale)+1;if(image?.complete&&image.naturalWidth){c.drawImage(image,0,0,data.tileSize,data.tileSize,dx,dy,size,size);drew=true}}
    return drew
  };
  art.drawSeaMotion=function(game,t,scale,centerLon=game.s.sea.lon,centerLat=game.s.sea.lat){
    const c=game.e.ctx;for(let y=76;y<468;y+=18)for(let x=-20;x<980;x+=44){const lon=centerLon+(x-480)/(8192/360*scale),lat=centerLat-(y-276)/(4096/180*scale);if(game.seaGrid.blocked(lon,lat,.02))continue;const drift=Math.round(Math.sin(x*.021+y*.017+t*1.8)*5),depth=game.seaGrid.depth(lon,lat);c.strokeStyle=depth<35?"rgba(229,242,196,.34)":y%36?"rgba(104,211,218,.18)":"rgba(218,239,213,.24)";c.beginPath();c.moveTo(x+drift,y);c.lineTo(x+14+drift,y-2);c.lineTo(x+30+drift,y);c.stroke()}
  };
  art.landPath=function(c,game,scale,centerLon=game.s.sea.lon,centerLat=game.s.sea.lat){for(const poly of game.navigation.land){const nearby=poly.some(([lon])=>{let dx=Math.abs(lon-centerLon);if(dx>180)dx=360-dx;return dx<34/scale});if(!nearby)continue;let started=false;for(const[lon,lat]of poly){const[x,y]=this.worldPoint(lon,lat,centerLon,centerLat,scale);if(!started){c.moveTo(x,y);started=true}else c.lineTo(x,y)}c.closePath()}};
  art.drawOceanV6=function(c,t,centerLon,centerLat){const image=this.images.oceanV6;if(image?.complete&&image.naturalWidth){const sw=image.naturalWidth,sh=image.naturalHeight/4;c.drawImage(image,0,sh,sw,sh,0,0,960,540)}else{c.fillStyle="#07517a";c.fillRect(0,0,960,540)}};
  art.drawLandV6=function(c,game,scale,centerLon,centerLat){c.save();c.beginPath();this.landPath(c,game,scale,centerLon,centerLat);c.clip();c.fillStyle=Math.abs(centerLat)>58?"#aebbb3":Math.abs(centerLat)<20?"#406c42":"#6d7545";c.fillRect(0,0,960,540);const image=this.images.terrainV6,index=Math.abs(centerLat)>58?3:Math.abs(centerLat)<18?(centerLon>-20&&centerLon<65?1:2):0;if(image?.complete&&image.naturalWidth){const sw=image.naturalWidth/2,sh=image.naturalHeight/2,sx=(index%2)*sw,sy=Math.floor(index/2)*sh;c.drawImage(image,sx,sy,sw,sh,0,0,960,540)}c.restore()};
  art.drawWake=function(c,x,y,dir,t,scale=1,color="rgba(226,244,223,.62)"){c.save();c.translate(x,y);c.rotate(dir*Math.PI/4);c.strokeStyle=color;c.lineWidth=2;c.setLineDash([9,6]);for(const side of[-1,1]){c.beginPath();c.moveTo(side*7,24);c.quadraticCurveTo(side*(13+Math.sin(t*2)*2),48,side*20,76);c.stroke()}c.setLineDash([]);c.restore()};
  art.worldSea=function(game){
    this.ensureV5Images();const e=game.e,c=e.ctx,s=game.s,t=performance.now()/1000,zoom=Math.max(.82,Math.min(1.65,s.sea.zoom||1.12)),dir=HL.DATA.directions[s.sea.heading],look=4.1/zoom,centerLon=s.sea.lon+dir[0]*look/Math.max(.3,Math.cos(s.sea.lat*Math.PI/180)),centerLat=s.sea.lat-dir[1]*look;e.clear("#062b4d");this.drawOceanV6(c,t,centerLon,centerLat);
    for(const[width,color]of[[36,"rgba(14,105,145,.62)"],[25,"rgba(23,151,170,.7)"],[14,"rgba(68,190,181,.76)"],[6,"rgba(218,208,132,.9)"]]){c.beginPath();this.landPath(c,game,zoom,centerLon,centerLat);c.strokeStyle=color;c.lineWidth=width;c.stroke()}this.drawLandV6(c,game,zoom,centerLon,centerLat);c.beginPath();this.landPath(c,game,zoom,centerLon,centerLat);c.strokeStyle="#e8d18a";c.lineWidth=2;c.stroke();c.lineWidth=1;this.drawSeaMotion(game,t,zoom,centerLon,centerLat);
    for(const[rx,ry,rr]of game.navigation.reefs){const[x,y]=this.worldPoint(rx,ry,centerLon,centerLat,zoom);if(x<-50||x>1010||y<60||y>500)continue;c.strokeStyle="rgba(190,239,210,.48)";c.setLineDash([4,5]);c.beginPath();c.arc(x,y,Math.max(10,rr*11*zoom),0,Math.PI*2);c.stroke();c.setLineDash([])}
    for(const[id,p]of Object.entries(HL.DATA.ports)){if(p.tier>s.worldPhase)continue;const entrance=game.seaGrid.portApproach(p).spawn,[x,y]=this.worldPoint(entrance[0],entrance[1],centerLon,centerLat,zoom);if(x<-30||x>990||y<65||y>490)continue;const known=s.knownPorts.includes(id);c.fillStyle=known?"#f0c45b":"#8ed3c5";c.fillRect(Math.round(x-4),Math.round(y-4),known?9:6,known?9:6);if(known)e.text(p.name,x,y-11,"#fff2bd","center",12)}
    const route=s.sea.autoTarget?game.routeGuide.info(s,s.sea.autoTarget):null,player=this.worldPoint(s.sea.lon,s.sea.lat,centerLon,centerLat,zoom);if(route){const[nextX,nextY]=this.worldPoint(route.next[0],route.next[1],centerLon,centerLat,zoom);c.setLineDash([9,7]);c.strokeStyle="#f0c45b";c.lineWidth=2;c.beginPath();c.moveTo(player[0],player[1]);c.lineTo(nextX,nextY);c.stroke();c.setLineDash([]);c.lineWidth=1;e.text(`추천 ${HL.DATA.directionNames[route.heading]}`,player[0]+42,player[1]-42,"#ffe29a","left",12)}
    const visible=game.fleetSystem?.visible(s)||[],detect=game.fleetSystem?.detectionRange(s)||2;for(const fleet of visible){const[x,y]=this.worldPoint(fleet.lon,fleet.lat,centerLon,centerLat,zoom);if(x<0||x>960||y<70||y>478)continue;const distance=game.fleetSystem.distance(fleet,s.sea),silhouette=distance>detect;this.drawWake(c,x,y,fleet.heading,t,.7,silhouette?"rgba(210,224,216,.18)":"rgba(214,232,218,.45)");if(silhouette){c.fillStyle="rgba(19,25,28,.72)";c.fillRect(x-5,y-11,10,20)}else{this.seaShipVisual.draw(e,fleet.shipType||"brig",x,y,fleet.heading,100,t,.64);e.text(fleet.name,x,y-43,fleet.kind==="story"?"#ffcf73":"#ffd6b1","center",11);if(fleet.ai==="chase")e.text("!",x+24,y-20,"#ff6f55","center",18)}}
    this.drawWake(c,player[0],player[1]+12,s.sea.heading,t,1);if(!this.seaShipVisual.draw(e,s.fleet[0].type,player[0],player[1],s.sea.heading,s.fleet[0].hull,t,.9))this.ship(e,player[0],player[1],s.sea.heading,s.fleet[0].type,1.2);
    const warning=game.seaGrid.forecast(s.sea.lon,s.sea.lat,s.sea.heading),eq=s.fleet[0].equipment||{};if(eq.figurehead&&eq.figurehead!=="none"){const d=HL.DATA.directions[s.sea.heading];c.fillStyle=eq.figurehead==="dragon"?"#e5ae45":"#8ed0c5";c.fillRect(Math.round(player[0]+d[0]*48-3),Math.round(player[1]+d[1]*48-3),7,7)}if(warning.danger){c.fillStyle="rgba(111,31,24,.92)";c.fillRect(350,84,260,32);c.strokeStyle="#ffba63";c.strokeRect(351,85,258,30);e.text(`주의 · 전방 ${warning.kind} ${warning.distance.toFixed(1)}° · ${HL.DATA.directionNames[warning.safeHeading]} 권장`,480,106,"#ffe0a1","center",14)}
    if(s.sea.weather==="안개"){c.fillStyle="rgba(218,227,219,.34)";c.fillRect(0,70,960,398)}if(s.sea.weather==="폭풍"){c.fillStyle="rgba(3,11,27,.5)";c.fillRect(0,70,960,398);for(let i=0;i<11;i++){c.strokeStyle="rgba(194,221,229,.4)";c.beginPath();c.moveTo((i*97+t*110)%1060,70);c.lineTo((i*97+t*110)%1060-85,330);c.stroke()}}
    c.fillStyle="rgba(2,14,23,.93)";c.fillRect(0,468,960,72);const task=game.campaignSystem?.currentTask(s),rec=game.campaignSystem?.recommendation(s,task),routeText=route?`${HL.DATA.ports[route.targetId].name} ${Math.round(route.distance)}° · 다음 ${HL.DATA.directionNames[route.heading]}${route.supply?` · 보급 ${HL.DATA.ports[route.supply].name}`:""}`:task?`목표 ${task.title} · ${rec.distance}° · 예상 ${rec.days}일`:"항로 미설정";e.text(`해류·항로  ${s.sea.weather} | 풍 ${HL.DATA.directionNames[s.sea.wind]} | 해류 ${HL.DATA.directionNames[s.sea.current]} | 수심 ${s.sea.depth}m | 해적 ${visible.length}척`,20,496,"#e4dfb0","left",14);e.text(routeText,20,523,"#f0bd55","left",13);for(const[label,y]of[["관찰",379],["수색",414],["교전",449]]){c.fillStyle="rgba(7,29,38,.93)";c.fillRect(835,y,100,28);c.strokeStyle="#b2883f";c.strokeRect(835.5,y+.5,99,27);e.text(label,885,y+19,"#f5dfaa","center",13)}
  };
  art.worldMap=function(game){
    this.ensureV5Images();const e=game.e,c=e.ctx,s=game.s;e.clear("#06131c");if(this.images.worldOverview.complete&&this.images.worldOverview.naturalWidth)c.drawImage(this.images.worldOverview,25,55,910,420);else{c.fillStyle="#0b3e58";c.fillRect(25,55,910,420)}c.fillStyle="rgba(3,14,22,.2)";c.fillRect(25,55,910,420);const project=(lon,lat)=>[25+(lon+180)/360*910,55+(90-lat)/180*420];for(const id of s.knownPorts){const p=HL.DATA.ports[id];if(!p)continue;const[x,y]=project(p.lon,p.lat);c.fillStyle="#f1c65f";c.fillRect(x-2,y-2,5,5)}for(const fleet of game.fleetSystem?.visible(s)||[]){const[x,y]=project(fleet.lon,fleet.lat);e.text("◆",x,y,fleet.kind==="story"?"#ff6f55":"#1b1820","center",11)}const task=game.campaignSystem?.currentTask(s);if(task){let marker=task.marker;if(!marker&&task.port){const p=HL.DATA.ports[task.port];marker=p?[p.lon,p.lat]:null}if(marker){const[x,y]=project(marker[0],marker[1]),pulse=7+Math.sin(performance.now()/180)*2;c.strokeStyle="#fff0a6";c.lineWidth=2;c.beginPath();c.arc(x,y,pulse,0,Math.PI*2);c.stroke();e.text(task.title,x,y-12,"#fff4c8","center",12);c.lineWidth=1}}const[x,y]=project(s.sea.lon,s.sea.lat),route=s.sea.autoTarget?game.routeGuide.info(s,s.sea.autoTarget):null;if(route){c.strokeStyle="#f3cd64";c.lineWidth=2;c.setLineDash([6,5]);c.beginPath();c.moveTo(x,y);for(const point of route.route){const[rx,ry]=project(point[0],point[1]);c.lineTo(rx,ry)}c.stroke();c.setLineDash([]);c.lineWidth=1;if(route.supply){const p=HL.DATA.ports[route.supply],[sx,sy]=project(p.lon,p.lat);c.strokeStyle="#8ee0c1";c.strokeRect(sx-5,sy-5,10,10);e.text(`보급 ${p.name}`,sx,sy+17,"#b8f1d5","center",10)}}const heading=HL.DATA.directions[s.sea.heading],hx=x+heading[0]*22,hy=y+heading[1]*22;c.strokeStyle="#fff";c.beginPath();c.moveTo(x,y);c.lineTo(hx,hy);c.stroke();c.fillStyle="#fff";c.beginPath();c.arc(x,y,5,0,Math.PI*2);c.fill();e.text("세계 해도",32,38,"#e9bd59","left",24);e.text(`발견 항구 ${s.knownPorts.length}/120 · 캠페인 ${game.campaignSystem.chapter(s).title}`,928,38,"#e7e2bd","right",13);e.text(route?`항로 ${HL.DATA.ports[route.targetId].name} · 추천 ${HL.DATA.directionNames[route.heading]} · 직접 조타`:"M / Esc 닫기 · J 항해 일지",928,515,"#e9bd59","right",14)
  };
})();
