window.HL=window.HL||{};
(function(){
  HL.DATA.version=4;

  const goodRows=[
    ["glass","유리 공예품",78,"공예"],["wine","포도주",52,"식품"],["timber","목재",64,"원료"],["salt","소금",38,"식품"],["wool","양모",48,"직물"],["spice","혼합 향신료",180,"향신료"],
    ["grain","곡물",24,"식품"],["olive_oil","올리브유",55,"식품"],["cheese","치즈",44,"식품"],["fish","건어물",32,"식품"],["sugar","설탕",92,"식품"],["coffee","커피",120,"식품"],
    ["tea","차",145,"식품"],["cocoa","카카오",135,"식품"],["rum","럼주",74,"식품"],["dates","대추야자",43,"식품"],["rice","쌀",36,"식품"],["citrus","감귤",46,"식품"],
    ["linen","아마포",62,"직물"],["cotton","면직물",78,"직물"],["silk","비단",210,"직물"],["velvet","벨벳",190,"직물"],["carpet","융단",160,"직물"],["dye","염료",102,"직물"],
    ["iron","철광석",58,"광물"],["copper","구리",88,"광물"],["tin","주석",76,"광물"],["silver","은",185,"광물"],["gold","금",260,"광물"],["coal","석탄",54,"광물"],
    ["marble","대리석",84,"광물"],["ivory","상아",175,"원료"],["ebony","흑단",150,"원료"],["rubber","수지",96,"원료"],["hides","가죽",66,"원료"],["paper","종이",72,"공예"],
    ["books","서적",110,"공예"],["porcelain","도자기",170,"공예"],["jewelry","보석 세공",245,"공예"],["clocks","시계",220,"공예"],["instruments","항해 기구",155,"공예"],["weapons","무기",130,"무기"],
    ["cannon","대포",240,"무기"],["gunpowder","화약",115,"무기"],["armor","갑옷",180,"무기"],["pepper","후추",170,"향신료"],["cinnamon","계피",165,"향신료"],["cloves","정향",205,"향신료"],
    ["nutmeg","육두구",215,"향신료"],["saffron","사프란",230,"향신료"],["ginger","생강",105,"향신료"],["medicine","의약품",125,"약재"],["lime_juice","라임 주스",68,"약재"],["aloe","알로에",82,"약재"],
    ["quinine","해열 수피",150,"약재"],["incense","향료",145,"향신료"],["pearls","진주",235,"공예"],["coral","산호",155,"공예"],["furs","모피",115,"원료"],["horses","말",135,"가축"]
  ];
  HL.DATA.goods=goodRows.map(([id,name,base,category])=>({id,name,base,category}));

  HL.DATA.nations={
    portugal:{name:"포르투갈 왕국",color:"#2f7c5e"},spain:{name:"카스티야-아라곤 왕국",color:"#bd8a35"},england:{name:"잉글랜드 왕국",color:"#8c3e3e"},
    france:{name:"프랑스 왕국",color:"#3e5f91"},habsburg:{name:"합스부르크령",color:"#8a5b8e"},italy:{name:"이탈리아 도시국가",color:"#628259"},
    ottoman:{name:"오스만 제국",color:"#8b403d"},maghreb:{name:"마그레브 제후국",color:"#54765f"},africa:{name:"아프리카 해안국",color:"#8b6f43"},
    arabia:{name:"아라비아 항구동맹",color:"#917947"},india:{name:"인도양 왕국",color:"#9b5d46"},asia:{name:"동방 해상국",color:"#477b7d"},
    japan:{name:"일본 제후령",color:"#775063"},americas:{name:"신대륙 항구권",color:"#6d7950"},neutral:{name:"중립 항구",color:"#777b75"}
  };

  const portRows=[
    ["bella","리스본","포르투갈",-9.14,38.72,"portugal","iberia","glass,wine,salt"],["lume","안트베르펜","벨기에",4.4,51.22,"habsburg","north","glass,wool,books"],["genoa","제노바","이탈리아",8.93,44.41,"italy","med","silk,glass,paper"],["azur","푼샬","마데이라",-16.91,32.65,"portugal","island","wine,sugar,timber"],
    ["seville","세비야","스페인",-5.99,37.39,"spain","iberia","wine,olive_oil,silver"],["cadiz","카디스","스페인",-6.29,36.53,"spain","iberia","salt,wine,fish"],["porto","포르투","포르투갈",-8.61,41.15,"portugal","iberia","wine,timber,fish"],["barcelona","바르셀로나","스페인",2.17,41.38,"spain","med","wine,weapons,linen"],["valencia","발렌시아","스페인",-0.38,39.47,"spain","med","citrus,silk,rice"],["palma","팔마","스페인",2.65,39.57,"spain","island","olive_oil,salt,fish"],
    ["marseille","마르세유","프랑스",5.37,43.3,"france","med","wine,olive_oil,soap"],["bordeaux","보르도","프랑스",-0.58,44.84,"france","north","wine,paper,grain"],["nantes","낭트","프랑스",-1.55,47.22,"france","north","salt,linen,grain"],["bristol","브리스틀","잉글랜드",-2.59,51.45,"england","north","wool,coal,tin"],["london","런던","잉글랜드",-0.12,51.51,"england","north","wool,weapons,clocks"],["amsterdam","암스테르담","네덜란드",4.9,52.37,"habsburg","north","glass,cheese,clocks"],["hamburg","함부르크","독일",9.99,53.55,"habsburg","north","grain,beer,timber"],["lubeck","뤼베크","독일",10.69,53.87,"habsburg","north","salt,fish,linen"],["copenhagen","코펜하겐","덴마크",12.57,55.68,"neutral","north","fish,grain,timber"],["bergen","베르겐","노르웨이",5.32,60.39,"neutral","north","fish,furs,timber"],["oslo","오슬로","노르웨이",10.75,59.91,"neutral","north","timber,iron,fish"],["stockholm","스톡홀름","스웨덴",18.07,59.33,"neutral","north","iron,furs,timber"],["danzig","단치히","폴란드",18.65,54.35,"neutral","north","grain,timber,amber"],["riga","리가","라트비아",24.1,56.95,"neutral","north","timber,furs,wax"],
    ["dublin","더블린","아일랜드",-6.26,53.35,"england","north","wool,hides,fish"],["venice","베네치아","이탈리아",12.33,45.44,"italy","med","glass,silk,spice"],["naples","나폴리","이탈리아",14.27,40.85,"italy","med","wine,olive_oil,silk"],["pisa","피사","이탈리아",10.4,43.72,"italy","med","marble,wool,wine"],["rhodes","로도스","그리스",28.22,36.44,"ottoman","island","sponge,wine,olive_oil"],["candia","칸디아","크레타",25.13,35.34,"ottoman","island","wine,olive_oil,cheese"],["ragusa","라구사","크로아티아",18.09,42.65,"italy","med","salt,silver,timber"],["athens","아테네","그리스",23.73,37.98,"ottoman","med","olive_oil,marble,wine"],["syracuse","시라쿠사","이탈리아",15.29,37.07,"italy","med","grain,wine,sulfur"],["messina","메시나","이탈리아",15.55,38.19,"italy","med","silk,citrus,wine"],
    ["ceuta","세우타","스페인",-5.31,35.89,"portugal","maghreb","salt,fish,hides"],["algiers","알제","알제리",3.06,36.75,"maghreb","maghreb","coral,hides,grain"],["tunis","튀니스","튀니지",10.18,36.8,"maghreb","maghreb","olive_oil,carpet,grain"],["tripoli","트리폴리","리비아",13.19,32.89,"ottoman","maghreb","dates,hides,salt"],["alexandria","알렉산드리아","이집트",29.92,31.2,"ottoman","ottoman","cotton,paper,spice"],["jaffa","야파","레반트",34.75,32.05,"ottoman","ottoman","citrus,glass,grain"],["beirut","베이루트","레바논",35.5,33.89,"ottoman","ottoman","silk,wine,cedar"],["constantinople","콘스탄티노폴리스","튀르키예",28.98,41.01,"ottoman","ottoman","carpet,weapons,spice"],["salonika","살로니카","그리스",22.94,40.64,"ottoman","ottoman","grain,wool,wine"],["trebizond","트레비존드","튀르키예",39.72,41,"ottoman","ottoman","silk,hazelnut,iron"],["caffa","카파","크림",35.38,45.03,"ottoman","ottoman","grain,furs,salt"],["azov","아조프","러시아",39.42,47.1,"ottoman","ottoman","grain,fish,furs"],["malta","비르구","몰타",14.52,35.89,"neutral","island","cotton,honey,salt"],["oran","오랑","알제리",-0.64,35.7,"maghreb","maghreb","hides,grain,coral"],["sfax","스팍스","튀니지",10.76,34.74,"maghreb","maghreb","olive_oil,salt,fish"],["tangier","탕헤르","모로코",-5.81,35.77,"maghreb","maghreb","hides,grain,salt"],["larache","라라슈","모로코",-6.15,35.19,"maghreb","maghreb","sugar,hides,fish"],["mogador","모가도르","모로코",-9.77,31.51,"maghreb","maghreb","sugar,fish,aloe"],
    ["canary","라스팔마스","카나리아",-15.43,28.12,"spain","island","sugar,wine,citrus"],["arguin","아르긴","모리타니",-16.03,20.6,"portugal","africa","gum,hides,salt"],["elmina","엘미나","가나",-1.35,5.08,"portugal","africa","gold,ivory,pepper"],["cape_verde","리베이라그란데","카보베르데",-25.06,17.02,"portugal","island","salt,sugar,hides"],["cacheu","카셰우","기니비사우",-16.17,12.27,"portugal","africa","ivory,wax,hides"],["bissau","비사우","기니비사우",-15.58,11.86,"africa","africa","ivory,rice,wax"],["sao_tome","상투메","상투메",6.73,0.34,"portugal","island","sugar,ivory,timber"],["luanda","루안다","앙골라",13.23,-8.84,"portugal","africa","ivory,copper,hides"],["benguela","벵겔라","앙골라",13.4,-12.58,"portugal","africa","copper,hides,salt"],["sierra_leone","시에라리온","시에라리온",-13.23,8.48,"africa","africa","ivory,gold,rice"],["sofala","소팔라","모잠비크",34.84,-20.17,"portugal","africa","gold,ivory,ebony"],["mozambique","모잠비크섬","모잠비크",40.73,-15.04,"portugal","africa","ivory,gold,cotton"],["kilwa","킬와","탄자니아",39.52,-8.96,"africa","africa","gold,ivory,coconut"],["zanzibar","잔지바르","탄자니아",39.2,-6.16,"africa","africa","cloves,ivory,coconut"],["mombasa","몸바사","케냐",39.67,-4.05,"africa","africa","ivory,spice,cotton"],["malindi","말린디","케냐",40.12,-3.22,"portugal","africa","ivory,aloe,fish"],["mogadishu","모가디슈","소말리아",45.32,2.04,"africa","africa","incense,hides,ivory"],["massawa","마사와","에리트레아",39.47,15.61,"ottoman","arabia","salt,pearls,coffee"],["aden","아덴","예멘",45.03,12.79,"ottoman","arabia","coffee,incense,spice"],["zeila","제일라","소말릴란드",43.47,11.35,"africa","arabia","coffee,incense,hides"],
    ["jeddah","제다","아라비아",39.17,21.49,"ottoman","arabia","coffee,incense,carpet"],["suez","수에즈","이집트",32.55,29.97,"ottoman","arabia","spice,grain,salt"],["muscat","무스카트","오만",58.41,23.59,"arabia","arabia","incense,dates,pearls"],["hormuz","호르무즈","이란",56.46,27.06,"arabia","arabia","pearls,spice,carpet"],["basra","바스라","이라크",47.78,30.5,"ottoman","arabia","dates,carpet,grain"],["diu","디우","인도",70.99,20.71,"portugal","india","cotton,indigo,salt"],["surat","수라트","인도",72.83,21.17,"india","india","cotton,indigo,spice"],["cambay","캄베이","인도",72.62,22.31,"india","india","cotton,ivory,cornelian"],["goa","고아","인도",73.83,15.49,"portugal","india","pepper,cotton,medicine"],["calicut","캘리컷","인도",75.78,11.26,"india","india","pepper,ginger,cotton"],["cochin","코친","인도",76.27,9.93,"india","india","pepper,cinnamon,ginger"],["colombo","콜롬보","스리랑카",79.86,6.93,"india","india","cinnamon,gems,tea"],["chittagong","치타공","방글라데시",91.83,22.35,"india","india","rice,cotton,silk"],["masulipatnam","마술리파트남","인도",81.13,16.18,"india","india","cotton,dye,rice"],["nagapattinam","나가파티남","인도",79.84,10.77,"india","india","rice,cotton,pearls"],["tuticorin","투티코린","인도",78.13,8.76,"india","india","pearls,salt,cotton"],
    ["malacca","말라카","말레이시아",102.25,2.19,"portugal","seasia","spice,tin,silk"],["aceh","아체","인도네시아",95.32,5.55,"asia","seasia","pepper,gold,coffee"],["pattani","파타니","태국",101.25,6.87,"asia","seasia","tin,rice,spice"],["ayutthaya","아유타야","태국",100.57,14.35,"asia","seasia","rice,ebony,silk"],["brunei","브루나이","브루나이",114.94,4.9,"asia","seasia","camphor,spice,gold"],["banten","반튼","인도네시아",106.15,-6.04,"asia","seasia","pepper,rice,spice"],["sunda_kelapa","순다 켈라파","인도네시아",106.81,-6.12,"asia","seasia","pepper,rice,timber"],["ternate","테르나테","인도네시아",127.39,0.79,"asia","island","cloves,nutmeg,spice"],["tidore","티도레","인도네시아",127.4,0.68,"asia","island","cloves,nutmeg,ebony"],["manila","마닐라","필리핀",120.98,14.6,"asia","seasia","silk,gold,porcelain"],["guangzhou","광저우","중국",113.26,23.13,"asia","china","silk,porcelain,tea"],["quanzhou","취안저우","중국",118.68,24.87,"asia","china","porcelain,tea,paper"],["ningbo","닝보","중국",121.55,29.87,"asia","china","silk,porcelain,tea"],["macau","마카오","중국",113.54,22.2,"portugal","china","silk,porcelain,medicine"],["naha","나하","류큐",127.68,26.21,"asia","japan","sulfur,sugar,porcelain"],["hakata","하카타","일본",130.4,33.59,"japan","japan","silver,swords,paper"],["sakai","사카이","일본",135.47,34.57,"japan","japan","swords,silk,tea"],["nagasaki","나가사키","일본",129.87,32.75,"japan","japan","silver,porcelain,weapons"],
    ["havana","아바나","쿠바",-82.37,23.11,"spain","caribbean","sugar,rum,tobacco"],["santo_domingo","산토도밍고","도미니카",-69.89,18.49,"spain","caribbean","sugar,hides,cocoa"],["santiago_cuba","산티아고 데 쿠바","쿠바",-75.83,20.02,"spain","caribbean","copper,sugar,rum"],["san_juan","산후안","푸에르토리코",-66.11,18.47,"spain","caribbean","sugar,ginger,hides"],["cartagena","카르타헤나","콜롬비아",-75.48,10.39,"spain","caribbean","gold,pearls,cocoa"],["veracruz","베라크루스","멕시코",-96.13,19.17,"spain","americas","silver,cocoa,dye"],["nombre_dios","놈브레 데 디오스","파나마",-79.47,9.58,"spain","caribbean","gold,pearls,spice"],["panama_city","파나마","파나마",-79.52,8.98,"spain","americas","gold,pearls,cocoa"],["campeche","캄페체","멕시코",-90.53,19.85,"spain","caribbean","dye,salt,cocoa"],["santa_marta","산타마르타","콜롬비아",-74.2,11.24,"spain","caribbean","pearls,gold,cocoa"],["callao","카야오","페루",-77.15,-12.06,"spain","americas","silver,gold,wool"],["recife","헤시피","브라질",-34.88,-8.05,"portugal","americas","sugar,timber,cocoa"],["salvador","사우바도르","브라질",-38.5,-12.97,"portugal","americas","sugar,timber,tobacco"],["rio","리우데자네이루","브라질",-43.17,-22.91,"portugal","americas","timber,sugar,gold"]
  ];

  const aliases={soap:"olive_oil",beer:"grain",amber:"jewelry",wax:"medicine",sponge:"coral",cedar:"timber",hazelnut:"grain",sulfur:"gunpowder",honey:"sugar",gum:"rubber",coconut:"dates",indigo:"dye",cornelian:"jewelry",gems:"jewelry",camphor:"medicine",swords:"weapons",tobacco:"spice"};
  const baseMaps=["bella","lume","genoa","azur"];
  const marketFor=(specialties,index)=>{const market={};for(const [i,g] of HL.DATA.goods.entries()){const specialty=specialties.includes(g.id),wave=.88+((index*17+i*11)%29)/100,buy=Math.max(5,Math.round(g.base*wave*(specialty?.62:1.08)));market[g.id]=[buy,Math.max(3,Math.round(buy*.82))]}return market};
  const ports={};
  portRows.forEach((row,index)=>{const[id,name,modern,lon,lat,nation,culture,specialtyText]=row,tier=index<24?1:index<72?2:3,specialties=specialtyText.split(",").map(x=>aliases[x]||x);ports[id]={id,name,modern,lon,lat,x:lon,y:lat,nation:nation,culture,tier,specialties,economy:260+(index*47)%650,industry:220+(index*61)%690,shipyard:1+(index%4),facilities:["market","inn","shipyard","guild","lodge","harbor",...(index%3!==2?["bank"]:[]),...(index%4===0?["estate"]:[])],market:marketFor(specialties,index),hostility:index%19===0?25:0}});
  HL.DATA.ports=ports;
  HL.DATA.portOrder=portRows.map(r=>r[0]);
  const cultureColors={iberia:["#246f83","#d5a06b","#8e442f"],north:["#385f7b","#d7aa78","#4a563d"],med:["#7c4a3b","#d8a26d","#2c6070"],island:["#2d7471","#c98d5c","#835a2d"],maghreb:["#8a6537","#ba7d53","#315f5b"],ottoman:["#6c3f62","#d1a06d","#8a703d"],africa:["#4d6d45","#8f5f3c","#d1a06f"],arabia:["#79603c","#b78355","#365c62"],india:["#8b4b51","#b97c55","#d1a43f"],seasia:["#347067","#a75d3d","#d3a465"],china:["#7c3c3b","#d2a15e","#345f69"],japan:["#425e78","#b46a59","#d8b477"],caribbean:["#326e75","#b56b39","#d0a75c"],americas:["#567142","#a65f3d","#d0a064"]};
  for(const [portIndex,id] of HL.DATA.portOrder.entries()){
    const p=ports[id],palette=cultureColors[p.culture]||cultureColors.med;
    for(const [npcIndex,npcId] of ["guide","merchant","sailor","scribe"].entries())HL.DATA.appearances[`${id}_${npcId}`]={body:["slim","average","broad"][(portIndex+npcIndex)%3],hair:`world_${(portIndex*3+npcIndex)%17}`,outfit:`${p.culture}_${npcId}`,hat:(portIndex+npcIndex)%4===0?"none":`hat_${(portIndex+npcIndex)%9}`,accessory:`${id}_${npcId}`,palette:[palette[0],palette[1],palette[2]],spriteSheet:npcIndex===2?"orso":"citizen"};
    for(const [facilityIndex,facility] of ["market","inn","shipyard","guild","lodge","harbor","mansion"].entries())HL.DATA.appearances[`owner_${id}_${facility}`]={body:["average","broad","slim"][(portIndex+facilityIndex)%3],hair:`owner_${(portIndex+facilityIndex)%19}`,outfit:`${p.culture}_${facility}_owner`,hat:facilityIndex%3===0?"cap":"none",accessory:`${id}_${facility}`,palette:[palette[2],palette[1],palette[0]],spriteSheet:"owner"};
  }

  const legacyMaps={bella:HL.DATA.townMaps.bella,lume:HL.DATA.townMaps.lume,genoa:HL.DATA.townMaps.genoa,azur:HL.DATA.townMaps.azur};
  HL.WorldData={
    portCount:portRows.length,
    activePorts(phase=1){return HL.DATA.portOrder.filter(id=>HL.DATA.ports[id].tier<=phase)},
    townMapFor(id){if(legacyMaps[id])return legacyMaps[id];const p=ports[id],seed=HL.DATA.portOrder.indexOf(id),base=legacyMaps[baseMaps[Math.abs(seed)%4]],map={...base,id,palette:base.palette,visual:base.visual,spawn:[16,16],buildings:base.buildings.map(b=>({...b})),props:base.props.map(o=>({...o,x:Math.max(9,Math.min(21,o.x+((seed%3)-1)*.45))})),npcs:base.npcs.map((n,i)=>({...n,id:`${id}_${n.id}`,name:i===0?`${p.name} 안내인`:n.name,appearanceId:`${id}_${n.id}`,lines:[`${p.name}의 특산품은 ${p.specialties.map(g=>HL.DATA.goods.find(x=>x.id===g)?.name).join(", ")}입니다.`,`${HL.DATA.nations[p.nation].name}의 영향력이 미치는 항구입니다.`]}))};map.collision={...base.collision,solids:base.collision.solids.map(r=>[...r]),doors:base.collision.doors.map(d=>({...d,rect:[...d.rect]})),polygons:[]};return map},
    nearestPort(lon,lat,phase=3,max=2.1){let best=null;for(const id of this.activePorts(phase)){const p=ports[id],d=Math.hypot((lon-p.lon)*Math.cos(lat*Math.PI/180),lat-p.lat);if(d<=max&&(!best||d<best.distance))best={id,distance:d}}return best?.id||null},
    normalizeGood(id){return aliases[id]||id}
  };

  HL.DATA.shipEquipment={
    figureheads:{none:{name:"장식 없음",price:0,stormReduction:0},dragon:{name:"용 선수상",price:900,stormReduction:.15},angel:{name:"천사 선수상",price:1800,stormReduction:.25},dolphin:{name:"돌고래 선수상",price:650,encounterReduction:.1}},
    sails:{square:{name:"사각돛",price:0,tailwind:1.12,headwind:.82},lateen:{name:"삼각돛",price:750,tailwind:1,headwind:1.18},topsail:{name:"복합 상돛",price:1300,tailwind:1.2,headwind:1.05}},
    hulls:{wood:{name:"참나무 선체",price:0,hull:1,speed:1},copper:{name:"구리 외장",price:1600,hull:1.22,speed:.94},cedar:{name:"삼나무 선체",price:1200,hull:.9,speed:1.12}}
  };
  HL.DATA.spriteMeta={frameWidth:108,frameHeight:160,directions:8,walkFrames:[0,1,2,3,2,1],idleFrames:[0,0,0,1],pivot:[54,145],hitRadius:.28,sourceRows:{north:0,east:1,south:2,west:3}};
})();
